### ISSUE TITLE
Configure Jenkins to upload iOS app to testflight

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#105]
Source issue: https://github.com/mlcommons/mobile_app_flutter/issues/16

Currently we upload new builds to testflight manually.
We need to configure Jenkins to upload new builds automatically.

We probably want to do this on demand only, as we probably don't want to see hundreds of minor builds, one for each new commit in master branch. Most changes don't even affect iOS.

**Comment by freedomtan** [comment]
Do it manually and close this for now.
