### ISSUE TITLE
A README file needed

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#11]
We need a `README` file for new users. A modified version of current [Android app one](https://github.com/mlcommons/mobile_app_open/blob/master/android/README.md) should be enough.

**Comment by anhappdev** [comment]
I think we can just move the file `mobile_app_open/android/README.md` to the root folder `mobile_app_open/README.md`.

The instruction for building should also be updated because the path is changed.
OLD:
```
bazel build -c opt //java/org/mlperf/inference:mlperf_app

# Install the app with the command:
adb install -r bazel-bin/java/org/mlperf/inference/mlperf_app.apk
```

NEW
```
bazel build -c opt //android/java/org/mlperf/inference:mlperf_app

# Install the app with the command:
adb install -r bazel-bin/android/java/org/mlperf/inference/mlperf_app.apk
```

**Comment by relja128** [comment]
The repo will contain multiple apps (eventually flutter as well), so the per-app README is not applicable to the whole readme. That's why I moved only the top half of the readme that sort of explains what the repo is about.

As for build instructions, seems like a good change, please update the readme.

**Comment by anhappdev** [comment]
The `mobile_app_open/android/README.md` still refer to the `Makefile` and `WORKSPACE` files in the root folder `mobile_app_open`. 
So for now I will only update the path from `//java/org/mlperf/` to `//android/java/org/mlperf/`, so new user can build the app.
