### ISSUE TITLE
Upload an Android version of the Flutter app for testing

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#111]
Source issue: https://github.com/mlcommons/mobile_app_flutter/issues/321

We need to build Android version of the Flutter app and upload the apk so people interested in it can download and test it.

**Comment by freedomtan** [comment]
The Android version of the Flutter app won't run without network and file access permissions. https://github.com/mlcommons/mobile_app_open/pull/131

**Comment by relja128** [comment]
Proprietary backend files live here:
https://github.com/mlcommons/mobile_back_*
(you need to be an MLC contractor)

**Comment by d-uzlov** [comment]
I have built an APK with all backends (tflite, neuron, pixel, qti, samsung).
The APK can be downloaded from the Releases page: https://github.com/mlcommons/mobile_app_open/releases/tag/v3.0.0-flutter-android-alpha-1

**Comment by mohitmundhragithub** [comment]
Thanks Danil for sharing the APK.
I tried this apk internally on a Qualcomm device. The libqtibackend.so loads just fine, But Qualcomm needs the location of the library to be passed during create.

https://github.com/mlcommons/mobile_app_open/blob/master/mobile_back_qti/cpp/backend_qti/qti_c.cc#L84

This path is used for loading the libs required for DSP communication. These libs are bundled within the apk itself. 
I debugged and found that currently the lib_path is coming as an empty string. Can you please check this part?

**Comment by d-uzlov** [comment]
@mohitmundhragithub, the Flutter app has native lib path hardcoded, it always passes an empty string.
I'll fix it, upload a new APK and ping you when I'm done so you can test if it will work with the fix.

**Comment by d-uzlov** [comment]
@mohitmundhragithub, could you check if this APK works?
https://drive.google.com/file/d/1n_SwqOhtHL2Y-oxxicjoZT_3QjntNMkn/view?usp=sharing

**Comment by mohitmundhragithub** [comment]
I tried this apk shared. But the numbers are too low. Which SNPE SDK and qti backend code base did you use to build the apk?

**Comment by d-uzlov** [comment]
I used SNPE SDK 1.55.0.2958, and the following commit: https://github.com/mlcommons/mobile_app_open/tree/817505143a9374ac99096c16057da1eadf21b7d3

**Comment by mohitmundhragithub** [comment]
I checked further. Looks like this apk provided doesn't load qti backend. Can you please have a look?

	Line 2140: 12-02 10:18:31.417 12644 12644 W FlutterActivityAndFragmentDelegate: A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
	Line 2140: 12-02 10:18:31.417 12644 12644 W FlutterActivityAndFragmentDelegate: A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
	Line 2140: 12-02 10:18:31.417 12644 12644 W FlutterActivityAndFragmentDelegate: A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
	Line 2158: 12-02 10:18:31.456 12644 12688 I flutter : await getNativeLibraryPath() /data/app/~~C6uTDYv6GocmK7tPHLm71w==/org.mlcommons.android.mlperfbench-kOhUvMEGD_wiuzw4aN_ptw==/lib/arm64
	Line 2159: 12-02 10:18:31.462 12644 12688 I native  : cpp/flutter/dart_backend_match.cc:14 checking backend 'libtflitebackend.so' ...
	Line 2162: 12-02 10:18:31.462 12644 12688 I native  : cpp/flutter/dart_backend_match.cc:43 checking pbdata
	Line 2163: 12-02 10:18:31.462 12644 12688 I native  : cpp/flutter/dart_backend_match.cc:70 backend matches
	Line 2648: 12-02 10:18:38.203 12644 12688 I flutter : Running Benchmark:IC_tpu_uint8 in performance mode...

**Comment by d-uzlov** [comment]
Seems like I messed up the previous build. Sorry for this.
Here is a new one: https://drive.google.com/file/d/1993wNscwePY1jReyvE5JCs2doDMCqp4a/view?usp=sharing

**Comment by mohitmundhragithub** [comment]
I was able to run this apk with qualcomm backend. 
But, looks like that the configuration for offline case has some changes, because I am getting very low score, ~170QPS instead of ~2500QPS.

**Comment by d-uzlov** [comment]
@mohitmundhragithub, I'll try investigating this.

In the meantime, could you approve https://github.com/mlcommons/mobile_app_open/pull/156?

**Comment by relja128** [comment]
Closing this off. Please continue perf work in other issues.
