### ISSUE TITLE
Merge Android and Flutter makefiles

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#112]
We need to have uniform integrated makefiles across the repo.
Makefiles from the Flutter app repo don't match the style used in this repo, so they need to be significantly rewritten.

Parent issue: https://github.com/mlcommons/mobile_app_open/issues/92

**Comment by d-uzlov** [comment]
@mcharleb, is there a particular reason why we use `@` everywhere in all makefiles to suppress the command echoing?

**Comment by relja128** [comment]
Top level make files should be minimal, include app-specific make files from the subdirs.

**Comment by anhappdev** [comment]
If the Android app will be deprecated in favor of Flutter app. I think it's best not to merge them. Just move the Makefile for Android into `android` folder.

**Comment by d-uzlov** [comment]
I think that we should do the following in context of this task:

1. Pull make targets for the Flutter app to the repository root (and refactor them in the process)
2. Integrate all backends with the Flutter app
3. Add commands to build Flutter app with docker
4. And because all this would be too much for one makefile: refactor our root make file, moving Android-app-related stuff to the `/android` directory.

I also wanted to change the way we handle docker. Now there are just monstrous commands for everything in docker. I wanted to split each command (ones that we have now and ones that we will add in the future) into 2 parts: the `make command` itself, which builds what is needed locally, and `make docker/command`, that mounts docker container and runs `make command` inside.

And we should probably create a bunch more issues which would be linked to this one, and this one should be used just for tracking the status of the refactoring.

**Comment by d-uzlov** [comment]
>If the Android app will be deprecated in favor of Flutter app

Another thing to note is that while the Android app itself will be deprecated, at least half of the configs and build commands (which were previously used for the Android app) are actually for backends, which are not going to be deprecated any time soon.

**Comment by anhappdev** [comment]
>Another thing to note is that while the Android app itself will be deprecated, at least half of the configs and build commands (which were previously used for the Android app) are actually for backends, which are not going to be deprecated any time soon.

I would just copy those configs and command to some place outside the `android` folder. We should not have dependency on deprecated code. Sometime in the feature we will probably mark the `android` folder as deprecated and do not want to touch it anymore.

**Comment by anhappdev** [comment]
@d-uzlov I think we can do the first point of #153 in this issue.

**Comment by d-uzlov** [comment]
@anhappdev, which exact common resources are you talking about?

**Comment by anhappdev** [comment]
> which exact common resources are you talking about?

Those you mentioned earlier:

> Another thing to note is that while the Android app itself will be deprecated, at least half of the configs and build commands (which were previously used for the Android app) are actually for backends, which are not going to be deprecated any time soon.
