### ISSUE TITLE
Pull cpp folder out of android and flutter directories

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#113]
We have 2 mostly duplicated `cpp` folders: [android/cpp](https://github.com/mlcommons/mobile_app_open/tree/347d490c1ef90cf62a37ec097ba8d846a1b8ead6/android/cpp) and [flutter/cpp](https://github.com/mlcommons/mobile_app_open/tree/347d490c1ef90cf62a37ec097ba8d846a1b8ead6/flutter/cpp).
Folders were last synced several weeks ago, so there are few differences.

We need to pull `cpp` directory to to the top level near `android` and `flutter` directories, merging its contents.

**Comment by relja128** [comment]
Leave as-is. We will deprecate Android in ~6 months.

**Comment by relja128** [comment]
Having them in the same location helps with build - backends would pull headers in from only one spot. Let's do this.
