### ISSUE TITLE
Header files for Neuron not found 

### ISSUE THREAD

**Issue by K-R-U-T-I** [mlcommons/mobile_app_open#115]
While building MLPerf mobile app by running below bazel command

bazel-3.7.2 --output_user_root=/opt/cache/bazel build -c opt --cxxopt='--std=c++14' --host_cxxopt='--std=c++14' --host_cxxopt='-Wno-deprecated-declarations' --host_cxxopt='-Wno-class-memaccess' --cxxopt='-Wno-deprecated-declarations' --cxxopt='-Wno-unknown-attributes' --//android/java/org/mlperf/inference:with_mediatek="1" --fat_apk_cpu=arm64-v8a //android/java/org/mlperf/inference:mlperf_app

It's giving these errors.

mobile_back_tflite/cpp/backend_tflite/tflite_c.cc:24:10: fatal error: 'neuron/APUWareUtilsApi.h' file not found
#include "neuron/APUWareUtilsApi.h"

mobile_back_tflite/cpp/backend_tflite/tflite_c.cc:39:10: fatal error: 'neuron/neuron_delegate.h' file not found
#include "neuron/neuron_delegate.h"

Here's the screenshots:

![Screenshot from 2021-11-02 13-31-16](https://user-images.githubusercontent.com/38699938/139880998-a94a669f-4cb0-4e20-931f-b25d045e2c6b.png)

![Screenshot from 2021-11-02 13-31-27](https://user-images.githubusercontent.com/38699938/139881005-b248c7ef-f184-4dd0-a662-39ddfd888337.png)

**Comment by mcharleb** [comment]
@K-R-U-T-I  Are you building the master branch? Did you try "make WITH_MEDIATEK=1 app" ?

**Comment by relja128** [comment]
Also, per @freedomtan - you seem to be running bazel with sudo. This could cause issues if su has access to a different set of files than the regular user.

**Comment by freedomtan** [comment]
@K-R-U-T-I  for you reference, The following works for me on both Linux and macOS

```
bazel build -c opt --cxxopt='--std=c++14' \
  --host_cxxopt='--std=c++14' \
  --host_cxxopt='-Wno-deprecated-declarations' --host_cxxopt='-Wno-class-memaccess' \
  --cxxopt='-Wno-deprecated-declarations' --cxxopt='-Wno-unknown-attributes' \
  --//android/java/org/mlperf/inference:with_mediatek="1" \
  --fat_apk_cpu=arm64-v8a \
  //android/java/org/mlperf/inference:mlperf_app
```
Note that I didn't use `sudo` and didn't set bazel cache.

Further information: those headers are in Neuron delegate repo, they are supposed to be retrieved and placed into bazel cache. See https://github.com/mlcommons/mobile_app_open/blob/master/WORKSPACE#L88-L95
```
# Neuron Delegate

http_archive(
    name = "neuron_delegate",
    sha256 = "2e4600c99c9b4ea7a129108cd688419eeef9b2aeabf05df6f385258e19ca96c4",
    strip_prefix = "tflite-neuron-delegate-2.6.0",
    urls = ["https://github.com/MediaTek-NeuroPilot/tflite-neuron-delegate/archive/v2.6.0.tar.gz"],
)
```

**Comment by relja128** [comment]
Closing this off. Please file a new issue if running without sudo is a problem.

**Comment by K-R-U-T-I** [comment]
Hi @mcharleb, I built the app with flag WITH_MEDIATEK=1 & from the master branch.

Hi @freedomtan, @relja128 Thanks for your response.

After including missing files from this [repository](https://github.com/MediaTek-NeuroPilot/tflite-neuron-delegate/tree/master/neuron), issue will be resolved.
