### ISSUE TITLE
Need more instructions for adding custom backend

### ISSUE THREAD

**Issue by mkankana** [mlcommons/mobile_app_open#118]
1. Followed the instructions provided in the [adding-custom-backend](https://github.com/mlcommons/mobile_app_open/blob/master/flutter/documentation/adding-custom-backend.md) . 
2. Added openvino source to the [cpp/backend_openvino](https://github.com/mlcommons/mobile_app_open/tree/flutter_openvino/flutter/cpp/backend_openvino).
3. I'm new to make and flutter , when trying to build with command `make ENABLE_BACKEND_OPENVINO=1 backends/openvino-windows windows` I get the below error.

`make: *** No rule to make target 'backends/openvino-windows'.  Stop.` 

4. Could you also please point me to the source that call the .exe file and also how the parameter are passes ( example : scenario , batch size ).

**Comment by d-uzlov** [comment]
>`make: *** No rule to make target 'backends/openvino-windows'. Stop.`

Maybe you have a typo on the name of your make target?
Could you provide your modified makefile?

>Could you also please point me to the source that call the .exe file and also how the parameter are passes ( example : scenario , batch size ).

App iterates over available backends here: https://github.com/mlcommons/mobile_app_open/blob/347d490c1ef90cf62a37ec097ba8d846a1b8ead6/flutter/lib/benchmark/benchmark.dart#L72

App calls the external backend, for example, here:
https://github.com/mlcommons/mobile_app_open/blob/347d490c1ef90cf62a37ec097ba8d846a1b8ead6/flutter/cpp/backends/external.h#L144
https://github.com/mlcommons/mobile_app_open/blob/347d490c1ef90cf62a37ec097ba8d846a1b8ead6/flutter/cpp/backends/external.h#L151
https://github.com/mlcommons/mobile_app_open/blob/347d490c1ef90cf62a37ec097ba8d846a1b8ead6/flutter/cpp/backends/external.h#L164

Parameters are passed via a pure C interface defined in [backend_c.h](https://github.com/mlcommons/mobile_app_open/blob/347d490c1ef90cf62a37ec097ba8d846a1b8ead6/flutter/cpp/c/backend_c.h).
App expects the backend to be a dynamic-link library (.dll on Windows). I never tested using executables as dlls, and I'm not sure if it's even possible.

**Comment by mkankana** [comment]
> Could you provide your modified makefile?

Here is the [modified make](https://github.com/mlcommons/mobile_app_open/blob/flutter_openvino/flutter/Makefile) file . 

> App expects the backend to be a dynamic-link library (.dll on Windows). I never tested using executables as dlls, and I'm not sure if it's even possible.
Is it a hard rule for the backend to be a library file to integrate into the app ?

**Comment by mkankana** [comment]
@d-uzlov  
I change our backend from .exe to .dll as per the requierments.
Also added openvino-windows as the backend for windows on my branch to test the functionality.
Now the build with command `make ENABLE_BACKEND_OPENVINO=1 backends/openvino-windows windows`  throws this error 

> INFO: Build completed successfully, 1 total action
chmod +w bazel-bin/cpp/flutter/backend_bridge.dll
chmod: cannot access 'bazel-bin/cpp/flutter/backend_bridge.dll': No such file or directory
make: *** [Makefile:126: backend-bridge-windows] Error 1

**Comment by d-uzlov** [comment]
>Now the build with command make ENABLE_BACKEND_OPENVINO=1 backends/openvino-windows windows throws this error

This is an issue introduced when I merged configs.
It will be fixed soon. Sorry for the inconvenience.

>Is it a hard rule for the backend to be a library file to integrate into the app ?

Launching a separate app for each call to backend would significantly slow down the benchmark.

I guess you've already solved the issues you had with the makefile?

**Comment by d-uzlov** [comment]
>This is an issue introduced when I merged configs.
It will be fixed soon. Sorry for the inconvenience.

We've merged a fix for this issue into master branch.

**Comment by relja128** [comment]
@mcharleb volunteered to help with the documentation
