### ISSUE TITLE
Remove mobile_app_flutter once issues are resolved, and end of January

### ISSUE THREAD

**Issue by relja128** [mlcommons/mobile_app_open#124]

**Comment by freedomtan** [comment]
Let's wait until the integrated flutter app tested.

**Comment by anhappdev** [comment]
I think we can remove the `mobile_app_flutter` repo. The `mobile_app_open` is much different from `mobile_app_flutter` now.

**Comment by freedomtan** [comment]
Let's do it.

**Comment by freedomtan** [comment]
@freedomtan will try to remove the repo to close this.

**Comment by freedomtan** [comment]
I cannot do it either. @jwookiehong

**Comment by mkankana** [comment]
repo is now archived. Thanks to Bruno.
