### ISSUE TITLE
Allow same binary to be used for submission and press release

### ISSUE THREAD

**Issue by relja128** [mlcommons/mobile_app_open#125]
We need a unified binary (we already can make this, but we should tighten the rules to disallow per-vendor front end modifications).
The same binary should be able to generate submission and performance results. We will need to fetch config data from github, and then failing that, fetch from SD card.

[For closed submissions only for now]

**Comment by anhappdev** [comment]
> We will need to fetch config data from github, and then failing that, fetch from SD card.

1. With config data you mean the [tasks_v2.pbtxt](https://github.com/mlcommons/mobile_models/blob/main/v1_0/assets/tasks_v2.pbtxt), right? 
2. Should the path to the config file in SD card just be hard-coded to something like `/sdcard/mlperf_datasets/custom_tasks.pbtxt`?
3. Should the change be made for Android or Flutter or both app?

**Comment by relja128** [comment]
1) With config data you mean the tasks_v2.pbtxt, right?
Yes, but if you need additional config data elsewhere, that's ok.

2) Should the path to the config file in SD card just be hard-coded to something like /sdcard/mlperf_datasets/custom_tasks.pbtxt?
No, see below.

3) Should the change be made for Android or Flutter or both app?
Flutter app.

----

What we want to achieve:
1) The press can run the app as-is, no switches needed
2) Same binary can be validated and then released
3) MLCommons developers have an easy way of running the right dataset on the unified binary

We will continue discussion.

One idea: 
By default, the app will use files on the SD card if found, else it will download to cache directory, and use the cache.
There will be a switch to force SD-card-only or download-only behavior.

**Comment by anhappdev** [comment]
I think we should add a file picker to the setting screen.
In the setting screen, the user can set the paths to different datasets and models.
On the first start, the paths will be populated using the default paths from the default `tasks.pbtxt` file. After that, the user can change it (using a file picker for a local path or just enter text for a URL).
This would be a clean approach without too many custom logics for different user groups.

**Comment by relja128** [comment]
We discussed having an edit box with paths in settings, but decided it was unwieldly because of the number and length of paths.

For now, implement the following:
* By default, the app will use files on the SD card if found, else it will download to cache directory, and use the cache.

We will discuss and design the override switches in settings in a future meeting.

**Comment by Mostelk** [comment]
Clearing cache will clear the downloaded datasets for performance mode as well, Can we have a Toggle switch (similar to what we have to choose between performance and submission mode) to switch between HTTP vs Card: in case of HTTP it uses the models in the Cache and downloads them if missing, in case of Card it uses the modes on SDCard and throws an error if cannot find them. This way there is no confusion which models are used. By default, the switch should be at HTTP, similar to now, where the switch is at Performance model by default

**Comment by anhappdev** [comment]
> Clearing cache will clear the downloaded datasets for performance mode as well, Can we have a Toggle switch (similar to what we have to choose between performance and submission mode) to switch between HTTP vs Card: in case of HTTP it uses the models in the Cache and downloads them if missing, in case of Card it uses the models on SDCard and throws an error if cannot find them. This way there is no confusion which models are used. By default, the switch should be at HTTP, similar to now, where the switch is at Performance mode by default

We can discuss it in the next mobile meeting. For now, I just implemented the simple behavior first (delete all loaded resources).

**Comment by relja128** [comment]
Let's go with @Mostelk's proposal. This will involve having separate tasks files - one for local (SD), one pointing at URLs which will then populate the cache.
The key point is that the cache and the local SD card files are separate entities.
