### ISSUE TITLE
Convert use of mobile repo to mobile_open

### ISSUE THREAD

**Issue by mcharleb** [mlcommons/mobile_app_open#130]
The code currently used the private mobile repo instead of the mobile_open repo.

**Comment by relja128** [comment]
Per mcharleb this is primarily in docs

**Comment by relja128** [comment]
Mohit to look into it

**Comment by mcharleb** [comment]
The DLC building code in mobile_back_qti used to reference it before the updates to generate the datasets was merged. I don't know if there are any further references or not.

**Comment by mohitmundhragithub** [comment]
I checked and found that all the repos are changed to mobile_open.
