### ISSUE TITLE
Unify guides and scripts for dataset creation

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#144]
Currently, there are 3 locations regarding dataset for the MLPerf app and the code in those locations are also overlapping.

* [mobile_datasets](https://github.com/mlcommons/mobile_datasets): Contains scripts to create performance-only test sets for MLPerf Mobile
* [mobile_app_open/datasets](https://github.com/mlcommons/mobile_app_open/tree/master/datasets): Contains scripts to prepare test and calibration data used for accuracy evaluation and model quantization.
* [mobile_app_open/android/cpp/datasets](https://github.com/mlcommons/mobile_app_open/tree/master/android/cpp/datasets): Contains instruction and scripts to create dataset for this MLPerf Mobile App.

I suggest we agree on one location for the dataset. Since we already have `mobile_app_open`, `mobile_model` and `mobile_datasets` repos. The last one `mobile_datasets` repo seems to be a good place for it.

Related to #99.

**Comment by relja128** [comment]
Per our discussion, we are keeping the structure as is. Notes:
* mobile_datasets - scripts to generate performance mode datasets that are later downloaded by the app
* mobile_app_open/datasets/utils - scripts to generate calibration and validation files. Want this to be version controlled along with the app code.
* mobile_app_open/android/cpp/datasets - legacy app instructions. Will get retired along with the app
