### ISSUE TITLE
Update TensorFlow to 2.8.0

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#145]
TF 2.7 is out: https://github.com/tensorflow/tensorflow/releases/tag/v2.7.0 and have many improvements.
We should update TensorFlow to 2.7.0 (the current used version is 2.6.0)
This will also close the PR #86 without merging it.

**Comment by relja128** [comment]
To be discussed in the policy meeting.

**Comment by relja128** [comment]
@freedomtan - pro update, but there may be an issue with CoreML delegate that we would have to deal with. This affects only iOS.

**Comment by relja128** [comment]
This was approved. Postponing until we figure out our performance delta over the old app.

**Comment by freedomtan** [comment]
Let's delay this for the flutter app

**Comment by freedomtan** [comment]
[TensorFlow 2.8.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.8.0) was release last week.

**Comment by freedomtan** [comment]
#278 is merged
