### ISSUE TITLE
Create Docker image for code formatting

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#148]
We should have a Docker image contains all the tools needed to run code formatter, and a short guide how to use it.
All the code formatting tools and chosen code styles should match those used in our CI/CD pipeline.

**Comment by anhappdev** [comment]
@d-uzlov: Danil, how do you run code formatter for this repo? Are these tools installed locally? Do you have a problem with other repos if they use other code styles (version) but for the same language?

**Comment by d-uzlov** [comment]
I have all the required tools installed locally.
To format everything, I just run `make format`.
The result matches our CI checks.
Our CI also checks other things, for which we can run `make lint`.

I should have probably documented these commands somewhere.

>Do you have a problem with other repos if they use other code styles (version) but for the same language?

Do you mean if I dislike it or not? I don't mind.
Well, I may not like some particular code styles but it's not like I can do something about it other than autoformat the code I write to be compliant with the required style.

**Comment by anhappdev** [comment]
> Do you mean if I dislike it or not? I don't mind.

I mean, how you manage multiple version on the same computer. I worked on multiple repos, and they use slightly different version and produce slightly different result, which causes CI test to fail.

That is the problem I try to solve with Docker (multiple environment on same computer). Of course, it is also easier to just run 'docker run' instead of installing all the tools locally.

**Comment by d-uzlov** [comment]
I don't have much experience with using contributing to repositories with the same language but different code styles. It just so happened that the projects I worked on so far used different languages. Well, actually, not languages, just different formatting tools.

We shouldn't have issues with mismatched styles, because we specify the rules we check in command arguments. For example, we use `google` style for C++ files, and we just specify it on CI and in the format makefile. If someone uses a different style for C++ files, it doesn't change anything for our formatting commands.
We could theoretically get some issues if the tools we use make incompatible changes. I find it very unlikely, but it's possible.

I agree that running one docker command could be easier than installing everything manually.

**Comment by anhappdev** [comment]
Since you already set up the formatter for CI pipeline. Would this be a quick task for you? Else, I can also do it.

**Comment by d-uzlov** [comment]
How do you think, where should we put Dockerfile for the image with formatting utils?

**Comment by anhappdev** [comment]
I think we can have a folder named `tools` at the root level. Then a folder `formatter` inside it. Then we put all the formatting related stuffs in there. Also move the `format.mk` to `tools/formatter/format.mk`. The Docker file would be in `tools/formatter/Dockerfile`

**Comment by d-uzlov** [comment]
Will we keep anything else in the `tools` folder?

**Comment by anhappdev** [comment]
I would also move the `datasets` folder into `tools` but don't know what the others think. 
And if there is no hard requirements where all the `yaml` files for CI/CD must be, I would also move them into `tools/ci`.

**Comment by d-uzlov** [comment]
There is a hard requirement that github CI configs live in `/.github/workflows`.
We could move GCP cloudbuild configs to somewhere else (right now we only have one file). I think it would be easier to understand if we keep it near the Github CI files.

**Comment by d-uzlov** [comment]
Overall I like the idea to move formatting stuff to `/tools/format`, or something, looks reasonable.
And I personally would support the idea to rename `/datasets` folder to `/tools/datasets`.

**Comment by anhappdev** [comment]
> There is a hard requirement that github CI configs live in `/.github/workflows`. We could move GCP cloudbuild configs to somewhere else (right now we only have one file) but I think it would be easier to understand if we keep it near the Github CI files.

Yes, I know some CI services have a hard requirement where the config files must be. I think we just leave the CI config files there unchanged for now.

**Comment by anhappdev** [comment]
@d-uzlov: Danil, did you start working on this? If not I can do it, since I need it today. Just want to avoid duplicated work.

**Comment by d-uzlov** [comment]
No, I was going to start tomorrow.
You can take it.

**Comment by anhappdev** [comment]
> No, I was going to start tomorrow. You can take it.

Ok.
