### ISSUE TITLE
Deprecate native Android app in favor of Flutter app

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#153]
Since we will deprecate the Android app located in `android` folder sometime in the future. I am going to make a checklist of things to consider:

1. The Flutter app shouldn't have any dependencies on the Android app. Any shared code used by Flutter app, but located in `android` directory, should be copied to other places outside `android`.
2. Check if we can build the Android app successfully, then tag that commit and add a note to `android/README.md` that it is the last supported commit for Android app.
3. `android` folder should be marked / renamed to `android_deprecated`
4. Disable any CI steps for Android app
5. (to be updated)

**Comment by relja128** [comment]
This is a good list, but we shouldn't do any of this work before we start the deprecation process (likely after the 2.0 release).

**Comment by anhappdev** [comment]
We now have the Android app maintained in the `android-v2` branch, and Flutter app maintained in the `master` branch.
