### ISSUE TITLE
Old app: add one more segmentation task to tasks list

### ISSUE THREAD

**Issue by relja128** [mlcommons/mobile_app_open#162]

**Comment by Mostelk** [comment]
For V2,0 next submission: we have a new segmentation model called MOSAIC. For Soft transition of models and investigation of new proposal efficacy, we agreed model replacements will be in soft transition. Hence, the newer model MOSAIC will replace the older DLV3+ model for the Segmentation task in current task list and task called "v2.0 Image Segmentation", and the current Segmentation task will be copied as is (with same DLV3+ model) to the end of the run (called "v0.7 Image Segmentation" ). This is to be done for both Performance Mode and Submission Mode. The naming can change, but looking at the UI this naming may fit.

**Comment by d-uzlov** [comment]
The APK is available on the Releases page: https://github.com/mlcommons/mobile_app_open/releases/tag/v2.0.1-alpha-mosaic

**Comment by relja128** [comment]
Per @Mostelk - UI looks good and the right model has been picked up.

**Comment by relja128** [comment]
Please integrate into master. Everyone should start working on this version of the app for the new submission.
