### ISSUE TITLE
Add toggle switch to choose between internet resources or local resources.

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#168]
Ref: https://github.com/mlcommons/mobile_app_open/issues/125#issuecomment-987601695

Add toggle switch to choose between internet resources and local resources.
There will be two configuration files, one with only local paths and one with only HTTP paths.
Local resources and HTTP resources will be stored separated in different folders.

**Comment by anhappdev** [comment]
Add a toggle switch to setting screen.
In offline mode, an error will be raised if the app tries to use internet resources. Multiple configurations (multiple `tasks.pbtxt` can already be defined via `json` file. See [this guide].(https://github.com/mlcommons/mobile_app_open/blob/dd39478d334b2bf0b305f8f62d1b6246bad6df06/flutter/documentation/custom-tasks.md#using-custom-taskspbtxt-file)

**Comment by Mostelk** [comment]
This message I get when setting 'Offline mode' switch without modifying the tasks file: However, we do need the performance datasets downloaded, and only the model. e.g. tflite can be sideloaded. Can the Offline mode switch just point to a second preset tasks file (which can have the models sideloaded on sdcard and the datasets downloaded) 
![Screenshot_20211216-223546](https://user-images.githubusercontent.com/57555939/146501418-3b735475-bf57-48c7-b1bb-b1641c23e322.jpg)

**Comment by anhappdev** [comment]
The performance datasets will always be downloaded or provided, else the app cannot run the benchmark, right?
What we can do is doing the offline check only for models and ignore the datasets. Is this ok?

Regarding a second task file, user should be able to add it easily following [this guide](https://github.com/mlcommons/mobile_app_open/blob/dd39478d334b2bf0b305f8f62d1b6246bad6df06/flutter/documentation/custom-tasks.md#using-custom-taskspbtxt-file). 
I am not sure about pointing to a fixed task file when offline mode is enabled. That mean the app can have only 2 task files. It reduces the flexibility of having multiple task files the app currently have. And then there maybe an issue when defining paths to local resources in only one task file for multiple platforms (iOS, Android, Windows).

**Comment by Mostelk** [comment]
Yes, Performance datasets have to be downloaded for consistency. For adding second task file, where can we locate benchmarksConfigurations.json so we can add it?

**Comment by anhappdev** [comment]
When the app starts for the first time, it creates a file named `benchmarksConfigurations.json` in the root application directory. The root application directory is platform-dependent.
* iOS: `/MLPerf`
* Android: `/Android/data/org.mlcommons.android.mlperfbench/files`
The section [using-external-resources](https://github.com/mlcommons/mobile_app_open/blob/dd39478d334b2bf0b305f8f62d1b6246bad6df06/flutter/documentation/custom-tasks.md#using-external-resources-on-an-iphone) has it described in more detail.

**Comment by anhappdev** [comment]
> How is the app going to choose which task file to run?
User selects it in the Settings screen.

**Comment by anhappdev** [comment]
Another option would be just showing a warning dialog (app can continue) instead of error (app cannot continue) and keep the check for both datasets and models.

**Comment by anhappdev** [comment]
As discussed in the meeting, we chose to just showing a warning dialog (app can continue) instead of error (app cannot continue) and keep the check for both datasets and models.
