### ISSUE TITLE
Standardize accuracy result display

### ISSUE THREAD

**Issue by Mostelk** [mlcommons/mobile_app_open#169]
Currently the accuracy is displayed as dd.pp%, 0.pppp, 0.pppp, dd.ppppp, dd.pp% for the 5 tasks, I suggest to normalized the display for all of them to be like image classification dd.pp% e.g 75.50%

**Comment by Mostelk** [comment]
this is how current app currently displays: 75.84%, 0.2763, 0.5390, 93.9833, 75.73%
according to these reference, display is better standardized like this: 75.83, 27.63, 53.90, 93.98, 75.73
Deeplab: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7913730
MobileDet: https://arxiv.org/pdf/2004.14525.pdf
MobileBert: https://arxiv.org/pdf/2004.02984.pdf

**Comment by TheKanter** [comment]
is this the display in the app? Where exactly?

**Comment by Mostelk** [comment]
E.g. screenshot from 1.1. results e.g. https://github.com/mlcommons/mobile_submission_1.1/blob/master/closed/Qualcomm_Innovation_Center/results/SDM778G/Screenshot_20210916_160208.jpg

**Comment by freedomtan** [comment]
`75.83, 27.63, 53.90, 93.98, 75.73` (without showing the percent sign) looks fine to me.
