### ISSUE TITLE
Change parsing logic of location path in tasks.pbtxt

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#171]
Currently, the Flutter app will replace `mlperf_datasets` with `external_resources`. See [this README](https://github.com/mlcommons/mobile_app_open/blob/0e161989a7d17456f78c5c83708b9250ce81a83d/flutter/documentation/custom-tasks.md?plain=1#L27).
This seems to be a workaround to make the Flutter app compatible with the [tasks_v2.pbtxt](https://github.com/mlcommons/mobile_models/blob/main/v1_0/assets/tasks_v2.pbtxt) used in the Android app.

This is quite confusing because if the path defined the `tasks.pbtxt` is `/sdcard/mlperf_datasets/some/folders/test.txt` then the path on iPhone is `/MLPerf/external_resources/some/folders/test.txt`.

We should remove this logic and use the location defined in `tasks.pbtxt` as is.

**Comment by anhappdev** [comment]
@d-uzlov Can you provide some context about this logic?

**Comment by d-uzlov** [comment]
I can't say too much about this.
This logic was implemented before I started working on this project. I guess that using `external_resources` as directory name was an arbitrary choice.

>We should remove this logic and use the location defined in tasks.pbtxt as is.

I guess we can remove this logic for Android, but all paths in tasks file are defined for Android, and don't even make sense on other platforms. There is no `/sdcard` folder on either iOS or Windows.
On iOS we can probably reduce the logic from `replace /sdcard/mlperf_datasets with <app directory>/external_resources` to `replace /sdcard with <app directory>`.
I'm not sure what would be the best approach on Windows. Maybe we could say that `<app directory>` on Windows is literally directory where `.exe` file is located. It would probably be more convenient to use than some obscure Windows-specific `%localappdata%` path, or whatever Windows suggests to use for user-specific app data.

**Comment by d-uzlov** [comment]
> On iOS we can probably reduce the logic from `replace /sdcard/mlperf_datasets with <app directory>/external_resources` to `replace /sdcard with <app directory>`.

Well, actually the problem here would be that someone could use `/sdcard/loaded_resources` path in their tasks file and mess with our cache.
Not sure if we care about this.

**Comment by anhappdev** [comment]
A solution could be, that we require all data must be placed in the app storage directory. The path in `tasks.pbtxt` must be prefixed with `app://` for local resources, then `app://` will be replaced with a full path to app directory which is platform-specific.
So `app:///path/to/file.txt` in the `tasks.pbtxt` would be translated to `/platform/specific/app/root/directory/path/to/file.txt`.

**Comment by d-uzlov** [comment]
I like the idea.
I think we should discuss it at tomorrow meeting.

**Comment by d-uzlov** [comment]
As long as the actual directory is accessible, the changes should not be a problem.
Let's create a PR with this `app://` change and test that the application directory used in this PR is accessible on all devices tested.
