### ISSUE TITLE
Refactor Flutter files

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#172]
We have few files in the Dart/Flutter sources that are hard to read and navigate.
[benchmark.dart](https://github.com/mlcommons/mobile_app_open/blob/0e161989a7d17456f78c5c83708b9250ce81a83d/flutter/lib/benchmark/benchmark.dart) — 670 lines
[resource_manager.dart](https://github.com/mlcommons/mobile_app_open/blob/0e161989a7d17456f78c5c83708b9250ce81a83d/flutter/lib/benchmark/resource_manager.dart) — 477 lines
But the primary reason for the inconvenience is the lack of proper structure, in these and in some of the smaller files.
It would be nice to refactor it.

Estimated required time: ~~1-2 days~~ 1-2 weeks.

This is a low priority task.

**Comment by d-uzlov** [comment]
Currently the only file that really needs refactoring is `flutter/lib/benchmark/state.dart`:
https://github.com/mlcommons/mobile_app_open/blob/40e01139b89e73acada30f0966f7d116ad7cdc7b/flutter/lib/benchmark/state.dart
Its current structure may significantly increase time needed to modify anything related to it. I haven't needed to adjust anything in it lately but we will definitely need to fix it at some point.

**Comment by freedomtan** [comment]
Close it for now. May reopen it with more details later
