### ISSUE TITLE
App crash when different tflite model is loaded

### ISSUE THREAD

**Issue by K-R-U-T-I** [mlcommons/mobile_app_open#173]
After downloading Mobilenet Edge TPU pre-trained model from [here](https://storage.cloud.google.com/mobilenet_edgetpu/checkpoints/mobilenet_edgetpu_224_1.0.tgz). 

I converted it to tflite with --input_shapes=1,224,224,3 --input_value_ranges=-1,1 --quantize=True --allow_missing_quantization_ranges=True flags. Added source tflite url in tflite_settings.h & tflite_settings_mtk.h

Here's the screenshot, I modified src path of IC_tpu_uint8 & OD_uint8. (For Object detection, Tflite is generated from Mobilenet v2 quantized model)

![Screenshot from 2021-12-14 12-33-16](https://user-images.githubusercontent.com/38699938/145949213-fee90b6a-13cd-4c73-9f4f-782fd4ec574a.png)

But, It's showing this error at the time of running Image classification & Object detection models that "The model is not a valid Flatbuffer buffer".

![Screenshot from 2021-12-07 14-44-030](https://user-images.githubusercontent.com/38699938/145947840-851abab2-25b9-4ca1-9411-7e5781f0018e.png)

I tried changing - private static final int BUFFER_SIZE = 4096; in CalculatingActivity.java to different values but still facing the same issue.

Do I need to do any other modifications in code to use new different tflite model?

**Comment by relja128** [comment]
You have to make sure the model is valid, and that it is not compressed. Other than that, there should be no additional code changes needed. We don't have an easy solution to this, other than for someone to debug, try it with a different model, etc.

**Comment by relja128** [comment]
Also, please make sure that the URL you are downloading from is a .../raw/.. URL otherwise github will return back a web page instead of the file itself. Take a look at the other model paths to see how they're expressed.

**Comment by freedomtan** [comment]
to be more specific, please use `https://github.com/K-R-U-T-I/ML-Benchmarking/raw/main/mobilenetEdgetpu_uint8.tflite` instead of `https://github.com/K-R-U-T-I/ML-Benchmarking/blob/main/mobilenetEdgetpu_uint8.tflite`

**Comment by K-R-U-T-I** [comment]
Yes, by specifying the raw URL (https://github.com/K-R-U-T-I/ML-Benchmarking/raw/main/mobilenetEdgetpu_uint8.tflite), the issue got resolved.
