### ISSUE TITLE
Flutter app did not pick up the Samsung backend when built

### ISSUE THREAD

**Issue by relja128** [mlcommons/mobile_app_open#177]
Per @Mostelk - the build which is supposed to contain the Samsung backend has the same performance as the regular tflite version of the app.

**Comment by d-uzlov** [comment]
A new version was uploaded here: https://github.com/mlcommons/mobile_app_open/issues/159#issuecomment-1000685411
It contains several fixes, which may also affect this issue.
@Mostelk, please, test if this is the case.

**Comment by Mostelk** [comment]
I tested this ..debug-qsmgt apk on S21 Ultra, the detailed results actually show backend as TFLite for all benchmarks, and results show that Samsung backend is not picked up

**Comment by d-uzlov** [comment]
@Mostelk, could you upload part of the logs with backend matching?
They should contain the reason why the app did not pick the Samsung backend.

**Comment by al-mahi** [comment]
@d-uzlov I tested in my local device. I found in the log that it picked up tflite backend. From the following logs I think it either could not parse the BackendSetting or the backend setting is wrong itself. 
12-28 15:32:07.152 21250 22915 I native  : cpp/flutter/dart_backend_match.cc:43 checking pbdata
12-28 15:32:07.153 21250 22915 E libprotobuf-native: [libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:322] Error parsing text-format mlperf.mobile.BackendSetting: 80:11:     Message type "mlperf.mobile.BenchmarkSetting" has no field named "setting".

**Comment by d-uzlov** [comment]
@al-mahi, Is there a `Can't parse backend settings before serialization: <multiline protobuf from backend>` error message right after the error from `libprotobuf-native`?
Could you post it here?
You can use the `details` github markdown tag:

<details>

```

<details>
many log lines
</details>

```
</details>

to avoid flooding the page

**Comment by al-mahi** [comment]
@d-uzlov Yes, the error message you mentioned is there. I posted several lines of the logs in the details tag.
<details>
12-28 15:32:07.152 21250 22915 D MLPerf  : [Backend][EdenAI] mlperf_backend_matches_hardware:955: This hardware is supported
12-28 15:32:04.882     0     0 I [2:c.PmicCurrentEG: 3832] adc_check_async: check async clear(0x41)
12-28 15:32:07.152 21250 22915 I native  : cpp/flutter/dart_backend_match.cc:43 checking pbdata
12-28 15:32:07.153 21250 22915 E libprotobuf-native: [libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:322] Error parsing text-format mlperf.mobile.BackendSetting: 80:11: Message type "mlperf.mobile.BenchmarkSetting" has no field named "setting".
12-28 15:32:07.153 21250 22915 E native  : cpp/flutter/dart_backend_match.cc:54 Can't parse backend settings before serialization:
12-28 15:32:07.153 21250 22915 E native  : 
12-28 15:32:07.153 21250 22915 E native  : common_setting {
12-28 15:32:07.153 21250 22915 E native  :   id: "num_threads"
12-28 15:32:07.153 21250 22915 E native  :   name: "Number of threads"
12-28 15:32:07.153 21250 22915 E native  :   value {
12-28 15:32:07.153 21250 22915 E native  :     value: "4"
12-28 15:32:07.153 21250 22915 E native  :     name: "4 threads"
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :     value: "1"
12-28 15:32:07.153 21250 22915 E native  :     name: "Single thread"
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :     value: "2"
12-28 15:32:07.153 21250 22915 E native  :     name: "2 threads"
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :     value: "4"
12-28 15:32:07.153 21250 22915 E native  :     name: "4 threads"
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :     value: "8"
12-28 15:32:07.153 21250 22915 E native  :     name: "8 threads"
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :     value: "16"
12-28 15:32:07.153 21250 22915 E native  :     name: "16 threads"
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  : }
12-28 15:32:07.153 21250 22915 E native  : 
12-28 15:32:07.153 21250 22915 E native  : common_setting {
12-28 15:32:07.153 21250 22915 E native  :   id: "configuration"
12-28 15:32:07.153 21250 22915 E native  :   name: "configuration"
12-28 15:32:07.153 21250 22915 E native  :   value {
12-28 15:32:07.153 21250 22915 E native  :     value: "Samsung's Exynos Neural Network SDK running\non Exynos 990 mobile processor."
12-28 15:32:07.153 21250 22915 E native  :     name: "Samsung Exynos"
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :     value: "Samsung's Exynos Neural Network SDK running\non Exynos 990 mobile processor."
12-28 15:32:07.153 21250 22915 E native  :     name: "Samsung Exynos"
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  : }
12-28 15:32:07.153 21250 22915 E native  : 
12-28 15:32:07.153 21250 22915 E native  : common_setting {
12-28 15:32:07.153 21250 22915 E native  :   id: "share_results"
12-28 15:32:07.153 21250 22915 E native  :   name: "Share results"
12-28 15:32:07.153 21250 22915 E native  :   value {
12-28 15:32:07.153 21250 22915 E native  :     value: "0"
12-28 15:32:07.153 21250 22915 E native  :     name: "false"
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :     value: "1"
12-28 15:32:07.153 21250 22915 E native  :     name: "true"
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :     value: "0"
12-28 15:32:07.153 21250 22915 E native  :     name: "false"
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  : }
12-28 15:32:07.153 21250 22915 E native  : 
12-28 15:32:07.153 21250 22915 E native  : common_setting {
12-28 15:32:07.153 21250 22915 E native  :   id: "cooldown"
12-28 15:32:07.153 21250 22915 E native  :   name: "Cooldown"
12-28 15:32:07.153 21250 22915 E native  :   value {
12-28 15:32:07.153 21250 22915 E native  :     value: "0"
12-28 15:32:07.153 21250 22915 E native  :     name: "false"
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :     value: "1"
12-28 15:32:07.153 21250 22915 E native  :     name: "true"
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :     value: "0"
12-28 15:32:07.153 21250 22915 E native  :     name: "false"
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  : }
12-28 15:32:07.153 21250 22915 E native  : 
12-28 15:32:07.153 21250 22915 E native  : benchmark_setting {
12-28 15:32:07.153 21250 22915 E native  :   benchmark_id: "IS_uint8"
12-28 15:32:07.153 21250 22915 E native  :   setting {
12-28 15:32:07.153 21250 22915 E native  :     id: "accelerator"
12-28 15:32:07.153 21250 22915 E native  :     name: "accelerator"
12-28 15:32:07.153 21250 22915 E native  :     value {
12-28 15:32:07.153 21250 22915 E native  :       value: "samsung npu"
12-28 15:32:07.153 21250 22915 E native  :       name: "npu"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :     acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :       value: "samsung npu"
12-28 15:32:07.153 21250 22915 E native  :       name: "npu"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   setting {
12-28 15:32:07.153 21250 22915 E native  :     id: "configuration"
12-28 15:32:07.153 21250 22915 E native  :     name: "configuration"
12-28 15:32:07.153 21250 22915 E native  :     value {
12-28 15:32:07.153 21250 22915 E native  :         value: "Samsung's Exynos Neural Network SDK running\non Exynos 990 mobile processor."
12-28 15:32:07.153 21250 22915 E native  :         name: "Samsung Exynos"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :     acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :         value: "Samsung's Exynos Neural Network SDK running\non Exynos 990 mobile processor."
12-28 15:32:07.153 21250 22915 E native  :         name: "Samsung Exynos"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   image_width: 512,
12-28 15:32:07.153 21250 22915 E native  :   image_height: 512,
12-28 15:32:07.153 21250 22915 E native  :   num_classes: 31,
12-28 15:32:07.153 21250 22915 E native  :   src: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/Samsung/is.nnc"
12-28 15:32:07.153 21250 22915 E native  : }
12-28 15:32:07.153 21250 22915 E native  : 
12-28 15:32:07.153 21250 22915 E native  : benchmark_setting {
12-28 15:32:07.153 21250 22915 E native  :   benchmark_id: "IC_tpu_uint8"
12-28 15:32:07.153 21250 22915 E native  :   setting {
12-28 15:32:07.153 21250 22915 E native  :     id: "accelerator"
12-28 15:32:07.153 21250 22915 E native  :     name: "accelerator"
12-28 15:32:07.153 21250 22915 E native  :     value {
12-28 15:32:07.153 21250 22915 E native  :       value: "samsung npu"
12-28 15:32:07.153 21250 22915 E native  :       name: "npu"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :     acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :       value: "samsung npu"
12-28 15:32:07.153 21250 22915 E native  :       name: "npu"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   setting {
12-28 15:32:07.153 21250 22915 E native  :     id: "configuration"
12-28 15:32:07.153 21250 22915 E native  :     name: "configuration"
12-28 15:32:07.153 21250 22915 E native  :     value {
12-28 15:32:07.153 21250 22915 E native  :         value: "Samsung's Exynos Neural Network SDK running\non Exynos 990 mobile processor."
12-28 15:32:07.153 21250 22915 E native  :         name: "Samsung Exynos"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :     acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :         value: "Samsung's Exynos Neural Network SDK running\non Exynos 990 mobile processor."
12-28 15:32:07.153 21250 22915 E native  :         name: "Samsung Exynos"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   image_width: 224,
12-28 15:32:07.153 21250 22915 E native  :   image_height: 224,
12-28 15:32:07.153 21250 22915 E native  :   src: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/Samsung/ic.nnc"
12-28 15:32:07.153 21250 22915 E native  : }
12-28 15:32:07.153 21250 22915 E native  : 
12-28 15:32:07.153 21250 22915 E native  : 
12-28 15:32:07.153 21250 22915 E native  : benchmark_setting {
12-28 15:32:07.153 21250 22915 E native  :   benchmark_id: "OD_uint8"
12-28 15:32:07.153 21250 22915 E native  :   setting {
12-28 15:32:07.153 21250 22915 E native  :     id: "accelerator"
12-28 15:32:07.153 21250 22915 E native  :     name: "accelerator"
12-28 15:32:07.153 21250 22915 E native  :     value {
12-28 15:32:07.153 21250 22915 E native  :       value: "samsung npu"
12-28 15:32:07.153 21250 22915 E native  :       name: "npu"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :     acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :       value: "samsung npu"
12-28 15:32:07.153 21250 22915 E native  :       name: "npu"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   setting {
12-28 15:32:07.153 21250 22915 E native  :     id: "configuration"
12-28 15:32:07.153 21250 22915 E native  :     name: "configuration"
12-28 15:32:07.153 21250 22915 E native  :     value {
12-28 15:32:07.153 21250 22915 E native  :         value: "Samsung's Exynos Neural Network SDK running\non Exynos 990 mobile processor."
12-28 15:32:07.153 21250 22915 E native  :         name: "Samsung Exynos"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :     acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :         value: "Samsung's Exynos Neural Network SDK running\non Exynos 990 mobile processor."
12-28 15:32:07.153 21250 22915 E native  :         name: "Samsung Exynos"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   image_width: 320,
12-28 15:32:07.153 21250 22915 E native  :   image_height: 320,
12-28 15:32:07.153 21250 22915 E native  :   num_classes: 91,
12-28 15:32:07.153 21250 22915 E native  :   src: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/Samsung/od.nnc"
12-28 15:32:07.153 21250 22915 E native  : }
12-28 15:32:07.153 21250 22915 E native  : 
12-28 15:32:07.153 21250 22915 E native  : benchmark_setting {
12-28 15:32:07.153 21250 22915 E native  :   benchmark_id: "LU_gpu_float32"
12-28 15:32:07.153 21250 22915 E native  :   setting {
12-28 15:32:07.153 21250 22915 E native  :     id: "accelerator"
12-28 15:32:07.153 21250 22915 E native  :     name: "accelerator"
12-28 15:32:07.153 21250 22915 E native  :     value {
12-28 15:32:07.153 21250 22915 E native  :       value: "samsung npu"
12-28 15:32:07.153 21250 22915 E native  :       name: "npu"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :     acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :       value: "samsung npu"
12-28 15:32:07.153 21250 22915 E native  :       name: "npu"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   setting {
12-28 15:32:07.153 21250 22915 E native  :     id: "configuration"
12-28 15:32:07.153 21250 22915 E native  :     name: "configuration"
12-28 15:32:07.153 21250 22915 E native  :     value {
12-28 15:32:07.153 21250 22915 E native  :         value: "Samsung's Exynos Neural Network SDK running\non Exynos 990 mobile processor."
12-28 15:32:07.153 21250 22915 E native  :         name: "Samsung Exynos"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :     acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :         value: "Samsung's Exynos Neural Network SDK running\non Exynos 990 mobile processor."
12-28 15:32:07.153 21250 22915 E native  :         name: "Samsung Exynos"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   src: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/Samsung/lu.nnc"
12-28 15:32:07.153 21250 22915 E native  : }
12-28 15:32:07.153 21250 22915 E native  : 
12-28 15:32:07.153 21250 22915 E native  : 
12-28 15:32:07.153 21250 22915 E native  : benchmark_setting {
12-28 15:32:07.153 21250 22915 E native  :   benchmark_id: "IC_tpu_uint8_offline"
12-28 15:32:07.153 21250 22915 E native  :   setting {
12-28 15:32:07.153 21250 22915 E native  :     id: "accelerator"
12-28 15:32:07.153 21250 22915 E native  :     name: "accelerator"
12-28 15:32:07.153 21250 22915 E native  :     value {
12-28 15:32:07.153 21250 22915 E native  :       value: "samsung npu"
12-28 15:32:07.153 21250 22915 E native  :       name: "npu"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :     acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :       value: "samsung npu"
12-28 15:32:07.153 21250 22915 E native  :       name: "npu"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   setting {
12-28 15:32:07.153 21250 22915 E native  :     id: "configuration"
12-28 15:32:07.153 21250 22915 E native  :     name: "configuration"
12-28 15:32:07.153 21250 22915 E native  :     value {
12-28 15:32:07.153 21250 22915 E native  :         value: "Samsung's Exynos Neural Network SDK running\non Exynos 990 mobile processor."
12-28 15:32:07.153 21250 22915 E native  :         name: "Samsung Exynos"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :     acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :         value: "Samsung's Exynos Neural Network SDK running\non Exynos 990 mobile processor."
12-28 15:32:07.153 21250 22915 E native  :         name: "Samsung Exynos"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   setting {
12-28 15:32:07.153 21250 22915 E native  :     id: "offline"
12-28 15:32:07.153 21250 22915 E native  :     name: "offline"
12-28 15:32:07.153 21250 22915 E native  :     value {
12-28 15:32:07.153 21250 22915 E native  :       value: "1"
12-28 15:32:07.153 21250 22915 E native  :       name: "true"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :     acceptable_value {
12-28 15:32:07.153 21250 22915 E native  :       value: "1"
12-28 15:32:07.153 21250 22915 E native  :       name: "true"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  : 
12-28 15:32:07.153 21250 22915 E native  :   setting {
12-28 15:32:07.153 21250 22915 E native  :     id: "batch"
12-28 15:32:07.153 21250 22915 E native  :     name: "Batch"
12-28 15:32:07.153 21250 22915 E native  :     value {
12-28 15:32:07.153 21250 22915 E native  :       value: "2048"
12-28 15:32:07.153 21250 22915 E native  :       name: "Batch Size"
12-28 15:32:07.153 21250 22915 E native  :     }
12-28 15:32:07.153 21250 22915 E native  :   }
12-28 15:32:07.153 21250 22915 E native  :   image_width: 224,
12-28 15:32:07.153 21250 22915 E native  :   image_height: 224,  
12-28 15:32:07.153 21250 22915 E native  :   src: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/Samsung/ic_offline.nncgo"
12-28 15:32:07.153 21250 22915 E native  : }
12-28 15:32:07.154 21250 22915 I flutter : skipping backend libsamsungbackend.so
12-28 15:32:07.154 21250 22915 I flutter : checking backend libtflitebackend.so...
12-28 15:32:07.157 21250 22915 I native  : cpp/flutter/dart_backend_match.cc:14 checking backend 'libtflitebackend.so' ...
12-28 15:32:07.157 21250 22915 I native  : cpp/backends/external.cc:135 Using default allocator
12-28 15:32:07.158 21250 22915 I native  : cpp/backend_tflite/tflite_c.cc:163 TFLite backend matches hardware
12-28 15:32:07.158 21250 22915 I native  : cpp/flutter/dart_backend_match.cc:43 checking pbdata
12-28 15:32:07.158 21250 22915 I native  : cpp/flutter/dart_backend_match.cc:70 backend matches
12-28 15:32:07.163 21250 22915 I flutter : using backend libtflitebackend.so

**Comment by d-uzlov** [comment]
@al-mahi 
Samsung backend appear to be using the old protobuf scheme for settings.
The scheme was changed ~6 months ago, in the [currently deleted] `mobile_app` repo, and the `.so` file I used was built ~8 months ago.
I either used outdated version of the backend or the backend has yet to be updated to use the new protobuf scheme.
It worth noting that [samsung_settings.h](https://github.com/mlcommons/mobile_app_open/blob/89c398aa1e7b8267b4cf0129284b71ed5b967474/mobile_back_samsung/cpp/eden_mlperf_c_backend/jni/eden_sdk/include/samsung_settings.h) in this repo does use the updated scheme. Was it updated without rebuilding the `.so` file?

I got the `libsamsungbackend.so` file from the `samsung_backend/lib` folder in the master branch of the mobile_back_samsung repo. Is this the correct place?

**Comment by al-mahi** [comment]
@d-uzlov @relja128 Is there any Docker build environment for flutter app? If so please share the link.

**Comment by al-mahi** [comment]
> @al-mahi Samsung backend appears to be using the old protobuf scheme for settings. The [scheme](https://github.com/mlcommons/mobile_app_open/blob/89c398aa1e7b8267b4cf0129284b71ed5b967474/android/cpp/proto/backend_setting.proto) was changed ~6 months ago, in the [currently deleted] `mobile_app` repo, and the `.so` file I used was built ~8 months ago. I either used outdated version of the backend, or the backend has yet to be updated to use the new protobuf scheme. It worth noting that [samsung_settings.h](https://github.com/mlcommons/mobile_app_open/blob/89c398aa1e7b8267b4cf0129284b71ed5b967474/mobile_back_samsung/cpp/eden_mlperf_c_backend/jni/eden_sdk/include/samsung_settings.h) in this repo does use the updated scheme. Was it updated without rebuilding the `.so` file?

I am not sure about that. @Mostelk I think can tell better

> I got the `libsamsungbackend.so` file from the `samsung_backend/lib` folder in the master branch of the mobile_back_samsung repo. Is this the correct place?
Yes

**Comment by d-uzlov** [comment]
> Is there any Docker build environment for flutter app? If so please share the link.

Yes, you can build the Flutter app using docker.
Instructions for docker builds can be found in the Flutter app documentation: https://github.com/mlcommons/mobile_app_open/blob/master/flutter/documentation/build-and-run.md#android

**Comment by d-uzlov** [comment]
@al-mahi, could you test if this build works correctly?
https://drive.google.com/file/d/1QqmWq1gkfLJZa-EpDAOI1epOLim7t0U-/view?usp=sharing

**Comment by al-mahi** [comment]
> @al-mahi Yes, you can build the Flutter app using docker. Instructions for docker builds can be found in the Flutter app documentation: https://github.com/mlcommons/mobile_app_open/blob/master/flutter/documentation/build-and-run.md#android

@d-uzlov when I try to build it 
Flutter app fails with the following error. Please let Danil know about this error and possible fix. 

cd flutter &&  flutter pub get
Running "flutter pub get" in flutter...                             3.4s
rm -rf flutter/lib/protos
mkdir -p flutter/lib/protos
protoc --proto_path android/cpp/proto \
        --dart_out flutter/lib/protos \
        android/cpp/proto/*.proto
protoc-gen-dart: program not found or is not executable
--dart_out: protoc-gen-dart: Plugin failed with status code 1.
flutter/flutter.mk:44: recipe for target 'flutter/protobuf' failed
make: *** [flutter/protobuf] Error 1

I added the following in my path environment.
export FLUTTER_HOME=$HOME/Flutter/flutter
export PATH=$FLUTTER_HOME/bin:$PATH 
export PATH=$FLUTTER_HOME/bin/cache/dart-sdk/:$PATH 
export PATH=$FLUTTER_HOME/bin/cache/dart-sdk/bin:$PATH  # to point which dart to use
export PATH=$HOME/.pub-cache/bin/:$PATH

The dart and flutter I am using is the following.
mobile_app_open$ which dart
~/Flutter/flutter/bin/cache/dart-sdk/bin/dart
mobile_app_open$ which flutter 
~/Flutter/flutter/bin/flutter

**Comment by al-mahi** [comment]
> @al-mahi, could you test if this build works correctly? https://drive.google.com/file/d/1QqmWq1gkfLJZa-EpDAOI1epOLim7t0U-/view?usp=sharing

@d-uzlov I tested the app you shared. It is not picking samsungbackend and using tflite backend instead.
Can you please share the link to the source code of this app? i.e. any particular branch.
<details>
01-12 13:09:55.640 29230 29548 I native  : cpp/flutter/dart_backend_match.cc:14 checking backend 'libsamsungbackend.so' ...
01-12 13:09:55.641 29230 29548 E native  : cpp/backends/external.cc:85 Unable to load: libsamsungbackend.so: dlopen failed: library "libc++_shared.so" not found: needed by /data/app/~~n_rVl5-1aKKIh0abVSmApw==/org.mlcommons.android.mlperfbench-VRxMnUle0u6yQjebEdU13A==/lib/arm64/libsamsungbackend.so in namespace classloader-namespace
01-12 13:09:55.641 29230 29548 E native  : cpp/flutter/dart_backend_match.cc:17 backend can't be loaded
01-12 13:09:55.641 29230 29548 I native  : cpp/flutter/dart_backend_match.cc:14 checking backend 'libtflitebackend.so' ...
01-12 13:09:55.642 29230 29548 I native  : cpp/backends/external.cc:135 Using default allocator
01-12 13:09:55.642 29230 29548 I native  : cpp/backend_tflite/tflite_c.cc:163 TFLite backend matches hardware
01-12 13:09:55.642 29230 29548 I native  : cpp/flutter/dart_backend_match.cc:43 checking pbdata
01-12 13:09:55.642 29230 29548 I native  : cpp/flutter/dart_backend_match.cc:70 backend matches

**Comment by d-uzlov** [comment]
>protoc-gen-dart: program not found or is not executable

Have you run `dart pub global activate protoc_plugin`?

>Can you please share the link to the source code of this app? i.e. any particular branch.

I used branch [206/move-samsung-check](https://github.com/mlcommons/mobile_app_open/tree/206/move-samsung-check) and the last available Samsung backend binary from its repo, from the branch that Mostelk told me about.

**Comment by d-uzlov** [comment]
Here is a build with fixed dependency, which prevented previous build from working:
https://drive.google.com/file/d/1nMm6ItwlviUM_HBQRmq5rUAfQcDbyS-7/view?usp=sharing
I also pushed this fix to the previously mentioned branch.

**Comment by freedomtan** [comment]
this was for the old(er) backend. Let's close this.
