### ISSUE TITLE
Flutter UI should show the backend used in the advanced view just like the old app

### ISSUE THREAD

**Issue by relja128** [mlcommons/mobile_app_open#178]

**Comment by anhappdev** [comment]
This is how the UI looks with backend info. Please confirm if that is ok.

![IMG_12CCE59821AA-1](https://user-images.githubusercontent.com/85728587/147694364-852aff54-ff5e-44ea-95fa-abf6be062096.jpeg)
![IMG_3D8714A4E4E3-1](https://user-images.githubusercontent.com/85728587/147694369-82f9292c-644f-4920-b473-f88c3f1a56ff.jpeg)

**Comment by relja128** [comment]
The UI looks good.
