### ISSUE TITLE
Require new approval when new commit are pushed to approved pull request

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#182]
Currently, this repo is set up so that if a PR is approved, new commits can be pushed to that PR and that PR can be merged without requiring a new approval.

I think the repo should be set up that when new commits are pushed to that PR, it needs approval again before merging is allowed.
This can be achieved by enable `Dismiss stale pull request approvals when new commits are pushed.` (see [step number 6 in this guide](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule))

**Comment by d-uzlov** [comment]
Done.
I enabled the `Dismiss stale <...>` checkbox.

**Comment by anhappdev** [comment]
@d-uzlov Can you review and approve this PR: https://github.com/mlcommons/mobile_app_open/pull/198
I will then push a new commit with slightly changed color to test the behavior.

**Comment by anhappdev** [comment]
It worked as intended.
