### ISSUE TITLE
Handling of updated default task file

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#184]
The app uses a default task file (`tasks.pbtxt`) loaded from a URL. There are 3 cases:
1. The URL is changed, but the app is not changed.
2. The URL is changed, but the app is changed.
3. The URL is not changed, but the content of the config file is changed.

How should we handle those cases?
One idea is to use a permanent URL for the default task file. The URL will redirect to an actual task file. The actual task file should have a new name (`tasks_v1.pbtxt`, `tasks_v2.pbtxt`, ...) if the content is changed. The app will always use the latest task file.

**Comment by d-uzlov** [comment]
There is another case: app is updated and the new version uses a new URL.
Currently the Flutter app would pick up the new URL if filename is changed.
After we merge https://github.com/mlcommons/mobile_app_open/pull/170 the behavior will change: the app will continue using the old config unless someone manually clears the cache.

**Comment by anhappdev** [comment]
I added the case you mentioned.
We rarely change the default task file and in the Settings screen we can also see which task file is used, so it is quite transparent.
I would just merge #170 first, then handle this issue to avoid merge conflict if we keep the PR too long open.

**Comment by relja128** [comment]
Our config files should be immutable once published. If the config needs to change, then the URL needs to change. Therefore, we should never have to handle situation #3:
"The URL is not changed, but the content of the config file is changed."
