### ISSUE TITLE
Backend hardware match is not handled as expected in flutter app

### ISSUE THREAD

**Issue by mohitmundhragithub** [mlcommons/mobile_app_open#205]
Found that in the latest flutter based app, if qti backend detects a snapdragon device, but the device is not supported, then also, the app goes ahead and loads the next backend and finally runs the tflite models.
Expected: The app should show a message saying that the device is unsupported instead of loading the next backend. This is what happens in the legacy android app, but not in the flutter based android app.

**Comment by freedomtan** [comment]
@anhappdev and @d-uzlov please help on this.
