### ISSUE TITLE
Move check for Samsung backend to C++ code

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#206]
Android app has an exception for Samsung backend. Samsung backend should not be unloaded between benchmarks:
https://github.com/mlcommons/mobile_app_open/blob/8711a2f52f2ae9fa4926589b01b07251c2a6c64f/android/java/org/mlperf/inference/RunMLPerfWorker.java#L179
Flutter app doesn't have such check.
It would make sense to move this check into C++ code instead of adding a separate check into Flutter app.

**Comment by AhmedTElthakeb** [comment]
Samsung will only support new backend on the flutter app, and this check will not be needed in the flutter app.

**Comment by freedomtan** [comment]
new backend doesn't have this problem. close this

**Comment by AhmedTElthakeb** [comment]
This issue has been resolved for all generations (old and new) in the latest android app merge, no workarounds are needed any more.
https://github.com/mlcommons/mobile_app_open/tree/android-v2
Commit# https://github.com/mlcommons/mobile_app_open/commit/a47423a778debeb7d4dffcc4a9c69b2697171b93
