### ISSUE TITLE
Facing issues in building windows flutter app. 

### ISSUE THREAD

**Issue by mohitmundhragithub** [mlcommons/mobile_app_open#212]
@d-uzlov I am getting below error when trying to build flutter based windows app. 
Can you please have a look once if you have come across it earlier or any suggestions to try out?

fatal error C1083: Cannot open compiler generated file: '': Invalid argument

[error.txt](https://github.com/mlcommons/mobile_app_open/files/7855423/error.txt)

**Comment by d-uzlov** [comment]
I can't be 100% sure, but I think I encountered this same issue when I was building the app with too long username.
The path to the file in your log is 188 symbols long, but I believe that Visual Studio compiler composes file path and a relative include path in the file, and the resulting path exceeds ~260 path length limit. Or something like this.

I got this solved by just renaming the user in the docker container I was using.
It could probably be solved by just manually pointing `--output_user_root` bazel startup arg to a shorter path.

**Comment by relja128** [comment]
In case this helps, enabling long paths in Win10:
https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd

**Comment by mohitmundhragithub** [comment]
Thanks Danil and Relja. I was able to resolve the issue.

Facing a new issue now when trying to build qtibackend.
The SNPE for windows library produces dynamic libraries. But when we enable dynamic libraries flag for libqtibackend, it throws some linking error for tflite.
On trying out the same change in mobile_back_tflite, i.e., to dynamically link tflite, get the same error as above.
Any way that you may be aware of to dynamically link tflite?

**Comment by d-uzlov** [comment]
I never tried to build libraries with dynamic linking using bazel on Windows.

>On trying out the same change in mobile_back_tflite, i.e., to dynamically link tflite, get the same error as above.

@mohitmundhragithub, could you provide more into about changes you've made? I don't see any places where adding `linkshared = 1` in the tflite build file would make sense. Are you talking about some other flag, or are there some bigger changes in build configs?

**Comment by mohitmundhragithub** [comment]
https://github.com/mlcommons/mobile_app_open/blob/master/mobile_back_tflite/cpp/backend_tflite/BUILD#L26

Add a field, "linkstatic=0" in the cc_library bazel construct.
https://docs.bazel.build/versions/main/be/c-cpp.html#cc_library

BTW, I tried by using tflite v2.7 as well... but it didn't help :(

**Comment by d-uzlov** [comment]
When I tried adding `linkstatic=0` to the `cc_library { name = "tflite_c" }` rule I didn't get any errors.
Judging by Bazel documentation this is to be expected:
>The linkstatic attribute has a different meaning if used on a cc_library() rule. For a C++ library, linkstatic=True indicates that only static linking is allowed, so no .so will be produced. linkstatic=False does not prevent static libraries from being created. The attribute is meant to control the creation of dynamic libraries.

I used the following commands to test:
* `bazel build --config windows //mobile_back_tflite/cpp/backend_tflite:libtflitebackend.dll`
* `bazel build --config windows //mobile_back_tflite/cpp/backend_tflite:tflite_c`

However, I did get an error `file 'mobile_back_tflite/cpp/backend_tflite/quantization_util.dll' is generated by these conflicting actions` when I added `linkstatic=0` to `cc_binary( name = "libtflitebackend.dll"`.
Did you mean `cc_binary` rule, or are there some other changes?

**Comment by mohitmundhragithub** [comment]
I was able to resolve the above issue. Earlier, I was missing one one important point, that Qualcomm needs to build the app for windows_arm64 and not windows_x64. The current windows app is built only for x64. When i switched to windows_arm64, then compilation of few of the helper libraries itself fails. I will close this issue, and create a new one for adding support for windows_arm64.
