### ISSUE TITLE
Refresh the iOS version of the app, apparently it expired

### ISSUE THREAD

**Issue by relja128** [mlcommons/mobile_app_open#213]
Looks like we ran into the testflight time limit. Please re-submit the app so it keeps runnig.

**Comment by d-uzlov** [comment]
I've uploaded a new version of the app into Testflight.

**Comment by relja128** [comment]
Didn't update for me, @d-uzlov is looking at whether it's internals or externals.

**Comment by d-uzlov** [comment]
I uploaded a new build.
@relja128, I also tried removing and re-adding you to the app testers. It seems you will have to accept the invite again.

**Comment by relja128** [comment]
Worked for me now, thanks
