### ISSUE TITLE
We need a build of the Flutter app with all backends that the vendors can test

### ISSUE THREAD

**Issue by relja128** [mlcommons/mobile_app_open#223]
Please add it to the releases page

**Comment by anhappdev** [comment]
The build is uploaded here:
https://github.com/mlcommons/mobile_app_open/releases/tag/v3.0.0-flutter-android-alpha-4

**Comment by hbkaye** [comment]
Does this build automatically detects the backend or is there a way to specify using the app UI ?

**Comment by fatihcakirs** [comment]
"v3.0.0-flutter-android-alpha-4" crashes our phone w/ Exynos backend shortly after the first task is completed.

**Comment by hbkaye** [comment]
![Screenshot_2022-02-01-12-21-04-554_org mlcommons android mlperfbench](https://user-images.githubusercontent.com/42088297/151924816-0cf0e629-f6f8-4452-8e57-7d61b6cda575.jpg)

This is pic of configuration page on our Qualcomm's SDM888 device
It selects TFLite and NNAPI, instead we want to run with QTI backend and DSP accelerator.

**Comment by anhappdev** [comment]
@hbkaye 
> Does this build automatically detects the backend or is there a way to specify using the app UI ?

The app detects automatically available backends and use the detected one, else it uses the default TFLite backend.

**Comment by anhappdev** [comment]
@fatihcakirs 
> "v3.0.0-flutter-android-alpha-4" crashes our phone w/ Exynos backend shortly after the first task is completed.

I think it's related to the issue https://github.com/mlcommons/mobile_app_open/issues/30

**Comment by hbkaye** [comment]
> @hbkaye
> 
> > Does this build automatically detects the backend or is there a way to specify using the app UI ?
> 
> The app detects automatically available backends and use the detected one, else it uses the default TFLite backend.

Yeah, was able to make it work.
Also does this app has integrated official vendor's patch used for submitting results ?
Like the one given here - 
https://github.com/mlcommons/mobile_submission_1.1/blob/master/closed/Qualcomm_Innovation_Center/code/qti_submission.patch

**Comment by freedomtan** [comment]
cf. #231

**Comment by freedomtan** [comment]
we already have #231
