### ISSUE TITLE
Commit ID for  MLPerf Mobile V2.0 Submission 

### ISSUE THREAD

**Issue by Mostelk** [mlcommons/mobile_app_open#226]
Please confirm if you are fine with this commit ID to use for V2.0 Submission Branch 
https://github.com/mlcommons/mobile_app_open/commit/7bd303f49c24a0c3b4e281120fb1368f017eacb2

**Comment by anhappdev** [comment]
If I remember correctly, we will still use the native Android app for the v2.0 submission.
The commit `7bd303f` only affects the new Flutter app.

**Comment by freedomtan** [comment]
> > If I remember correctly, we will still use the native Android app for the v2.0 submission. The commit `7bd303f` only affects the new Flutter app.
> 
> Thanks for clarification, we can still use this commit as a reference, to clone the app to freeze branch for MLPerf v2

yes, we can still use this commit as reference. It works for some customers' phone I tested.

BTW, for MediaTek's Neuron delegate, we need an extra entry for the new Mosaic model, https://github.com/mlcommons/mobile_app_open/pull/228

**Comment by sb-huh** [comment]
As anhappdev mentioned. that commit do not have any changes for others.  

Anyway, for samsung backend 2.0 and MLPerf app, it did not happen abnormal performances. Looks good.

**Comment by anhappdev** [comment]
Would it be better if we (pre-)release a v2.0 Android app with all backends, then use that release commit?

**Comment by freedomtan** [comment]
> Would it be better if we (pre-)release a v2.0 Android app with all backends, then use that release commit?

I am not sure if that will be better. Usually, there are modifications / enhancements for new submissions. We have to do post-submission/auditing integration anyway.

**Comment by freedomtan** [comment]
Qualcomm, Samsung, and MediaTek are fine with this one. We can close this and create a new 2.0 branch based one this one.

**Comment by anhappdev** [comment]
Here is the 2.0 submission branch created from the commit `7bd303f`:
https://github.com/mlcommons/mobile_app_open/tree/submission-v2.0
