### ISSUE TITLE
--experimental_no_product_name_out_symlink

### ISSUE THREAD

**Issue by shabanim** [mlcommons/mobile_app_open#233]
The flag was removed in version 5-0 according to https://blog.bazel.build/2022/01/19/bazel-5.0.html ("Removed flag --experimental_no_product_name_out_symlink; it is effectively always true."

As a result it complain if bazel 5.0 is installed on the system because common.mk uses this flag. I think we should use this conditionally depending on bazel version installed on the machine.

**Comment by anhappdev** [comment]
Per https://blog.bazel.build/2022/01/19/bazel-5.0.html
> Bazel 5.0 is a major release and Bazel’s second LTS release. It contains new features and backwards incompatible changes from 4.x, the previous LTS release.

If there isn't a reason to use Bazel 5.0, I would stick to Bazel 4.x for now, since more issues may be occurred when building the app on other platforms with Bazel 5.0.

**Comment by shabanim** [comment]
This is exactly what I did. Perhaps, we need to mention this on document for those who setup it up for the first time. I found if we run choco install bazel --version 4.2 then it install the specific version instead of the latest version

**Comment by anhappdev** [comment]
The tested environment was mentioned in the [instruction for iOS](https://github.com/mlcommons/mobile_app_open/blob/master/flutter/documentation/env-setup-ios.md#tested-anvironment) but not for Windows. Perhaps can you create a PR and add it to the Windows instruction after a successful build?

**Comment by freedomtan** [comment]
Bazel is evolving fast. I usually use whatever bazel version used by TensorFlow. @shabanim  please add doc about required bazel version for the project.

**Comment by freedomtan** [comment]
the PR https://github.com/mlcommons/mobile_app_open/pull/248 is sent
