### ISSUE TITLE
Inconsistency in naming variable for speed measurement

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#237]
Currently, in the app, we have different variable names to mean the same thing:
* `score` measured in `QPS` (Query Per Second)
* `latency` measured in `ms` for single stream benchmark
* `latency` measured in `QPS` for offline benchmark
* `score` is also used to measure accuracy with different units depend on benchmark type.

This caused confusion and conversion between units (`qps = 1000 / latency in ms`) in many places.

We should agree on one name and unit for speed measurement to be consistent.

**Comment by freedomtan** [comment]
@shabanim will help check what is the right name (by loading loadgen related log)

**Comment by shabanim** [comment]
I am copying here mlperf_log_summary.txt generated by loadgen for both SingleStream and offline for easy reverencing. 

- For SingleStream performance mode, it reports mostly 90th percentile latency in ns.
- For Offline performance mode, it reports sample per second at the top
- For Accuracy, unit used depends on the workload.


**SingleStream Log file**
================================================
MLPerf Results Summary
================================================
SUT name : SUT
Scenario : SingleStream
Mode     : PerformanceOnly
90th percentile latency (ns) : 1796200
Result is : VALID
  Min duration satisfied : Yes
  Min queries satisfied : Yes

================================================
Additional Stats
================================================
QPS w/ loadgen overhead         : 603.66
QPS w/o loadgen overhead        : 604.31

Min latency (ns)                : 1419400
Max latency (ns)                : 12871700
Mean latency (ns)               : 1654771
50.00 percentile latency (ns)   : 1642700
90.00 percentile latency (ns)   : 1796200
95.00 percentile latency (ns)   : 1835100
97.00 percentile latency (ns)   : 1880700
99.00 percentile latency (ns)   : 2013600
99.90 percentile latency (ns)   : 2506100

================================================
Test Parameters Used
================================================
samples_per_query : 1
target_qps : 500
target_latency (ns): 0
max_async_queries : 1
min_duration (ms): 60000
max_duration (ms): 0
min_query_count : 1024
max_query_count : 0
qsl_rng_seed : 1624344308455410291
sample_index_rng_seed : 517984244576520566
schedule_rng_seed : 10051496985653635065
accuracy_log_rng_seed : 0
accuracy_log_probability : 0
accuracy_log_sampling_target : 0
print_timestamps : 0
performance_issue_unique : 0
performance_issue_same : 0
performance_issue_same_index : 0
performance_sample_count : 1024

No warnings encountered during test.

No errors encountered during test.


** Offline Log File**
================================================
MLPerf Results Summary
================================================
SUT name : SUT
Scenario : Offline
Mode     : PerformanceOnly
Samples per second: 2146.76
Result is : VALID
  Min duration satisfied : Yes
  Min queries satisfied : Yes

================================================
Additional Stats
================================================
Min latency (ns)                : 62963756500
Max latency (ns)                : 62963756500
Mean latency (ns)               : 62963756500
50.00 percentile latency (ns)   : 62963756500
90.00 percentile latency (ns)   : 62963756500
95.00 percentile latency (ns)   : 62963756500
97.00 percentile latency (ns)   : 62963756500
99.00 percentile latency (ns)   : 62963756500
99.90 percentile latency (ns)   : 62963756500

================================================
Test Parameters Used
================================================
samples_per_query : 135168
target_qps : 2048
target_latency (ns): 0
max_async_queries : 1
min_duration (ms): 60000
max_duration (ms): 0
min_query_count : 1
max_query_count : 0
qsl_rng_seed : 1624344308455410291
sample_index_rng_seed : 517984244576520566
schedule_rng_seed : 10051496985653635065
accuracy_log_rng_seed : 0
accuracy_log_probability : 0
accuracy_log_sampling_target : 0
print_timestamps : 0
performance_issue_unique : 0
performance_issue_same : 0
performance_issue_same_index : 0
performance_sample_count : 1024

1 warning encountered. See detailed log.

No errors encountered during test.

**Comment by freedomtan** [comment]
So I guess we should avoid "score". I am fine with either latency or queries per second (QPS).

**Comment by anhappdev** [comment]
I would name it `speed` (vs. `accuracy`) and the unit of measurement is `QPS`.
But I am fine with other names too if it's used consistently in the code base.

**Comment by freedomtan** [comment]
for qps, throughput (instead of score). and we can keep latency (either nanosecond or millisecond)

just get rid of "score".

**Comment by d-uzlov** [comment]
Do we also want to change `score` to `throughput` in the `result.json` file?

**Comment by d-uzlov** [comment]
I created a separate issue to discuss changes in `result.json`: https://github.com/mlcommons/mobile_app_open/issues/247
