### ISSUE TITLE
Random number seeds for v2.0

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#243]
We need v2.0 seeds for submission-v2.0 branch. See https://github.com/mlcommons/inference/pull/1065 for seeds

**Comment by willc2010** [comment]
thanks for filing this. do you mind create a PR for this?

**Comment by freedomtan** [comment]
> thanks for filing this. do you mind create a PR for this?

Yes, the PR is #244

**Comment by freedomtan** [comment]
#244 Merged and cherry-picked to submission-v2.0 branch, https://github.com/mlcommons/mobile_app_open/commit/d67a6b64f2bd212a2f2076ea80a03440cfa904e6
