### ISSUE TITLE
Add small glossary

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#246]
As @shabanim suggested in the meeting, I think having a small glossary is helpful for new contributors to understand common used words in the context of this repo. I will add a small glossary for some common used words.

@shabanim Feel free to add any words you think we should explain.

Some words in my minds:
* accelerator
* throughput
* latency
* accuracy
* backend
* vendor
* loadgen
* task
* performance mode
* accuracy mode
* single stream scenario
* offline scenario
* benchmark

**Comment by shabanim** [comment]
Great! That would be very helpful. If we take the blockdiagram at https://github.com/mlcommons/inference/tree/master/loadgen#integration-example-and-flow, we need to define backend as well. example of backend is tflight, OpenVINO and .. it is really inference engine available on the device. It is used for inferencing.

single stream and offline are scenario. Please remove the word benchmark that comes after them. 

My understanding of benchmark is the block in the diagram that glue all components together and this block is vendor specific. You may also call the whole code base benchmark. However, I like to call vendor specific code + additional code/blocks other than those listed in the diagram as benchmark. We can brainstorm on what we mean by benchmark in the next session. Thanks

**Comment by anhappdev** [comment]
> single stream and offline are scenario. Please remove the word benchmark that comes after them.

Updated

**Comment by anhappdev** [comment]
You are welcome to add new terms and it's description in this doc:
https://docs.google.com/document/d/1F2gdh15bw7IpnG1JmX457zAm8QlC3LLf3oVMF_LoPzI/edit?usp=sharing

I will add it to this repo after we have the table filled.
