### ISSUE TITLE
Formal specification for result.json file

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#247]
Currently I don't see any info about the structure of this file.
As far as I'm aware it is imported in some external tools, so it must have a certain format which is recognized by these tools.

We need to write a proper specification for this file, so we can stick to it when making changes in sources, to avoid breaking any external tools.

**Comment by freedomtan** [comment]
There should be some descriptions in the submission rule doc. Let's if what we can do from that doc.
@freedomtan to add submission rules doc link later

**Comment by d-uzlov** [comment]
In the old Android app there is a function that creates `result.json`:
https://github.com/mlcommons/mobile_app_open/blob/084729b7f29043dc833fd7a90c49940fc5012e3e/android/java/org/mlperf/inference/MLPerfTasks.java#L149

## Android app

It creates the following structure:
On top level there is an array of benchmark entries. Each entry is a map with the following fields:
```json
{
"benchmark_id": string,
"configuration": {
  "runtime": string
},
"score": string,
"accuracy": string,
"min_duration": string,
"duration": string,
"min_samples": string,
"num_samples": string,
"mode": string,
"datetime": string
}
```
Few notes about these fields:
* `runtime` is always empty. In the app sources I see that it was supposed to always be `External` instead of empty string, but in the real results file I got after running the app it's just empty.
Both empty and "External" values doesn't make much sense to me, if they never change.
* `score` always contains benchmark score
* `accuracy` for contains accuracy string that we get from native code for submission mode results, and `N\/A` for performance mode results.
I don't understand why there is `\/` instead of just `/`. It looks as if `/` was a special JSON character which must be escaped, but it is not.
* `score`, `min_duration`, `duration`, `min_samples`, `num_samples` are numeric values but we write them as strings for some unknown reason.
* `datetime` has the following form: `2022-02-15T15:04:52.291`. It is missing time zone.
* `mode` can have one of the following values:
  * `performance_lite_mode`
  * `accuracy_mode`
  * It seems like at some point other run modes were used, but now the app only runs these 2 modes.
* `min_duration` and `min_samples` values are from benchmark config
* `duration` and `num_samples` are measured values

## Flutter app

Flutter app manages result file creation in this class:
https://github.com/mlcommons/mobile_app_open/blob/084729b7f29043dc833fd7a90c49940fc5012e3e/flutter/lib/resources/result_manager.dart#L44
Flutter app mimics Android app result file, it has the same fields, with the same type of values.
It also has additional fields that Android app doesn't have:
```json
{
... all the same fields ...,
"shards_num": numeric,
"batch_size": numeric,
"backend_description": string
}
```
* `batch_size` is only relevant for offline benchmarks. The value is from backend config
* `shards_num` is only relevant for offline benchmarks when tflite backend is used.
* `batch_size` and `shards_num` are configurable via the app UI on iOS
* `backend_description` is currently the name of the backend, which we also show in the UI. When https://github.com/mlcommons/mobile_app_open/issues/203 is done, it will also contain accelerator name.

**Comment by d-uzlov** [comment]
@jwookiehong
I don't know if it will be useful to you before the meeting next week, but I posted description of the current structure of `result.json` file in my comment above.

**Comment by freedomtan** [comment]
@d-uzlov should be free to propose changes.
@freedomtan and @jwookiehong create a spec for this `results.json`

**Comment by d-uzlov** [comment]
I uploaded a proposal for new results structure:
https://github.com/mlcommons/mobile_app_open/blob/a82c8de7f4069d1b88e9749e25ee3c6abae59db7/flutter/documentation/result-spec.md
