### ISSUE TITLE
Add result history to the Flutter app

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#253]
Currently the app only shows last result. When you rerun any set of benchmarks, results of the previous run are erased.
We need to add a new UI page that will show list of previous results and allow to inspect them.

This feature must be offline.
We can technically upload result into Firebase, and then fetch them to show in history but sometimes this can be undesirable, so we must keep results locally.

Initial discussion was here: https://github.com/mlcommons/mobile_app_open/issues/235

Steps:
* [x] Add history saving
* [ ] Add UI pages for result list and for individual results

**Comment by freedomtan** [comment]
@anhappdev please help on this one. do some initial investigation

**Comment by anhappdev** [comment]
I would store the `result.json` file of each benchmark run on disk with a timestamp. In the history screen, the app shows a list of those result files, and on tap of one result file, the app show the content of the result file.

**Comment by d-uzlov** [comment]
When working on https://github.com/mlcommons/mobile_app_open/issues/251 I have modified the way we handle `result.json` a bit. I fixed serialization and added few new fields that are required for uploading.
I'll extract it into a separate PR today so you can use it for result history.

**Comment by anhappdev** [comment]
@d-uzlov Would you take over this issue? I think with the tasks you are current doing (implementation of new result spec), this issue would fit better in your workflow and design.

**Comment by d-uzlov** [comment]
@anhappdev sure.

**Comment by anhappdev** [comment]
@d-uzlov Great. Thanks.

**Comment by d-uzlov** [comment]
I have created 2 separate issues for backend changes and for UI changes.
