### ISSUE TITLE
Should we use tflite in Google Play services?

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#258]
Google Play services started bundling TfLite in recent Feb 17, 2021 release (cf. https://developers.google.com/android/guides/releases and https://www.tensorflow.org/lite/android/play_services). Should we use the binary in Google Play. 

pros: smaller package size, less build time
cons: may need to rewrite part of tflite backend

**Comment by d-uzlov** [comment]
I don't think it will significantly affect build time, except for the first build. Bazel cache is quite effective when library files don't change.
Package size will also not be affected too much. The tflite backend itself is relatively small. The majority of the package size comes from dependencies of the qti and samsung backends, and from Flutter UI.
