### ISSUE TITLE
Update loadgen version

### ISSUE THREAD

**Issue by bellycat77** [mlcommons/mobile_app_open#26]
Original https://github.com/mlcommons/mobile_app/issues/333

**Comment by bellycat77** [comment]
@relja128 @mcharleb @Mostelk @freedomtan 
Which version/commit of the Loadgen library should we use?

**Comment by freedomtan** [comment]
for 0.7, as far as I can remember, we used 0.7 branch of inference. 
thus, for 1.1, we should use https://github.com/mlcommons/inference/tree/r1.1

**Comment by bellycat77** [comment]
PR waits for approvement

**Comment by bellycat77** [comment]
@relja
APKs:
with old loadgen: https://drive.google.com/file/d/1zoe9BUPLAer5V87Oj14V9n1DmqqqQb4J/view?usp=sharing
with new loadgen: https://drive.google.com/file/d/1qnt25Y90Sd5qZl6yOEKGBBBquu2YBDoq/view?usp=sharing

**Comment by Relja** [comment]
I think you got the wrong Relja. I can't escape from you @relja128  ;)

**Comment by relja128** [comment]
Ha, that's amazing! We keep running into each other all over the internet.
We should get drinks next time you're in Belgrade. :)
