### ISSUE TITLE
Add support for several model files per benchmark

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#270]
Currently a backend can only specify one model file for a benchmark.
Future backends may use models that are defined in several files. Specifically I'm aware that there are models that need 2 files.
I see 2 possible solutions here:
1. Add a new setting to the protobuf config. We can make it optional so we don't have to update our current backends. We will only support fixed number of files.
2. Use `CustomSetting` field in the benchmark settings. We can add special handling of some CustomSetting fields to the app frontend to download files using provided URLs.

**Comment by freedomtan** [comment]
Per our discussion, a model archive file (say, foo.zip) should work. Leave op after we test it.

**Comment by carlosd-29** [comment]
Downloading a zip file and opening within interface function works.
