### ISSUE TITLE
Merge changes from v2.0 submission

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#278]
we have at least the following issues
1. the latency setting,
2. the TensorFlow 2.80, 
3. uploading new (converted, e.g., QIT's dlc files and original (mosaic)) 

Let's start the merging after the publication this Wed (Apr 6th)

**Comment by freedomtan** [comment]
@anhappdev   please merge  https://github.com/mlcommons/mobile_app_open/tree/submission-v2.0 to both the Android branch and main/master branch.

**Comment by freedomtan** [comment]
@fatihcakirs has submitted some nnc files. @anhappdev to help put all the .nnc and .dlc files to the mobile_models repo

**Comment by anhappdev** [comment]
Trying upload model files for Qualcomm I got an error with size limit:
```
remote: error: File v2_0/SNPE/mobilebert_quantized_htp.dlc is 104.35 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
```

Should we use Git LFS for model files?

**Comment by freedomtan** [comment]
yeah, large file is an issue. As far as I can remember, github lfs has monthly bandwidth limit (1 GiB per month). https://docs.github.com/en/enterprise-cloud@latest/billing/managing-billing-for-git-large-file-storage/about-billing-for-git-large-file-storage

That is, after downloading > 10 times, we'll run out of 1 GB / month quota :-(

**Comment by anhappdev** [comment]
Is there other alternative storage provider we can use?

>Technically, we can work around this by compressing or splitting large files. We need way to decompress the compressed file or merge splitted files.

Yes, it's possible but I am not sure if it's worth the effort to implement it vs. just using a storage service.

**Comment by freedomtan** [comment]
@willc2010 and @jwookiehong what's your opinion?

**Comment by Mostelk** [comment]
If possible to gauge how much work is needed for this issue, as it will be needed for future submission as well https://github.com/mlcommons/mobile_app_open/issues/291

**Comment by freedomtan** [comment]
Possible solutions

1. buy storage services (github or other version control services), 
2. splitting (and/or or compressing)
3. ?

**Comment by freedomtan** [comment]
@jwookiehong will check with @TheKanter to see if we can pay for services

**Comment by jwookiehong** [comment]
I talked to David, and he is receptive to the idea. Now we need to figure
out which services we need, and how much it will cost. Also, is it possible
to somehow use GCP?

**Comment by anhappdev** [comment]
We can use any storage service (like Git Large File Storage, Google Cloud Storage or AWS S3)
* Git LFS has simple pricing ([Link](https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/about-billing-for-git-large-file-storage))
> Additional storage and bandwidth is offered in a single data pack. One data pack costs $5 per month, and provides a monthly quota of 50 GB for bandwidth and 50 GB for storage. You can purchase as many data packs as you need. For example, if you need 150 GB of storage, you'd buy three data packs.
* Google Cloud Storage has a more complex pricing ([Link](https://cloud.google.com/storage/pricing))
> Cloud Storage pricing is based on the following components:
>Data storage: the amount of data stored in your buckets. Storage rates vary depending on the storage class of your data and location of your buckets.
Data processing: the processing done by Cloud Storage, which includes operations charges, any applicable retrieval fees, and inter-region replication.
Network usage: the amount of data read from or moved between your buckets.

Any of them is fine.

**Comment by jwookiehong** [comment]
@TheKanter @relja128, Git LFS looks the most straighforward, and should be sufficient for our needs. An extra $5 a month is cool, right?

**Comment by TheKanter** [comment]
Sounds fine. Hopefully the egress is sufficient. Go ahead and do it!

**Comment by anhappdev** [comment]
I created a PR (https://github.com/mlcommons/mobile_models/pull/38) for uploading `*.dlc` files using Git LFS.
After merging the PR and ensuring that Git LFS works as expected I will migrate all other large model files (`*.nnc`,`*.tflite`) to Git LFS.

**Comment by anhappdev** [comment]
Submission branch is merged. We have other issues for updating to TF2.8 (https://github.com/mlcommons/mobile_app_open/issues/145) and making latency configurable (https://github.com/mlcommons/mobile_app_open/issues/291).
