### ISSUE TITLE
Few warning reported from enterprise github for firebase.

### ISSUE THREAD

**Issue by mohitmundhragithub** [mlcommons/mobile_app_open#279]
Sharing these errors just in case these are some important security vulnerability.

![image](https://user-images.githubusercontent.com/1549325/161685848-0012fb6a-71de-49f3-bfb7-736bbc2d40ab.png)

https://docs.github.com/en/enterprise-server@3.3/code-security/dependabot/dependabot-alerts/about-dependabot-alerts

![image](https://user-images.githubusercontent.com/1549325/161685981-fe5eb742-e058-4650-8220-d98a5fcefac5.png)

![image](https://user-images.githubusercontent.com/1549325/161686088-447d35a4-cb02-45ab-b08b-b856aeb8f1a2.png)

![image](https://user-images.githubusercontent.com/1549325/161686134-9a52a9bb-56b0-44a8-bdf1-28ab66cd50e0.png)

![image](https://user-images.githubusercontent.com/1549325/161686170-7443150c-7c67-4675-9b8c-7c7801cb329b.png)

**Comment by d-uzlov** [comment]
According to Dependabot documentation, it is enabled by default in all public repositories but this can be changed by an Organization owner:
https://docs.github.com/en/code-security/dependabot/dependabot-alerts/configuring-notifications-for-dependabot-alerts
>Dependabot is enabled by default on all public repositories. For Dependabot alerts, by default, you will receive Dependabot alerts by email, grouped by the specific vulnerability.
>
>If you're an organization owner, you can enable or disable Dependabot alerts for all repositories in your organization with one click. You can also set whether the detection of vulnerable dependencies will be enabled or disabled for newly-created repositories.

In this repository Dependabot is disabled. It was probably disabled by MLCommons administrator for all mlcommons repositories.
We can enable it for this repo to get notifications about vulnerable dependencies like one in this issue description.

**Comment by d-uzlov** [comment]
Maybe we should also plan to update our dependencies regularly. Maybe each month.

**Comment by freedomtan** [comment]
Let's try to enable to the enterprise feature that enable CVEs checking. @d-uzlov
