### ISSUE TITLE
Can backend name and vendor depend on benchmark?

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#284]
Functions `mlperf_backend_vendor_name` and `mlperf_backend_name` receive `mlperf_backend_ptr_t` pointer, so they can technically return different values depending on the benchmark settings
https://github.com/mlcommons/mobile_app_open/blob/8920125ce4f310a726faff408e0229f57a9787f4/flutter/cpp/c/backend_c.h#L37 https://github.com/mlcommons/mobile_app_open/blob/8920125ce4f310a726faff408e0229f57a9787f4/flutter/cpp/c/backend_c.h#L43
None of the currently existing backends use this, all backends return constant strings without any conditions.

Is this supposed to always be the case, or are backends expected to potentially return different `backend name` and `backend vendor` values for different benchmarks?

**Comment by freedomtan** [comment]
My understanding is, for TFLite backend, supposedly, 

- backend: tflite
- backend_vendor_name: MediaTek Neuron Delegate
