### ISSUE TITLE
Segfault on Oppo Reno 3 with MediaTek Dimensity 1000L

### ISSUE THREAD

**Issue by bellycat77** [mlcommons/mobile_app_open#29]
Original https://github.com/mlcommons/mobile_app/issues/605

**Comment by relja128** [comment]
Per @freedomtan - no elegant solution found yet. Will disable neuron delegate for this device in the backend.

**Comment by freedomtan** [comment]
avoid using Neuron delegate for Oppo Reno 3 in https://github.com/mlcommons/mobile_app_open/pull/50
