### ISSUE TITLE
Make expected_latency_ns a backend configurable parameter

### ISSUE THREAD

**Issue by Mostelk** [mlcommons/mobile_app_open#291]
Different backends require to set this differently to spend at least 60sec in the single stream benchmark. It should be responsibility of backend to set this correct to get a VALID submission. The default parameter of 1M had to be lowered to 900k or 800k in different v2 submissions. Is better if we set the default parameter as 1M and backend can overwrite if needed 
[mlperf_settings.single_stream_expected_latency_ns](https://github.com/mlcommons/mobile_app_open/blob/submission-v2.0/android/cpp/mlperf_driver.cc#L105)

**Comment by freedomtan** [comment]
make this change to both unified v2.0 and and master branch in another PR after the "main" 2.0 submission change PR.

@anhappdev and @d-uzlov

**Comment by anhappdev** [comment]
Where should the var `single_stream_expected_latency_ns` be set?
Since this var will be different for each backend (and maybe benchmark) I am thinking of letting the vendor set it in
the `benchmark_setting`

https://github.com/mlcommons/mobile_app_open/blob/75e319ee19ca742bce866bd99c7c79bdad0aa480/flutter/cpp/proto/backend_setting.proto#L36-L50

https://github.com/mlcommons/mobile_app_open/blob/511cccfc86e20338c3096bfbe2a6cb38cc9e7900/mobile_back_tflite/cpp/backend_tflite/tflite_settings_android.h#L93-L99

**Comment by freedomtan** [comment]
Yes, as far as I can tell, this looks right. @Mostelk or @fatihcakirs could you confirm it?

**Comment by Mostelk** [comment]
@anhappdev @freedomtan per our discussion today's meeting, Please @anhappdev make similar changes for Android app, so we can prepare unified apk.

**Comment by freedomtan** [comment]
Let's check status here

flutter:
backend | latency checked | notes | reported by|
--------------|-----:|:-----:| ----
Google  |  |  | 
MediaTek  |  |  | 
Qualcomm |  |  | 
Samsung |  |  | 

Android:
backend | latency checked | notes | reported by|
--------------|-----:|:-----:| ----
Samsung |  |  | 
Qualcomm |  |  | 
MediaTek  |  |  | 
Google  |  |  |

**Comment by mohitmundhragithub** [comment]
we tested this parameter. Needed to change the settings in mobile_back_qti, which has been pushed to the PR by @AasheeshT .
The new settings seems to be working fine for us.

**Comment by kcwu** [comment]
The android one works on Google devices. Currently I encountered issues to build flutter version and thus cannot check its status.

**Comment by freedomtan** [comment]
@kcwu Could you elaborate more on issues you met when building flutter version? I could build and run it on my Pixel 6

```
$ make WITH_PIXEL=1
$ cd flutter
$ flutter run
```

**Comment by AhmedTElthakeb** [comment]
This has been verified for Samsung backend up till commit 9bfd2e9.
https://github.com/mlcommons/mobile_app_open/commit/9bfd2e9cada2434ae77e289d631d0e626d3609b7

**Comment by kcwu** [comment]
The flutter version works on google device.

**Comment by mohitmundhragithub** [comment]
The changes works for qualcomm as well.
