### ISSUE TITLE
Add support for displaying several accuracy values per benchmark

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#294]
We may need to use 2 different accuracy metrics for some of the future benchmarks, so we need to modify UI to support it.

**Comment by d-uzlov** [comment]
Here are mockups of some possible easy changes:
<details>
<summary>Top results: option  1</summary>
<img width=300 src="https://user-images.githubusercontent.com/36223296/163918794-cc635337-e5a4-4569-973e-66b82cb0a919.png">
</details>

<details>
<summary>Top results: option 2</summary>
<img width=300 src="https://user-images.githubusercontent.com/36223296/163918976-a129fd6d-d4a2-4062-a235-a286bd4d75fe.png">
</details>

<details>
<summary>Bottom results</summary>
<img width=300 src="https://user-images.githubusercontent.com/36223296/163919023-4dff658b-9417-4128-b6fd-c1ccac1f3dd3.png">
</details>

**Comment by freedomtan** [comment]
let's go for option 1 first.
