### ISSUE TITLE
Samsung backend does not destroy itself between tasks

### ISSUE THREAD

**Issue by bellycat77** [mlcommons/mobile_app_open#30]
Original https://github.com/mlcommons/mobile_app/issues/610

**Comment by relja128** [comment]
Per @Mostelk this is getting pushed back to post 1.1 (waiting for new submission)

**Comment by relja128** [comment]
Per @mcharleb - This is the check in the front end, the FE doesn't delete the backend, because the BE used to crash on delete. Probably in taskrunner.
@Mostelk - will take a look

**Comment by TheKanter** [comment]
@Mostelk When can we expect your team to clear this?

**Comment by relja128** [comment]
Per @Mostelk - v2 should fix this.

**Comment by al-mahi** [comment]
PR [197](https://github.com/mlcommons/mobile_app_open/pull/197)

**Comment by al-mahi** [comment]
Updated PR https://github.com/mlcommons/mobile_app_open/pull/197

**Comment by relja128** [comment]
Pushing this off for post 2.0 submission.

**Comment by freedomtan** [comment]
@jwookiehong will check if the latest samsung backend resolved this issue.

**Comment by AhmedTElthakeb** [comment]
Will need this [PR ](https://github.com/mlcommons/mobile_app_open/pull/271) to integrate our new and old backends

**Comment by freedomtan** [comment]
It seems there is not such problem for the new Samsung backend. Close this for now.

**Comment by AhmedTElthakeb** [comment]
A workaround is provided in the following [PR#283](https://github.com/mlcommons/mobile_app_open/pull/283), newer generations won't have this problem.

**Comment by AhmedTElthakeb** [comment]
This issue has been resolved for all generations (old and new) in the latest android app merge, no workarounds are needed any more. 
https://github.com/mlcommons/mobile_app_open/tree/android-v2
Commit# a47423
