### ISSUE TITLE
Show task name from `tasks.pbtxt` instead of hard-coded string

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#302]
Currently we show only hard-coded name for 5 different tasks type: IC, IC(offline), OD, IS, LU.

https://github.com/mlcommons/mobile_app_open/blob/149b224fd5b19179bc6acd5418a243e4d7e89372/flutter/lib/benchmark/info.dart#L36-L68

We should show the task name from the `task.pbtxt` instead.

**Comment by jwookiehong** [comment]
For the segmentation task, @jwookiehong to provide updated text by next engineering meeting 5/17.

**Comment by freedomtan** [comment]
@TheKanter and @jwookiehong please check the update text

**Comment by jwookiehong** [comment]
@TheKanter

Here is weijun’s writeup. Please have a gander.

*Image Segmentation (MOSAIC)*

Semantic image segmentation partitions an input image into labeled regions
at pixel granularity, and is used for complex image scene parsing to power
downstream image analysis and processing. The reference model is the MOSAIC
network, which was designed with current mobile processors and accelerators
in mind, and uses a 512x512 input image resolution. The backbone feature
extractor uses a modified version of MobileNet-v3.5-MultiHardware which was
the result of Network Architecture Search (NAS) considering inference speed
on various mobile processors and accelerators. Performance and accuracy are
evaluated on the ADE20K validation dataset. The benchmark requires a mean
Intersection Over Union (mIoU) value of 57.36% (96% of FP32 accuracy).

MOSAIC uses an efficient multi-scale context encoder and a light-weight
hybrid decoder to recover spatial details from aggregated information.
MOSAIC produces state-of-the-art results balancing between model accuracy
and speed across CPUs, GPUs, DSPs and NPUs.
