### ISSUE TITLE
Please enable offline scenario for SSD-MobileDet, MobileBert and MOSAIC workloads.

### ISSUE THREAD

**Issue by mkankana** [mlcommons/mobile_app_open#304]
Application currently requires each workload to have specific benchmark_id , there are no benchmark IDs for SSD-MobileDet, MobileBert and MOSAIC workloads in offline scenario. Can this be implemented in the default mode .

**Comment by jwookiehong** [comment]
This is a policy choice, and should be addressed in the main WG meeting.

**Comment by freedomtan** [comment]
@mkankana if you want to submit them, please send PR so others could reuse those IDs.

**Comment by freedomtan** [comment]
@anhappdev will try to outline a document on how to add offline scenario of a benchmark

**Comment by anhappdev** [comment]
To add a new (offline) benchmark, please follow those steps:
* Add new benchmark_setting in backend setting file (e.g `mobile_back_tflite/cpp/backend_tflite/tflite_settings_android.h`)
* Make a copy of `https://raw.githubusercontent.com/mlcommons/mobile_models/main/v2_0/assets/tasks_flutterapp.pbtxt` then add a new task to it
* Update `_defaultConfigUrl` in `flutter/lib/resources/config_manager.dart` to point to the new task file
* Update `_MAX_THROUGHPUT` in `flutter/lib/benchmark/info.dart` to add max throughput for the new `benchmark_id`
* Build and run the app

As an example, I added an offline scenario for Object Detection in this PR https://github.com/mlcommons/mobile_app_open/pull/311, you can see the [changes](https://github.com/mlcommons/mobile_app_open/pull/311/files) needed there.
Noted that the UI is not yet optimized for more than 6 tasks, but the app run without any issue.

**Comment by mkankana** [comment]
This works . Thanks for a very detailed instructions @anhappdev
