### ISSUE TITLE
Easy way to detect invalid results

### ISSUE THREAD

**Issue by mohitmundhragithub** [mlcommons/mobile_app_open#306]
We should show some indication on the UI that the results are valid or not. During the last submission, we some invalid results caused unnecessary work for SS and QC at the last moment.
Some indication on the UI (say colour change of the case which is invalid or some error message), will definitely help in avoiding such unnecessary work.

**Comment by freedomtan** [comment]
We can check result json file to if a benchmark result is valid or not. Dunno if loadgen returns valid  or not in its API.

@d-uzlov please help this after windows related ones.
