### ISSUE TITLE
Change task config structure

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#322]
<details>
<summary>initial proposal</summary>

Link to current tasks file for reference: https://github.com/mlcommons/mobile_models/blob/34613bb03c02e98b9b72e6cb6ac63d1da2d62bba/v2_0/assets/tasks_flutterapp.pbtxt

## Issues with current tasks config
* Some values from [`ModelConfig`](https://github.com/mlcommons/mobile_app_open/blob/af9103845dcbbed8e2e969e746f2a8cb558b32bc/flutter/cpp/proto/mlperf_task.proto#L80-L104) are not used in the app:
  * `score_max`
  * `accuracy_max`
  * `image_width`
  * `image_height`
  * `num_classes`
  * `description`
  * `tags`
  * `name`
    * This is `task.model.name`
    * Do not confuse with `task.name`
* Some of those values are not even defined anywhere in our tasks file:
  * `description`
  * `accuracy_max`
* `offset` value should probably be defined for dataset, not for model
* Benchmark ID is used as several values serialized to string but there is no defined structure  
  * Examples:
    * `IS_uint8_mosaic`
    * `IC_tpu_uint8`
  * First 2 letters are the "benchmark type" code, and one of the first things the app does is it extracts this code from the ID to look up benchmark icon, and description, and other stuff.
  * The rest of the ID content is not used anywhere except to differentiate additional values from `ModelConfig`.
  * Such compound IDs were probably intended to allow to use different options for different models. For example, `image_width=224` for `uint8`, `image_width=320` for `float32`.
  * In the current tasks file the only difference between some of the IDs is `score_max` value.
* Data type in benchmark ID doesn't do anything
  * It doesn't help frontend to determine required data type, there are special backend functions for this.
  * It doesn't apply any restrictions on backend. Backend can declare benchmark with ID `XX_float32` and still use `uint8`, for example.
* [minor] `DatasetConfig` defines dataset type
  * It doesn't make any sense to use different types of datasets for performance and accuracy modes.
* [minor] Dataset data is duplicated if several benchmarks use the same dataset
  * Currently `Imagenet` and `ADE20K` are defined twice

## Proposal

* Remove unused options
* Move `offset` to dataset config
* Define datasets separately, each task config will specify dataset ID instead of full dataset description
* Collapse benchmark IDs to one value per task
  * Each value will be used without any modifications
    * For each value app will look up a unique icon, name, description
  * Examples:
    * `image_classification_mobilenet_edgetpu`
    * `image_classification_mobilenet_edgetpu_offline`
    * `image_segmentation_mosaic`
    * `image_segmentation_deeplabv3`
* Obtain real data type in run time

## Open questions

* Should the app respect `score_max` value?
  * Currently max score values are backed into the frontend
* Do we need to add `accuracy_max` to the tasks file?

</details>

Current proposal is here: https://github.com/mlcommons/mobile_app_open/issues/322#issuecomment-1148030958

**Comment by anhappdev** [comment]
Here is my thought:

> Some values from ModelConfig are not used in the app:

> * Remove unused options

> * Do we need to add `accuracy_max` to the tasks file?

Some information like `image_width`, `image_height`, `num_classes` is quite crucial for the ML model. Normally, the images will be resized to match the model input. Maybe because it can be obtained directly from the ML model, we do not get it from the task file.
Some other information like `description`, `tags`, `accuracy_max`, ... are nice to have but like a DB, not every data field is required. 

I think all of this extra information is more for the human to read than for the app to process it.


> * `offset` value should probably be defined for dataset, not for model

> * Move `offset` to dataset config

`offset` can be defined for the model (for the output label of the model) because the model can have additional background classes.

> * Define datasets separately, each task config will specify dataset ID instead of full dataset description

The current data schema is more like NoSQL. To avoid duplicate, we need to switch to a relational schema. But there are advantage and disadvantage for each schema. The current task file with nested structure is quite easier for human to read IMO.

> * Collapse benchmark IDs to one value per task
>   
>   * Each value will be used without any modifications
>     
>     * For each value app will loop up a unique icon, name, description
>   * Examples:
>     
>     * `image_classification_mobilenet_edgetpu`
>     * `image_classification_mobilenet_edgetpu_offline`
>     * `image_segmentation_mosaic`
>     * `image_segmentation_deeplabv3`

There are some comments about the format of `benchmark_id`. But yes, it's not very precise.
`BenchmarkSetting.benchmark_id`  // Id of the benchmark. Must match the id in ModelConfig::id.
`ModelConfig.id`  // Unique id of the model. Format: TaskID_ModelID;

> * Data type in benchmark ID doesn't do anything

> * Obtain real data type in run time

We can detect the data type in run time. But the data type is relevant for the ML model and also quite important to know by just reading the code / task file. I think it should be a separated field in `ModelConfig`. 

>   * It doesn't make any sense to use different types of datasets for performance and accuracy modes.

I think this is more a policy question.


> ## Open questions
> * Should the app respect `score_max` value?
>   
>   * Currently max score values are backed into the frontend

I think `score_max` here means `max_throughput`, right? In that case, we should actually use the `max_throughput` defined in the task file instead of hard-coded one in the app:

https://github.com/mlcommons/mobile_app_open/blob/a12554dba8e3adee60791fbc27de16e80cfe7601/flutter/lib/benchmark/info.dart#L109-L126

**Comment by d-uzlov** [comment]
> Some information like `image_width`, `image_height`, `num_classes` is quite crucial for the ML model. Normally, the images will be resized to match the model input. Maybe because it can be obtained directly from the ML model, we do not get it from the task file.

It seems like image size is hardcoded into the native code:
https://github.com/mlcommons/mobile_app_open/blob/af9103845dcbbed8e2e969e746f2a8cb558b32bc/flutter/cpp/flutter/main.cc#L102

>offset can be defined for the model (for the output label of the model) because the model can have additional background classes.

Then it should be defined in the backend settings.



I think the major issue with `ModelConfig` is that it is _not_ a model configuration. Each backend uses its own model, so we can't really define any model-specific configuration in the tasks file.
`ModelConfig` could be used as a reference of how the model should look like. But right now we have several `ModelConfig` values per task, and I don't think it makes any sense to have more than one reference.

**Comment by anhappdev** [comment]
> It seems like image size is hardcoded into the native code

I think we should refactor the code to remove hard-coded values like those (and also `max_throughput` mentioned in other comment).

> Then it (offset) should be defined in the backend settings.
> I think the major issue with ModelConfig is that it is not a model configuration. Each backend uses its own model, so we can't really define any model-specific configuration in the tasks file.

It depends on which parameter the backend can change (policy relevant I assume). `offset` is similar to `image_height`, `image_width` in that they are all model related, but if the backend is not allowed to change it, it makes sense to define it in `ModelConfig`

> I'm talking about dataset types.

I am quite not clear what you mean, can you provide an example `enum` for `dataset_type`? `imagenet` is just the name of a dataset for image classification (others are e.g. MNIST, CIFAR‑10)

We do need some changes in the data structure, but I think adding more fields to `ModelConfig` (e.g. `data_type (float16|float32|uint8|...)`, `task_type(ic|od|is|...)`, etc.) should be enough for the app to differentiate them.

**Comment by d-uzlov** [comment]
> > I'm talking about dataset types.
> 
> I am quite not clear what you mean, can you provide an example `enum` for `dataset_type`? `imagenet` is just the name of a dataset for image classification (others are e.g. MNIST, CIFAR‑10)

The enum is here:
https://github.com/mlcommons/mobile_app_open/blob/af9103845dcbbed8e2e969e746f2a8cb558b32bc/flutter/cpp/proto/mlperf_task.proto#L59-L65

Look at the `flutter/cpp/datasets` folder, there are several classes for different types of datasets.

In the app frontend doesn't do anything with dataset type except it passes it to native code:
https://github.com/mlcommons/mobile_app_open/blob/af9103845dcbbed8e2e969e746f2a8cb558b32bc/flutter/lib/benchmark/benchmark.dart#L198
https://github.com/mlcommons/mobile_app_open/blob/af9103845dcbbed8e2e969e746f2a8cb558b32bc/flutter/cpp/flutter/main.cc#L98

When you specify `task.dataset.type` field in the config, you don't specify the actual dataset that you want to use. You specify which C++ class from the `flutter/cpp/datasets` directory you want to use to handle data that you specify in other fields of `task.dataset` object.

**Comment by anhappdev** [comment]
In this case, the dataset type means actually the dataset, IMO. The type enum is just for convenience coding purpose I guest.

**Comment by freedomtan** [comment]
@d-uzlov to provide revised proposal based on discussions above. 

We need opinions from backends. @freedomtan @mohitmundhragithub @fatihcakirs @karimnosseir @ptt2panda

**Comment by d-uzlov** [comment]
## Short summary

<details>
<summary>Current structure example</summary>

Tasks file:

```pbtxt
task {
  name: "Image classification"
  dataset {
    name: "Imagenet classification validation set"
    type: IMAGENET
    path: "app:///mlperf_datasets/imagenet/img"
    groundtruth_src: "app:///mlperf_datasets/imagenet/imagenet_val_full.txt"
  }
  lite_dataset { ... }
  test_dataset { ... }
  model {
    id: "IC_tpu_uint8"
    name: "MobileNetEdgeTPU 224 1.0 Uint8"
    offset: 1
    tags: "uint8"
    scenario: "SingleStream"
    description: <null>
    accuracy_max: <null>
    score_max: 1000
    image_width: 224
    image_height: 224
    num_classes: 123
  }
  model { ... }
  min_query_count: 1024
  min_duration_ms: 60000
}
```

Backend config:

```pbtxt
benchmark_setting {
  benchmark_id: "IC_tpu_uint8"
  accelerator: "nnapi"
  accelerator_desc: "NNAPI"
  configuration: "TFLite"
  src: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/tflite/mobilenet_edgetpu_224_1.0_uint8.tflite"
  md5Checksum: "008dfcb1c1962fedbeef1b998d4c84f2"
}
```
</details>

<details>
<summary>Proposed structure example</summary>

Tasks file:

```pbtxt
task {
  name: "Image classification"
  id: "image_classification"
  dataset {
    type: IMAGENET
    full: {
      name: "Imagenet classification validation set"
      path: "app:///mlperf_datasets/imagenet/img"
      groundtruth_src: "app:///mlperf_datasets/imagenet/imagenet_val_full.txt"
    }
    lite: { ... }
    test: { ... }
  }
  min_query_count: 1024
  min_duration_ms: 60000
  scenario: "SingleStream"
  accuracy_max: 123
  score_max: 1000
}
```

Backend config:

```pbtxt
benchmark_setting {
  benchmark_id: "image_classification"
  accelerator: "nnapi"
  accelerator_desc: "NNAPI"
  configuration: "TFLite"
  src: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/tflite/mobilenet_edgetpu_224_1.0_uint8.tflite"
  md5Checksum: "008dfcb1c1962fedbeef1b998d4c84f2"

  offset: 1
  image_width: 224
  image_height: 224
  num_classes: 123
}
```
</details>

## Open questions

* What is the purpose of `image_width`, `image_height`, `num_classes`, `offset` fields?
  * Currently they are hardcoded in the sources. Values from tasks file are ignored
  * As far as I understand, each model has predefined input/output size. If we specify values that don't match actual parameters of the model the results will be wrong
  * Are backends allowed/expected to use models with non-default input/output size?
  * Is it supposed to be just a reference, and the app must ignore it?

**Comment by freedomtan** [comment]
@freedomtan to find docs contain submission rules for reference use

**Comment by d-uzlov** [comment]
If the model is supposed to be the same in all backends then I think we need much less changes.
I've updated proposed structure example in my previous post, reverting some of the proposed changes because they are irrelevant in this case.

**Comment by freedomtan** [comment]
Submission rules

- https://github.com/mlcommons/mobile_open/blob/main/rules/mobile_inference_rules.adoc
- https://github.com/mlcommons/mobile_open/blob/main/rules/submissionRuleV2_0.adoc

**Comment by anhappdev** [comment]
My comment to the [proposed structure from 2022-06-15](https://github.com/mlcommons/mobile_app_open/issues/322#issuecomment-1148030958):

<details>
<summary>Proposed structure example</summary>

Tasks file:

```pbtxt
task {
  name: "Image classification"
  id: "image_classification"
  dataset {
    type: IMAGENET
    full: {
      name: "Imagenet classification validation set"
      path: "app:///mlperf_datasets/imagenet/img"
      groundtruth_src: "app:///mlperf_datasets/imagenet/imagenet_val_full.txt"
    }
    lite: { ... }
    test: { ... }
  }
  min_query_count: 1024
  min_duration_ms: 60000
  scenario: "SingleStream"
  model {
    offset: 1
    image_width: 224
    image_height: 224
    num_classes: 123
    accuracy_max: 123
    score_max: 1000
  }
}
```

Backend config:

```pbtxt
benchmark_setting {
  benchmark_id: "image_classification"
  accelerator: "nnapi"
  accelerator_desc: "NNAPI"
  configuration: "TFLite"
  src: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/tflite/mobilenet_edgetpu_224_1.0_uint8.tflite"
  md5Checksum: "008dfcb1c1962fedbeef1b998d4c84f2"
}
```
</details>


1. The proposed structure assumes a task can only use one model. Is it desired? I can image using one model optimized for performance mode and another optimized for accuracy mode (policy dependent, but policy can easily be changed, not our code / data structure).
2. It's quite important to know the data type of the model. We should have that field.

**Comment by freedomtan** [comment]
it should be safe to remove data type from benchmark id.

**Comment by mohitmundhragithub** [comment]
> 

For 1, we need to validate if the accuracy is met for the model used for measuring performance. So, we do need a single model only. However, I remember intel were asking for capability to pass 2 files. @mkankana can confirm.

For 2, till now, there has been flexibility with the user to select any of the datatype. Do, we wish to show the datatype being used on the UI? Having some datatype just in the config may not be as useful. With new models getting added, just thinking, it may help to display in the UI as well? 

Apart from above, I hope we are not removing "custom_setting" field in benchmark setting.

**Comment by d-uzlov** [comment]
> For 2, till now, there has been flexibility with the user to select any of the datatype. Do, we wish to show the datatype being used on the UI?

The issue with datatype in the config is that it doesn't mean anything. Datatype is defined by backend. If config says uint8 and the backend says float32, it will be float32. Datatype in config could only be used as a reference of what to _expect_ from backend but it's not enforced.

But I think it would be useful to save datatype in result history. We could show it in the history UI and use for some statistics.

> Apart from above, I hope we are not removing "custom_setting" field in benchmark setting.

No, certainly not.

**Comment by freedomtan** [comment]
Let's shut for 3.0 for this multiple files for a model feature.

**Comment by d-uzlov** [comment]
All related PRs have been merged, we can close this.
