### ISSUE TITLE
The app is impossible to build on macOS Monterey

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#329]
Bazel 4.2.2 requires python2 in system folder on macos, particularly `/usr/bin/python`.
macOS 12 Monterey removed it, so bazel is no longer able to work.
It seems like the only viable solution here is to use newer bazel version (the fix is available starting from 5.0.0). Theoretically we could also build our custom modified bazel-4.2.2 with a patch from newer bazel version but I would prefer to use the official version.

**Comment by freedomtan** [comment]
bazel 5.x looks to be a reasonable one since we are moving to TensorFlow 2.8 or later.
