### ISSUE TITLE
Remove binary file `tensorflow-lite-neuron.aar`

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#331]
The binary file `mobile_back_tflite/cpp/backend_tflite/neuron/tensorflow-lite-neuron.aar` should be downloaded from internet or removed from Git.
See https://github.com/mlcommons/mobile_app_open/pull/292#issuecomment-1140893469

**Comment by freedomtan** [comment]
@freedomtan to get MediaTek's Neuron Delegate repo updated to replace this binary `.aar`.
