### ISSUE TITLE
Use max throughput from task file

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#344]
The values for max throughput are hard-coded in the app:
https://github.com/mlcommons/mobile_app_open/blob/a6a9ce78ba6f61157bc2f19639d6ce0f3b259d65/flutter/lib/benchmark/info.dart#L116-L133

We should get this value from the task file, it makes adding new task easier without code change.
https://github.com/mlcommons/mobile_app_open/blob/75e319ee19ca742bce866bd99c7c79bdad0aa480/flutter/cpp/proto/mlperf_task.proto#L92-L93

**Comment by freedomtan** [comment]
why do we need these values? Just for the speed dial?

**Comment by anhappdev** [comment]
Yes, it's used currently only for the UI.
