### ISSUE TITLE
Show intermediate progress when running benchmarks

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#348]
Originally proposed in https://github.com/mlcommons/mobile_app_open/issues/333

Currently the app only shows which benchmark is currently running.
If a benchmark takes a long time it looks as if the app is stuck and nothing is happening.

We need to show intermediate progress to make it clear that there is some incremental progress.

Currently we have a progress screen with benchmark name and numeric progress in percent, but percent value only increments in steps of `100% / number of selected benchmarks`.

We can modify [MlperfDriver](https://github.com/mlcommons/mobile_app_open/blob/193b423222ad6def7dabb2adcef78ec762648cec/flutter/cpp/mlperf_driver.cc) to report how many queries are finished.
Additional code in the main benchmark thread can affect results so we will need to make sure that performance penalty is acceptable (preferably unnoticeable).
We can probably update [atomic](https://en.cppreference.com/w/cpp/atomic/atomic) variable in the benchmark loop and query that variable from UI on some interval. I think we won't see any performance difference this way.

We can also check if loadgen reports any intermediate progress. However, even if it does, loadgen doesn't have any way to know progress of Offline benchmarks.

**Comment by anhappdev** [comment]
Instead of showing the progress in percent, we can show the progress in step, e.g. 
`2/5 benchmarks completed`.
This way the users don't expect the progress number changes more often like the case with percent number. And it takes much less effort to implement.

**Comment by mkankana** [comment]
What if user selects only 1 benchmark to run ? In this case there is no user feedback till the workload is completed. For workloads like MobileBert ( which take longer run time) , users can get a feeling of application being stuck.
