### ISSUE TITLE
Flutter TFlite backend fails to run on Windows

### ISSUE THREAD

**Issue by mkankana** [mlcommons/mobile_app_open#352]
STEPS TO REPRODUCE:
1. git clone https://github.com/mlcommons/mobile_app_open.git ( last commit ID 2af39db4275fdcf40a9a96a3dca2f7e7bdf08c46)
2. make flutter ( No compilation error observed)
3. cd  flutter
4. flutter run

ERROR MESSAGE :

> flutter: Exception: dart_ffi_mlperf_config result: nullprt
> flutter: Exception stack: #0      getMLPerfConfig (package:mlperfbench/backend/bridge/ffi_config.dart:31:5)
>   #1      BenchmarkState.loadResources (package:mlperfbench/benchmark/state.dart:143:9)
>   <asynchronous suspension>
>   #2      BenchmarkState.create (package:mlperfbench/benchmark/state.dart:173:5)
>   <asynchronous suspension>
>   #3      launchUi (package:mlperfbench/main.dart:47:7)
>   <asynchronous suspension>
>   #4      main (package:mlperfbench/main.dart:29:5)
>   <asynchronous suspension>

**Comment by d-uzlov** [comment]
We incorrectly updated structure of the app config in one of the latest commits.
For now you can manually clear app cache (on Windows it's currently located in the `<user>/Downloads/loaded_resources`) until we get this properly fixed.
