### ISSUE TITLE
Setup automated Jenkins jobs for building/testing master branch

### ISSUE THREAD

**Issue by bellycat77** [mlcommons/mobile_app_open#36]

**Comment by bellycat77** [comment]
Jobs were created. Need to check automation

**Comment by relja128** [comment]
For now this has no extra gates compared to mobile_app.

**Comment by bellycat77** [comment]
@relja128 The "gate" will be needed for PRs only. Because only approved/tested/buildable PRs can be merged to the master branch. Additional issue #42 was created
