### ISSUE TITLE
Using Core ML directly on iOS 16 and macOS 13

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#360]
- Apple introduced Core ML profiling mechanisms in iOS 16 and macOS 13, https://developer.apple.com/videos/play/wwdc2022/10027/
- TFLite CoreML delegate uses older version of coremltools and supports only few ops

No, not for 2.1, iOS 16 is supposed to be publicly available in Sep.

I could run [MobileDet mlmodel I shared before](https://drive.google.com/file/d/1BXcyA0Z4zHo2mhw1zVBPNMyhHFr3GHv5/view?usp=sharing) fully on Neural Engine in iPhone 13.

|iphone 13|iPhone 11 Pro|
|-------------|--------------------|
| <img width="240" alt="Screen Shot 2022-06-10 at 5 11 38 PM" src="https://user-images.githubusercontent.com/3395998/173038610-dbd31790-1e8f-4a5c-873b-85d1a2115d27.png"> | <img width="240" alt="Screen Shot 2022-06-10 at 5 12 03 PM" src="https://user-images.githubusercontent.com/3395998/173038275-b0ca2a74-0aab-4315-beb8-ce5c36f6877f.png"> |

**Comment by freedomtan** [comment]
|model|latency (ms)|notes| screenshot|
|-|-:|-|-|
|Mobilenet EdgeTPU| 0.93| 80/80 Neural Engine |<img width="1020" alt="Screen Shot 2022-06-10 at 8 47 27 PM" src="https://user-images.githubusercontent.com/3395998/173067729-3e9c5737-239f-4d9e-997c-2c2bca84888a.png"> |
|MobileDet|3.64|213/213 Neural Engine|![](https://user-images.githubusercontent.com/3395998/173038610-dbd31790-1e8f-4a5c-873b-85d1a2115d27.png)|
|DeepLabV3+| 10.53| 112/114 Neural Engine, 2/114 CPU|<img width="889" alt="Screen Shot 2022-06-10 at 8 55 59 PM" src="https://user-images.githubusercontent.com/3395998/173069153-7e5dd357-f325-4b30-83a1-7bb3d7616dc4.png">|
|MobileBERT| 8.33| 2448/2458 Neural Engine, 10/2458 CPU| <img width="1113" alt="Screen Shot 2022-06-10 at 8 43 38 PM" src="https://user-images.githubusercontent.com/3395998/173066830-f1d3145d-f90c-4ef7-9c0f-095393c60a18.png">|

**Comment by freedomtan** [comment]
Core ML delegate status check.
1. coremltools updated to 5.2 in April, https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace2.bzl#L856-L862
2. coreml delegate only supports Core ML v2 and v3 (Core ML spec v3 and v4), https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/coreml/coreml_delegate.mm#L163, https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/coreml/coreml_executor.mm#L181-L191
3. list of [supported op](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/coreml/README.md#supported-ops)

With these, it seems not easy to get the Core ML delegate to be as good as using Core ML directly soon.

**Comment by freedomtan** [comment]
@jwookiehong FYI.

**Comment by freedomtan** [comment]
|benchmark|Core ML (ms) |Core ML delegate (ms, the flutter app)| Notes | 
|--|--:|---:|--|
|MobileNet EdgeTPU|  0.93 | 1.61 |
|MobileDet|  3.64 |  3.44 | post-process on Neural Engine is not faster! |
|DeepLabV3+|  10.53 | 32.71 | fallbacks|
|MobileBERT| 8.33 | 100.60 |  CoreML delegate actually uses GPU |

**Comment by freedomtan** [comment]
@anhappdev could you try to revive the Core ML backend work in a separate branch. Originally, I thought we won't be able to make it in Sep, so let's start this after 2.1 submission. During the work group meeting Wookie and others think, given good Core ML numbers, we should strive to have a Core ML backend as early as possible.

**Comment by anhappdev** [comment]
I am trying to integrate the Core ML backend to our Flutter app but could not figure out how to do it properly because I have worked mostly on the frontend part of the app. Since Danil has already integrated the Windows backend before, I think Danil is more suited for this task and would take less time than me doing it.
@d-uzlov Would you give it a try? You can use the Core ML models I published [here](https://github.com/anhappdev/coreml-models).

**Comment by freedomtan** [comment]
We used to have a dummy backend which was used a template for new mobile backend. It seems we removed it. Maybe we should reintroduce a dummy backend (or a template) for new backend implementation. And simple documentation for new backend implementation.

**Comment by d-uzlov** [comment]
> Since Danil has already integrated the Windows backend before

I didn't really implement a new backend for Windows, I only fixed issues with tflite backend to make it work on Windows.
But I have worked with tflite sources a bit so I'm should able to answer any questions about out backend API or the tflite backend itself.

> I think Danil is more suited for this task and would take less time than me doing it.

I have never worked with CoreML. As far as I understand, CoreML requires using Swift, and I haven't worked with Swift either.
Anh, if you have some experience CoreML, I think it would be faster if I was just helping you with clarifying backend documentation.

**Comment by freedomtan** [comment]
Public Core ML API is available in both [Objective-C](https://developer.apple.com/documentation/coreml?language=objc) and [Swift](https://developer.apple.com/documentation/coreml?language=objc). For implementing the mlperf backend C interface, Objective-C is more intuitive. Yes, it's possible to call Swift function from C. To me, it's not as convenient as using Objective-C methods directly.

I think the very first step to do is to implement functions declared in [flutter/cpp/c/backend_c.h](https://github.com/mlcommons/mobile_app_open/blob/master/flutter/cpp/c/backend_c.h) in C (.c) or Objective-C (.m).

**Comment by anhappdev** [comment]
I am mostly proficient in Swift and have limited experience with Objective-C. Normally, I would prefer using Swift over Objective-C since it's better documented and supported, but in this case, Objective-C is actually more suited because of the need for interfacing with C. @freedomtan I assume you are experienced in Objective-C and can provide help here?

@freedomtan @d-uzlov Let try working on it together and see how it's going. I created a new branch `360-add-coreml-backend` for it.

**Comment by freedomtan** [comment]
@anhappdev 
Yes, I do have some Objective-C experience (because I actually learned object-oriented programming in [Smalltalk-80](https://en.wikipedia.org/wiki/Smalltalk) :-))

Thanks for creating the branch (#421). I think the next step is to create shared library instead of static library (as @d-uzlov suggested in #423) and then we can use the [command line program](https://github.com/mlcommons/mobile_app_open/tree/master/flutter/cpp/binary) to test MobileNet EdgeTPU on macOS first.

**Comment by freedomtan** [comment]
I get similar numbers when running my simple program with Xcode + Instruments (w/ the new CoreML template) https://github.com/freedomtan/SimpleCoreMLBenchmark

**Comment by anhappdev** [comment]
@freedomtan The documentation for the [command line program](https://github.com/mlcommons/mobile_app_open/tree/master/flutter/cpp/binary) seems to be outdated. Can you update it?

In general, I think we can split this task in 2 smaller one:
1. Create a Core ML backend by implementing the C interface
2. Integrate the backend into our build system

I am trying to do the second one first with a mockup / dummy backend, so we can easily test the implementation while coding it. Any comment on this approach?

**Comment by freedomtan** [comment]
created an issue for updating the command line program, https://github.com/mlcommons/mobile_app_open/issues/443
