### ISSUE TITLE
Update website design

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#374]
Initially we created a temporary design for the website, just to make it clear that website works.
Now we have a new design mockups (link is in the website proposal document), so we should update the website.

**Comment by mkankana** [comment]
@d-uzlov thanks for the new design mocks. Working group has shifted the decision to have a MVP at this time.
Could you please re-evaluate a do a mock with below considerations.

1 . User can upload results to a database.
2. User can compare his results with other uploaded results.

**Comment by d-uzlov** [comment]
Closing this since we decided to skip developing website for now.
We'll track progress for uploading-related app pages in different github issues.
