### ISSUE TITLE
flutter app remains stuck at 0% on rerunning after a failed case

### ISSUE THREAD

**Issue by mohitmundhragithub** [mlcommons/mobile_app_open#376]
Steps to reproduce: 
1) Make sure any one of the model fails to run and results in crash (app closes).
2) Run the suite by clicking on "go".
3) Once the app crashes, open the app again to find that it remains stuck at 0%.

From the logs, seeing below error message of Md5 Checksum failure, although it runs fine the first time.

![image](https://user-images.githubusercontent.com/1549325/174592683-73143eab-131b-4906-b4dd-f2450119a016.png)

**Comment by d-uzlov** [comment]
> 1. Make sure any one of the model fails to run and results in crash (app closes).

How do you do that?

App being stuck on 0% if checksum validation failed is a known issue (though, it's not well documented):
* https://github.com/mlcommons/mobile_app_open/issues/307

However, I don't see why files would change on app crash. Especially several model files at once.
App launches benchmarks one at a time.
If you run 6 benchmarks, and the last one crashed, it means the first 5 have finished successfully.
If all of the models failed checksum validation then model files are modified regardless of the crash.

**Comment by mohitmundhragithub** [comment]
I think i was able to find the issue at our end. It seems to be not related to the flutter app. I will withdraw this.
But some visual error for the issue will be great. But, closing it for now.
