### ISSUE TITLE
flutter app crashes with sdk 31

### ISSUE THREAD

**Issue by AhmedTElthakeb** [mlcommons/mobile_app_open#379]
[s22p_sdk31_crash.log](https://github.com/mlcommons/mobile_app_open/files/8945690/s22p_sdk31_crash.log)

Building the app with Samsung backend with the updated sdk31, the app crashes running any benchmark. Logcat file is attached.

**Comment by freedomtan** [comment]
@freedomtan to add runtime ld debug android prop information here.

**Comment by freedomtan** [comment]
According to the [Android linker changes for NDK developers](
https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#enable-logging-of-dlopen_dlsym-and-library-loading-errors-for-apps-available-in-android-o), we can do something like
```
adb shell setprop debug.ld.all dlerror,dlopen

```
Then all the dlopen() and dlerror() calls will be logged and we can get them from `logcat`.
