### ISSUE TITLE
Include task file as an asset in the app

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#381]
Problem:
At first start, the app downloads and caches the task file. The app can only understand a certain schema of the task file. A crash can occur if:
1. The app is updated to use a new schema but still read the **cached** task file
2. The task file is updated, but the app is not updated.

It's not possible to catch the first case with CI, since we don't know which cached version the users have.

Suggestion:
We include the task file as an asset in the app. If we need to deploy a new task file, we just deploy a new app. Since we are planing to publish the app in the app store, deploying a new version should be easy. If we want the users to use the latest version of the task file, we can remotely force an app update (I have implemented this in many apps before and it works quite well).

Note: The app can use a custom task file, see [custom-tasks.md](https://github.com/mlcommons/mobile_app_open/blob/8d66afcc8b95d44661ce90d2c2f18add8f0d163b/flutter/documentation/custom-tasks.md)

Related: https://github.com/mlcommons/mobile_app_open/issues/354

**Comment by d-uzlov** [comment]
Related (actually the exact same task):
* https://github.com/mlcommons/mobile_app_open/issues/362
