### ISSUE TITLE
Current md5 checksum doesn't match with QTI workflow

### ISSUE THREAD

**Issue by mohitmundhragithub** [mlcommons/mobile_app_open#389]
Found an issue that on re-running the flutter app with qti backend md5 checksum fails at the start for the models. 
The reason for this is QTI backend updates the DLC with accelerator cache, which helps in faster initialisation in subsequent runs.

We will need to fix this behaviour in the app. May be the app can do md5 check only when downloading the models for the very first time from github, rather than to do it during every open of the app.

**Comment by anhappdev** [comment]
@freedomtan This changes the behavior of the app. Please confirm if this one should be implemented.

**Comment by freedomtan** [comment]
> @freedomtan This changes the behavior of the app. Please confirm if this one should be implemented.

Let's discuss this in the meeting tomorrow.

**Comment by freedomtan** [comment]
Let's move the discussion to the mobile policy meeting.

**Comment by anhappdev** [comment]
One thing to note: If the app validates the checksum only when downloading files from internet, it will not validate the checksum when loading files from local disk (if the path in the task file start with `app://`).

**Comment by mkankana** [comment]
Qualcomm has concluded to rebuild the app from source for internal SDK updates, which solves the issue. I think all other vendors can adopt to the same path.
@mohitmundhragithub could you please confirm.

**Comment by mohitmundhragithub** [comment]
Sure, I will close this Issue.
