### ISSUE TITLE
Make cooldown 5 min by default

### ISSUE THREAD

**Issue by mohitmundhragithub** [mlcommons/mobile_app_open#390]
Currently the flutter app's cooldown period is set to off. But, for testing, we generally keep the cooldown to 5 mins for submission runs. May be we should keep the default value to 5mins?

**Comment by freedomtan** [comment]
Sounds good to me. I am not sure we should assume that this app is for submission only, though.

**Comment by freedomtan** [comment]
Let's do it. @d-uzlov
