### ISSUE TITLE
LOG in backend don't show in logcat

### ISSUE THREAD

**Issue by kcwu** [mlcommons/mobile_app_open#406]
In the past (v2 branch), LOG lines in backend will appear in logcat. But in the flutter app (master branch), LOG lines in backend don't show in logcat.

p.s. I can see LOG message from cpp/flutter/dart_run_benchmark.cc in logcat. But no lines from backends.

**Comment by freedomtan** [comment]
`LOG(INFO) <<  ...` should work. Is it redefined? @d-uzlov and @freedomtan to check if we can reproduce this.

**Comment by kcwu** [comment]
@freedomtan  are you using the apk generated by `make docker/flutter/android/apk` ?

**Comment by freedomtan** [comment]
nope, docker is slow on my old machines :-)
simply 
```
$ make WITH_MEDIATEK=1 WITH_PIXEL=1
$ cd flutter
$ flutter run
```

**Comment by kcwu** [comment]
Ah, sorry, it's my mistake. In the past (android version), backends are created for each benchmark. Now backends are created when app started and I missed the log messages.
