### ISSUE TITLE
Progress screen with `cool down` enabled is confusing

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#416]
With cool down enabled, the step count includes the cool down phase, so with 5 tasks running, it shows 9 steps in total with +4 steps for cool down phases in between.
In the current UI, the user may think the number represent the task count only, so we need either:
1. Count only the number of tasks to be run, or
2. Count the number of tasks to be run + cool down phase but change the UI to make it more obvious.

![2022-06-30 at 15 30 32 Medium](https://user-images.githubusercontent.com/85728587/176635461-45f14794-d1a9-4452-bec9-7665bd145b2e.jpeg)

**Comment by freedomtan** [comment]
Let's remove cooldown steps. @d-uzlov

**Comment by mohitmundhragithub** [comment]
I synced the build and ran on a device, and realised that "stage progress" telling the amount of time left for cooldown is a good thing to have. So, when we remove the number, probably, we should keep the cooldown progress %ge as it is now.

**Comment by anhappdev** [comment]
Ideally, the `Stage progress: x%` will become a count-down timer like `Cool down: x seconds left`.
