### ISSUE TITLE
App may read an old, not up-to-date configuration file

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#420]
Currently, the app read the path for the default task file from a user editable `json` file stored on the device (see https://github.com/mlcommons/mobile_app_open/blob/master/flutter/documentation/custom-tasks.md)

We have updated the path to the default task file several times, but if the user has an existed configuration file, the app will not create a new configuration file and the new path will not be used.

**Comment by anhappdev** [comment]
Sorry, the app already handle this case.

**Comment by AhmedTElthakeb** [comment]
I updated the json file with custom tasks file, and tried to switch to the other file from the app settings but it says "Path to config is invalid"

`{
  "default": "asset://assets/tasks.pbtxt",
  "otherName": "app:///tasks.pbtxt"
}`

I copied the file to the following location on the phone.
This PC\Galaxy S22 Ultra\Internal storage\Android\data\org.mlcommons.android.mlperfbench\files

I am using this file 
https://raw.githubusercontent.com/mlcommons/mobile_app_open/master/flutter/assets/tasks.pbtxt

**Comment by AhmedTElthakeb** [comment]
I previously had a similar issue (missing IS benchmark) in the android app, but that was a result of mismatch of the benchmark_id between what is defined in the app tasks file and what is defined in our backend settings. After unifying both, the benchmark was recognized fine. 

Currently the tasks file declares the model as follows 
`  model {
    id: "IS_uint8_mosaic"
    name: "MOSAIC Uint8"
    tags: "uint8"
    max_throughput: 2000
    num_classes: 31
    image_width: 512
    image_height: 512
  }`

And in our backend settings, we declare as follows
`benchmark_setting {
  benchmark_id: "IS_uint8_mosaic"
  accelerator: "samsung npu"
  accelerator_desc: "NPU"
  configuration: "Samsung Exynos"
  custom_setting {
    id: "mode"
    value: "3"
  }`

I am not sure why it is not picked up properly !
