### ISSUE TITLE
Deal with removal of LoadGen's ReportLatencyResults method 

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#439]
[removal of LoadGen's ReportLatencyResults](https://github.com/mlcommons/inference/commit/a8a43dcf2ce9f795be637f3126250c1cfa0d736e) caused a problem in this app. For v2.1 submission, we use a patch to revert this change. We need a cleaner solution in the long run.

cf. @d-uzlov's comment's in https://github.com/mlcommons/mobile_app_open/pull/436

**Comment by d-uzlov** [comment]
I don't see a way to get some of the data we use without ReportLatencyResults.
I created an issue in the loadgen repo: https://github.com/mlcommons/mobile_app_open/issues/439
