### ISSUE TITLE
New 2.0 Android apk fail to run on unsupported POCO F3..

### ISSUE THREAD

**Issue by oscarbg** [mlcommons/mobile_app_open#442]
Hi,
previous 1.0 version runned OK..
but now 2.0 fails to run citing unsupported device..
F3 uses Adreno 650 which is fairly recent qcom gpu.. I’m on Android 12.. can you you elaborate if there is a elaborated/manual list of supported devices or gpus or even driver versions..
Would be nice if this error is noted as warning but benchmark is allowed to run even if runs into a crash or hang..
Thanks..

**Comment by freedomtan** [comment]
@mohitmundhragithub Could you help on this?

**Comment by mohitmundhragithub** [comment]
Poco F3 has snapdragon 870, which is currently not supported. 
I can check more internally if the support can be added or not.

Meanwhile, can you please share adb logcat logs on the device?

**Comment by freedomtan** [comment]
@mohitmundhragithub will check if we can support POCO F3 easily

**Comment by mohitmundhragithub** [comment]
@oscarbg, can you please share the logcat logs?
