### ISSUE TITLE
Create unified APK for submission-v2.1

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#444]
To provide the unified APK built from https://github.com/mlcommons/mobile_app_open/tree/submission-v2.1
As requested by @AhmedTElthakeb and @Mostelk.

**Comment by anhappdev** [comment]
@AhmedTElthakeb @Mostelk 
Should the paths of .so files be the same in `BUILD` and `samsung_backend.mk`?
Currently, one is `samsung_backend/lib/` and the other is `/samsung/lib/`. Please check it.

https://github.com/mlcommons/mobile_app_open/blob/c2d3b460627958bec6211789836a097ebd236437/mobile_back_samsung/BUILD#L13-L24

https://github.com/mlcommons/mobile_app_open/blob/c2d3b460627958bec6211789836a097ebd236437/mobile_back_samsung/samsung_backend.mk#L19-L34

**Comment by freedomtan** [comment]
@Mostelk to help check .so files.

**Comment by AhmedTElthakeb** [comment]
@anhappdev 
This won't matter as long as you build with docker. But I will unify the names and push.

**Comment by AhmedTElthakeb** [comment]
It seems I cannot push here. so you can just:
1) Rename the mobile_back_samsung/samsung to mobile_back_samsung/samsung_backend
2) Edit mobile_back_samsung/samsung_backend.mk as follow.
`diff --git a/mobile_back_samsung/samsung_backend.mk b/mobile_back_samsung/samsung_backend.mk
index eb8ba6c..4ef75cd 100644
--- a/mobile_back_samsung/samsung_backend.mk
+++ b/mobile_back_samsung/samsung_backend.mk
@@ -16,7 +16,7 @@
 ifeq (${WITH_SAMSUNG},1)
   $(info WITH_SAMSUNG=1)
 
-  MOBILE_BACK_SAMSUNG_LIB_ROOT=$(shell echo mobile_back_samsung/samsung/lib* | awk '{print $$NF}')
+  MOBILE_BACK_SAMSUNG_LIB_ROOT=$(shell echo mobile_back_samsung/samsung_backend/lib* | awk '{print $$NF}')
   $(info MOBILE_BACK_SAMSUNG_LIB_ROOT=${MOBILE_BACK_SAMSUNG_LIB_ROOT})
 
   backend_samsung_android_files= \
@@ -29,7 +29,7 @@ ifeq (${WITH_SAMSUNG},1)
     ${MOBILE_BACK_SAMSUNG_LIB_ROOT}/libeden_nn_on_system.so \
   # main binaries for Samsung backend are prebuilt
   backend_samsung_android_target= \
-    //mobile_back_samsung/samsung/lib:libsamsungbackend.so \
+    //mobile_back_samsung/samsung_backend/lib:libsamsungbackend.so \
`

**Comment by anhappdev** [comment]
@AhmedTElthakeb The submission branch is protected, you can create a PR to update the `submission-v2.1` if you like, 
or just apply this patch to your development branch.
<details>
  <summary>Click to show the patch!</summary>

```
diff --git a/mobile_back_samsung/samsung_backend.mk b/mobile_back_samsung/samsung_backend.mk
index eb8ba6c..4ef75cd 100644
--- a/mobile_back_samsung/samsung_backend.mk
+++ b/mobile_back_samsung/samsung_backend.mk
@@ -16,7 +16,7 @@
 ifeq (${WITH_SAMSUNG},1)
   $(info WITH_SAMSUNG=1)
 
-  MOBILE_BACK_SAMSUNG_LIB_ROOT=$(shell echo mobile_back_samsung/samsung/lib* | awk '{print $$NF}')
+  MOBILE_BACK_SAMSUNG_LIB_ROOT=$(shell echo mobile_back_samsung/samsung_backend/lib* | awk '{print $$NF}')
   $(info MOBILE_BACK_SAMSUNG_LIB_ROOT=${MOBILE_BACK_SAMSUNG_LIB_ROOT})
 
   backend_samsung_android_files= \
@@ -29,7 +29,7 @@ ifeq (${WITH_SAMSUNG},1)
     ${MOBILE_BACK_SAMSUNG_LIB_ROOT}/libeden_nn_on_system.so \
   # main binaries for Samsung backend are prebuilt
   backend_samsung_android_target= \
-    //mobile_back_samsung/samsung/lib:libsamsungbackend.so \
+    //mobile_back_samsung/samsung_backend/lib:libsamsungbackend.so \
     //flutter/android/commonlibs:commonlibs
   backend_samsung_filename=libsamsungbackend
 endif
diff --git a/mobile_back_samsung/samsung/README.md b/mobile_back_samsung/samsung_backend/README.md
similarity index 100%
rename from mobile_back_samsung/samsung/README.md
rename to mobile_back_samsung/samsung_backend/README.md
diff --git a/mobile_back_samsung/samsung/lib/BUILD b/mobile_back_samsung/samsung_backend/lib/BUILD
similarity index 100%
rename from mobile_back_samsung/samsung/lib/BUILD
rename to mobile_back_samsung/samsung_backend/lib/BUILD
diff --git a/mobile_back_samsung/samsung/lib/backend_c.h b/mobile_back_samsung/samsung_backend/lib/backend_c.h
similarity index 100%
rename from mobile_back_samsung/samsung/lib/backend_c.h
rename to mobile_back_samsung/samsung_backend/lib/backend_c.h
diff --git a/mobile_back_samsung/samsung/lib/sbe_config.hpp b/mobile_back_samsung/samsung_backend/lib/sbe_config.hpp
similarity index 100%
rename from mobile_back_samsung/samsung/lib/sbe_config.hpp
rename to mobile_back_samsung/samsung_backend/lib/sbe_config.hpp
diff --git a/mobile_back_samsung/samsung/lib/sbe_core.cc b/mobile_back_samsung/samsung_backend/lib/sbe_core.cc
similarity index 100%
rename from mobile_back_samsung/samsung/lib/sbe_core.cc
rename to mobile_back_samsung/samsung_backend/lib/sbe_core.cc
diff --git a/mobile_back_samsung/samsung/lib/sbe_core.hpp b/mobile_back_samsung/samsung_backend/lib/sbe_core.hpp
similarity index 100%
rename from mobile_back_samsung/samsung/lib/sbe_core.hpp
rename to mobile_back_samsung/samsung_backend/lib/sbe_core.hpp
diff --git a/mobile_back_samsung/samsung/lib/sbe_helper.cc b/mobile_back_samsung/samsung_backend/lib/sbe_helper.cc
similarity index 100%
rename from mobile_back_samsung/samsung/lib/sbe_helper.cc
rename to mobile_back_samsung/samsung_backend/lib/sbe_helper.cc
diff --git a/mobile_back_samsung/samsung/lib/sbe_helper.hpp b/mobile_back_samsung/samsung_backend/lib/sbe_helper.hpp
similarity index 100%
rename from mobile_back_samsung/samsung/lib/sbe_helper.hpp
rename to mobile_back_samsung/samsung_backend/lib/sbe_helper.hpp
diff --git a/mobile_back_samsung/samsung/lib/sbe_loader.hpp b/mobile_back_samsung/samsung_backend/lib/sbe_loader.hpp
similarity index 100%
rename from mobile_back_samsung/samsung/lib/sbe_loader.hpp
rename to mobile_back_samsung/samsung_backend/lib/sbe_loader.hpp
diff --git a/mobile_back_samsung/samsung/lib/sbe_model_container.hpp b/mobile_back_samsung/samsung_backend/lib/sbe_model_container.hpp
similarity index 100%
rename from mobile_back_samsung/samsung/lib/sbe_model_container.hpp
rename to mobile_back_samsung/samsung_backend/lib/sbe_model_container.hpp
diff --git a/mobile_back_samsung/samsung/lib/sbe_utils.hpp b/mobile_back_samsung/samsung_backend/lib/sbe_utils.hpp
similarity index 100%
rename from mobile_back_samsung/samsung/lib/sbe_utils.hpp
rename to mobile_back_samsung/samsung_backend/lib/sbe_utils.hpp
diff --git a/mobile_back_samsung/samsung/lib/type.h b/mobile_back_samsung/samsung_backend/lib/type.h
similarity index 100%
rename from mobile_back_samsung/samsung/lib/type.h
rename to mobile_back_samsung/samsung_backend/lib/type.h
```
</details>

**Comment by anhappdev** [comment]
Here is the Flutter APK, built with the latest commit (https://github.com/mlcommons/mobile_app_open/commit/fb04b9880424397e6c6909a8731b530532524c41) on the `submission-v2.1` branch:

[mlperfbench-fb04b98-qsmgt.apk](https://drive.google.com/file/d/1OCwoxXbf0PX9zBpAgZ4XRoJgSIkdb1BA/view?usp=sharing)

Notes:
* Built with:
```
make docker/flutter/android/apk \
    WITH_QTI=1 WITH_SAMSUNG=1 WITH_MEDIATEK=1 WITH_PIXEL=1 WITH_TFLITE=1 \
    SNPE_SDK=/root/snpe-1.59.1.3230
```
* Samsung `*.so` files copied from https://github.com/mlcommons/mobile_back_samsung/tree/merge-submission-v2.0-into-master_samsung-backend/mobile_back_samsung/samsung/lib (commit https://github.com/mlcommons/mobile_back_samsung/commit/a061e07c90257c00845d77fe35f1b191e2c77ad8)

**Comment by anhappdev** [comment]
I have feedback from Samsung that the app crashed with `Exception: dart_ffi_backend_match result: nullptr` error.
Further debugging shows that QTI backend prevents the app trying next available backends.

**Comment by freedomtan** [comment]
> I have feedback from Samsung that the app crashed with `Exception: dart_ffi_backend_match result: nullptr` error. Further debugging shows that QTI backend prevents the app trying next available backends.

@mohitmundhragithub please help verify if that's caused QTI backend

**Comment by d-uzlov** [comment]
> the app crashed with `Exception: dart_ffi_backend_match result: nullptr` error

This happens when a backend can't be loaded into memory.
If I remember correctly, QTI backend requires some Qualcomm-specific libraries which are not present on devices with SOCs from other vendors.

The app should just ignore this error instead of crashing.

**Comment by anhappdev** [comment]
The new APK: [mlperfbench-f812aa1-qsmgt.apk](https://drive.google.com/file/d/1cim1mFtwyiUh0cvS1OYnPsne8evEMoXW/view?usp=sharing)
and the PR to reflect the changes: https://github.com/mlcommons/mobile_app_open/pull/448

**Comment by mohitmundhragithub** [comment]
> 

This latest apk works fine for Qualcomm.

**Comment by mohitmundhragithub** [comment]
> The new APK: [mlperfbench-f812aa1-qsmgt.apk](https://drive.google.com/file/d/1cim1mFtwyiUh0cvS1OYnPsne8evEMoXW/view?usp=sharing) and the PR to reflect the changes: #448

This latest apk works fine for Qualcomm.

**Comment by mohitmundhragithub** [comment]
can the log collection switch in settings be made default?

**Comment by freedomtan** [comment]
> mlperfbench-f812aa1-qsmgt.apk

al

> > The new APK: [mlperfbench-f812aa1-qsmgt.apk](https://drive.google.com/file/d/1cim1mFtwyiUh0cvS1OYnPsne8evEMoXW/view?usp=sharing) and the PR to reflect the changes: #448
> 
> This latest apk works fine for Qualcomm.

also works for a MediaTek internal phone, which means backend checking works and TFLite Neuron backend is picked on the device.

Thanks @anhappdev and @d-uzlov

**Comment by freedomtan** [comment]
@AhmedTElthakeb please help check if [mlperfbench-f812aa1-qsmgt.apk](https://drive.google.com/file/d/1cim1mFtwyiUh0cvS1OYnPsne8evEMoXW/view?usp=sharing) works as expected

**Comment by AhmedTElthakeb** [comment]
Works fine for Samsung!

**Comment by kcwu** [comment]
mlperfbench-f812aa1-qsmgt.apk works as expected on Google devices.

**Comment by freedomtan** [comment]
Since it's done. Let's close this.

**Comment by Mostelk** [comment]
@anhappdev We discussed in Policy meeting to release a v2.0 Flutter App based on above without the brown screen showing "Unverified Results", since all backend above are audited in MLPerf v2.0

**Comment by anhappdev** [comment]
Ok, here is the build with official UI:
[mlperfbench-22d6252-qsmgt-official.apk](https://drive.google.com/file/d/1LgjI9ONJGHuJYXjjsXW_bKKsjTkRPfsz/view?usp=sharing)

**Comment by freedomtan** [comment]
close this for now since it's one.

This is v2.1 submission branch based apk.
