### ISSUE TITLE
Random seed question

### ISSUE THREAD

**Issue by mkankana** [mlcommons/mobile_app_open#458]
I have reverted back to commit "5dd9ed739cc8dfeae2c5d30ec06f4cb524a4dd74" on https://github.com/mlcommons/inference

```
git clone https://github.com/mlcommons/inference.git
git checkout 5dd9ed739cc8dfeae2c5d30ec06f4cb524a4dd74
```
However the random seed associated with this commit doesn't have "UL" at the end . Is it required to have those 2 letters at the end.
This is a question for non app based submissions.

Ramdom seed in git clone https://github.com/mlcommons/inference.git at commit 5dd9ed739cc8dfeae2c5d30ec06f4cb524a4dd74

```
# 0xc63bb0c8c280fdef
*.*.qsl_rng_seed = 14284205019438841327
# 0x39c9343412051148
*.*.sample_index_rng_seed = 4163916728725999944
# 0x04267cf482328355
*.*.schedule_rng_seed = 2990638148649296214
```

Random seed in [mobile_app_open 2.1 branch](https://github.com/mlcommons/mobile_app_open/blob/submission-v2.1/flutter/cpp/mlperf_driver.cc#L98) 
```
mlperf_settings.qsl_rng_seed = 14284205019438841327UL;
mlperf_settings.sample_index_rng_seed = 4163916728725999944UL;
mlperf_settings.schedule_rng_seed = 299063814864929621UL;

```

**Comment by d-uzlov** [comment]
This suffix is not part of the random seed.
The seed is an integer number.
`UL` is the C/C++ syntax for specifying value type, which sometimes helps type safety. You can ignore it.

**Comment by mkankana** [comment]
Thanks @d-uzlov
