### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#467]
Currently, we had only one integration test, which launches the app and run all benchmarks with test dataset.
We should also add unit tests, and maybe some more integrations tests.

**Comment by anhappdev** [comment]
@d-uzlov The unit tests should be gradually added. So I think we should add a new unit test with each new PR when working on a certain code part.

**Comment by d-uzlov** [comment]
Related issue:
* https://github.com/mlcommons/mobile_app_open/issues/485

**Comment by d-uzlov** [comment]
> So I think we should add a new unit test with each new PR when working on a certain code part.

Unit tests require that the code consists of separable units.
Our current code does not satisfy this requirement.

It's possible to write new code in such a way that it is testable, and add tests along with the new code itself.
But if we work on something in the old code we most likely won't be able to write tests for it.
To write tests for old code we first need to refactor it.

**Comment by anhappdev** [comment]
Yes, we will not be able to write test for all parts of the app. A big refactoring now is not a good idea either. The point is we should have tests so let try to add tests `gradually` where it's possible.

**Comment by freedomtan** [comment]
We are making progress. We'll add more unit tests incrementally. Close this for now.
