### ISSUE TITLE
Fix Jenkins jobs in mobile_app_open to build app with backends

### ISSUE THREAD

**Issue by bellycat77** [mlcommons/mobile_app_open#47]

**Comment by bellycat77** [comment]
Manual-startable Jenkins job https://mlperf.xored.com/job/mobile_app_open/job/ManuallyBuildBranch was updated to build the app with backends support (need to merge PR #43 for Samsung backend support)

**Comment by bellycat77** [comment]
The Jenkins job builds the application with backends support.

**Comment by bellycat77** [comment]
@relja128 Can we close the issue? Does job work as expected

**Comment by relja128** [comment]
@bellycat77 - please create apks with backends and put them up on google drive for us to test

**Comment by bellycat77** [comment]
The new APK is here:
https://drive.google.com/file/d/1zoe9BUPLAer5V87Oj14V9n1DmqqqQb4J/view?usp=sharing

**Comment by bellycat77** [comment]
The APK https://drive.google.com/file/d/1qnt25Y90Sd5qZl6yOEKGBBBquu2YBDoq/view?usp=sharing with updated loadgen version

**Comment by relja128** [comment]
Looks like the autobuild works fine. Closing.
