### ISSUE TITLE
Remove human-readable values from backend settings

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#476]
Human-readable values are part of GUI so they should not be defined by backends.

Currently we have the following values:

 - `accelerator_desc`
 - `configuration`

https://github.com/mlcommons/mobile_app_open/blob/29cb9deb341709cee764325ea8e568ae0f8df892/flutter/cpp/proto/backend_setting.proto#L46-L49

We should create `id → description` map and only use ids in backend settings.

**Comment by freedomtan** [comment]
it seems moving all the mapping and name into a centralized list or map in high-level UI is no flexible. Let's close this for now.
