### ISSUE TITLE
Meaning of `configuration` in backend settings

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#477]
We have `configuration` field defined for each benchmark.

https://github.com/mlcommons/mobile_app_open/blob/29cb9deb341709cee764325ea8e568ae0f8df892/flutter/cpp/proto/backend_setting.proto#L48-L49 https://github.com/mlcommons/mobile_app_open/blob/29cb9deb341709cee764325ea8e568ae0f8df892/mobile_back_tflite/cpp/backend_tflite/tflite_settings_apple.h#L36 https://github.com/mlcommons/mobile_app_open/blob/29cb9deb341709cee764325ea8e568ae0f8df892/mobile_back_samsung/samsung/lib/sbe_config.hpp#L34 https://github.com/mlcommons/mobile_app_open/blob/29cb9deb341709cee764325ea8e568ae0f8df892/mobile_back_qti/cpp/backend_qti/qti_settings.h#L36 https://github.com/mlcommons/mobile_app_open/blob/29cb9deb341709cee764325ea8e568ae0f8df892/mobile_back_apple/cpp/backend_coreml/coreml_settings.h#L27

What does this value actually mean? I can't really infer it from current config files, each backend uses it for different things.
Is it supposed to name underlying machine learning framework?

**Comment by freedomtan** [comment]
is this for underlying accelerator configurations we discussed before?

**Comment by freedomtan** [comment]
This is kinda what Qualcomm colleagues use to display the "backend" to use (sometime it's TFLite + GPU delegate, not always SNPE).

**Comment by d-uzlov** [comment]
I'll create a PR to update documentation about this field.
