### ISSUE TITLE
Add automated code check to CI

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#488]
We should integrate this repo with a tool / service to auto check for code quality and code security.

This one is free for open-source project:
https://sonarcloud.io

If anyone has experience with other tools, please share.

**Comment by freedomtan** [comment]
@anhappdev please try to see it works for our current codebase without causing too many troubles, such as false-alarms.

**Comment by anhappdev** [comment]
I tested the SonarScanner on this code base. In general, I think we can use it for code analysis and focus on new code, new commits only.

Here is an example warning in the dashboard.
<img width="1518" alt="Screenshot 2022-09-05 at 14 24 21" src="https://user-images.githubusercontent.com/85728587/188392020-160d361e-9a2b-4b88-9b55-1be564a6cf12.png">

It may not detect all issue, but some red warnings is plausible, so we should fix it.

The SonarScanner currently connected to my account, we can create an organization account for this repo.
