### ISSUE TITLE
Change default time unit from `milliseconds` to `seconds`

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#489]
In the config we use values of the order of seconds. It would be easier to read if we remove redundant `000`.
We can use floating point values to keep high precision.
https://github.com/mlcommons/mobile_app_open/blob/a67fb3125ff92cb1dca5b0b5cbf28eb90b482010/flutter/assets/tasks.pbtxt#L5
```yaml
min_duration: 60.0
```

Regarding local variables and JSON results there is no meaningful difference between seconds and milliseconds for the program.
But milliseconds require additional constant for many arithmetic operations which makes it harder to maintain.

Also `second` is the main time unit in the SI unit system.

Depends on:
* https://github.com/mlcommons/mobile_app_open/pull/484

**Comment by anhappdev** [comment]
I think second is not precise enough for this `benchmarking` app. To convert between unit of time, there should be a built-in tool in each language, for example in Dart there is a [Duration class](https://api.dart.dev/stable/1.24.2/dart-core/Duration-class.html).

**Comment by d-uzlov** [comment]
`second` pecision is absolutely enough for any of our needs in the UI part of the app, because we can use `float64`/`double` datatype for it. Well, we already use it in most places.
In fact, it will be even more precise than what we currently use in the app config, for example.
The only thing that needs the best possible precision is the benchmarking itself, which is done by the loadgen and is completely isolated from the UI part of the app.

>To convert between unit of time, there should be a built-in tool in each language, for example in Dart there is a [Duration class](https://api.dart.dev/stable/1.24.2/dart-core/Duration-class.html).

Thank you, I'm much aware of that class and I don't see how it helps in our case.
If anything, `Duration` is not built for precision. Its methods return integer values, which ruins any precision.

Which option is simpler, easier to read and maintain?
1. `1 / latency`
2. `Duration.millisecondsInSecond / latencyMs`
3. `Duration.microsecondsPerSecond / Duration(milliseconds: latencyMs).inMicroseconds`
    * because `Duration.inSeconds` returns `int` value, which is certainly not precise enough, just like you pointed out.
    * `Duration(milliseconds: latencyMs).inMilliseconds` is also much less precise than using plain millis with float datatype.

And also compare:
1. `min_duration: 60`
2. `min_duration_ms: 60000` ← how many zeroes are there? Looks like 5. Or is it 6? Oh, no, it's actually 4...

As I have already noticed in the issue body, it doesn't make a real difference **_in the UI part of the app_**. It's just a stylistic choice, and I don't see much appeal in using milliseconds.

**Comment by d-uzlov** [comment]
The real issue with seconds is when we want to show values of the order of single milliseconds. E.g., `mean latency is 2.6 ms`.
But we don't really use such things anywhere in the app.

Or if we want to get user input with values or order of milliseconds: `min_duration_ms: 10`.
We also don't use such values. It's too short.
We do use small values in backend configs, for `single_stream_expected_latency_ns`. But it's a part of loadgen config, so it isn't affected by this proposal.

**Comment by d-uzlov** [comment]
>The real issue with seconds is when we want to show values of the order of single milliseconds

And even if we ever want to show something like this, we can still do it.
I don't propose that we completely ban milliseconds from the app, I just suggest that we only use it where we really need them.

**Comment by d-uzlov** [comment]
> What I propose here is just removing one unneeded constant.

It's not like anything would significantly change.

We already use floating point arithmetic, and its precision is good enough for us.

Currently we use range `1 ms` to `1000000 ms`, after switching to seconds we will use range `0.001 s` to `1000 s`.
Both ranges are fine, they are far from `double` limits where precision could be noticeable. If anything, new range is better because it's close to `1.0`.

There are no potential issues with precision.
There are only issues with readability and unneeded constants in calculations.

**Comment by freedomtan** [comment]
changing the time unit to seconds should be fine as long as we don't require to change vendor backend interface.
