### ISSUE TITLE
Add filtering by backend to online screen

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#506]
Parent issue:
* https://github.com/mlcommons/mobile_app_open/issues/490

Depends on:
* https://github.com/mlcommons/mobile_app_open/issues/505

User should be able to search for results from one or more specific backends.

### Open question

Should we count tflite backend as one backend or create a separate search entry for each OS?

**Comment by anhappdev** [comment]
Closing this in favor of https://github.com/mlcommons/mobile_app_open/issues/641
