### ISSUE TITLE
Save CPU model in result

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#508]
Currently we save very limited info about app environment: os type, os version, manufacturer, model id.
We should at least also save CPU model.

**Comment by d-uzlov** [comment]
It seems there is no well defined API to get phone SoC on Android.
I see the following possible solutions:
1. Use [cpuinfo](https://github.com/pytorch/cpuinfo) library
This library is OK for Windows and Apple but when I checked it on Android it failed on more than half of devices that I tested.
2. Read `getprop`
    * Currently I see that `ro.soc.model` is available on _some_ of the Samsung and Google devices. I didn't test other vendors.
3. Decode android's `board` value.
There is a handy [collection](https://github.com/xTheEc0/Android-Device-Hardware-Specs-Database) of `board → SoC` pairs with MIT license.

I propose we use all of them.

Decoding `board` should work in most cases.
However, since the list of known `board` values is maintained manually, it may not work for new or rare devices (we can obviously update it if we encounter such devices).

**Comment by anhappdev** [comment]
I am not sure that we should try to get hardware information in this app.
* First it's not easy to get it right as @d-uzlov has tried
* Second we already store device model code, which should be enough to look up in an online DB which hardware it has (e.g. [gsmarena.com](https://www.gsmarena.com/makers.php3))

**Comment by d-uzlov** [comment]
> * Second we already store device model code, which should be enough to look up in an online DB which hardware it has

There are still reasons to have hardware information in the app:

1. Windows devices don't have any model info
2. It is required to filter online results by hardware. Though, it will probably require more effort than I have originally thought.

We can discuss if this is important to us in the next weekly meeting.

**Comment by anhappdev** [comment]
> filter online results by hardware

If hardware here means device model code / name than we already have it. If it means hardware component like CPU (what this PR is about) than yes we really need to discuss if it's important to have it in this app.

**Comment by d-uzlov** [comment]
Here's an APK with this change:
https://drive.google.com/file/d/1XszBq3R2X1qSnh9JcF32bDz66uovCu00/view?usp=sharing
You can see if it works correctly on your device if you run the benchmark and look at the "Device SoC/CPU name" field in the result history.

**Comment by freedomtan** [comment]
@freedomtan to test this apk on some MediaTek devices and on Pixel 4.

it would be great if we can test the app on other devices, @AhmedTElthakeb, @mohitmundhragithub, @ptt2panda

**Comment by ptt2panda** [comment]
@kcwu

**Comment by kcwu** [comment]
The apk works on Pixel 6 and 7. I saw the original soc name on Pixel 7 and the decoded soc name on Pixel 6.

**Comment by freedomtan** [comment]
- [ ] Google| tested on Pixel 6 and 7
- [ ] MediaTek: tested on some internal devices, Android property `ro.soc.model` is correctly reported
- [ ] Qualcomm: 
- [ ] Samsung:

**Comment by AhmedTElthakeb** [comment]
The apk shows device soc/cpu name okay on samsung S21+ and S22+

**Comment by mohitmundhragithub** [comment]
The device name showing up for Qualcomm is same as what is shown in adb shell. Not sure if this name will be useful for showing the results. 
e.g. For SD8PG1, it will show "Taro" as the CPU name. This name will be different for different devices.

**Comment by freedomtan** [comment]
For Pixel 4,

<img src="https://user-images.githubusercontent.com/3395998/195236136-83ebb852-a5ce-44d1-b899-80bb71b41332.png" data-canonical-src="https://user-images.githubusercontent.com/3395998/195236136-83ebb852-a5ce-44d1-b899-80bb71b41332.png" width="200" />

**Comment by mohitmundhragithub** [comment]
Can you share the database please? Is it in our repo somewhere?

**Comment by d-uzlov** [comment]
> Can you share the database please? Is it in our repo somewhere?

https://github.com/mlcommons/mobile_app_open/tree/86a98812ac602bb687297bd666a97552b9c95717/flutter/assets/android-boards
