### ISSUE TITLE
Update app version

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#526]
In TestFlight, the latest build is currently distributed as v2.0.0. 
1. Should we update the iOS app to 2.1 or 3.0?
2. And also update the Flutter Android app version in the master branch to have both iOS and Android with the same version?

FYI: @mkankana, @freedomtan, @willc2010

**Comment by freedomtan** [comment]
I'll go for something like 2.1.x. And may be we can create a 2.1.x branch for integrating 2.1 submission and the Core ML backend.
