### ISSUE TITLE
Make field name in BenchmarkSetting less confusing

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#540]
Currently:
1. The `configuration` field is used to describe the ML framework (the software).
2. The `accelerator` field is sometime used to describe the framework (the software) and sometime the hardware.
3. The `accelerator_desc` field has mostly the same value as in `accelerator`.

This caused confusing in many places, so I propose the following changes:
1. Rename  `configuration` field to `framework` to describe the software used.
2. Update the `accelerator` field to describe only the hardware used.
3. Remove the `accelerator_desc` field since it mostly has the same value as in `accelerator` field.

https://github.com/mlcommons/mobile_app_open/blob/775ab8b240b0cecbec575c332372395975ce27c8/flutter/cpp/proto/backend_setting.proto#L36-L55

**Comment by freedomtan** [comment]
Let's all try to make the `accelerator_desc` fields of backend configurations more descriptive. 

@freedomtan, @AhmedTElthakeb, @ptt2panda, @mohitmundhragithub

**Comment by anhappdev** [comment]
Please just comment the new text for `accelerator_desc` here in this issue first. 
We can discuss later where should we put those texts (in the `BenchmarkSetting` or in the localized strings of the app)

**Comment by anhappdev** [comment]
Since we are all agreed in the meeting that `configuration` should be changed to `framework`, I created PRs for it first, other fields will be updated after discussion.
