### ISSUE TITLE
Add filtering by device model

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#543]
We should add the ability to show all results from a specific device model.
It's a firebase limitation that you can't search for several values at once.

---

Depends on:
* https://github.com/mlcommons/mobile_app_open/issues/542

Parent issue:
* https://github.com/mlcommons/mobile_app_open/issues/490

**Comment by anhappdev** [comment]
Closing this in favor of https://github.com/mlcommons/mobile_app_open/issues/641
