### ISSUE TITLE
Add sorting results by task throughput

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#545]
Depends on:
* https://github.com/mlcommons/mobile_app_open/issues/544

User should be able to select sorting by certain task throughput in descending order.

List of allowed tasks should be predetermined.

**Comment by RSMNYS** [comment]
@anhappdev  can you please add more details here. What tasks are meant here?

**Comment by anhappdev** [comment]
I am not sure what the OP really means either.
Maybe you can just sort the results by average throughput.
https://github.com/mlcommons/mobile_app_open/blob/e26ae66d7ee5620364524db301d304aa2f701f28/flutter/lib/ui/history/result_details_screen.dart#L42

**Comment by freedomtan** [comment]
Let's discuss what avg to use in the working group meeting. Let's sort by individual task first.

**Comment by RSMNYS** [comment]
@freedomtan can you elaborate more on this, please? On the results screen we have the list of the past tests. Each include benchmarks list that were tested. What is considered here as a single task? What are you expecting to see when you choose the sorting by task?

**Comment by freedomtan** [comment]
> @freedomtan can you elaborate more on this, please? On the results screen we have the list of the past tests. Each include benchmarks list that were tested. What is considered here as a single task? What are you expecting to see when you choose the sorting by task?

sorry for causing confusion, by task, I mean different benchmark_id.

**Comment by anhappdev** [comment]
@RSMNYS 
For the context (see [result-spec.md](https://github.com/mlcommons/mobile_app_open/blob/027050ffbd9aac4b4a1225728ccdb1ef5af6df71/docs/result-spec.md) for more info):
* Each run (tapping on the GO button) will generate a result (what currently displayed as a list in the history screen)
* Each result has one or more benchmark-specific results
* Each benchmark-specific result has one `benchmark_id`, zero or one `accuracy_run` and zero or one `performance_run`
* Throughput is existed only in `performance_run`

That means to sort the results by throughput, you will have to:
1. Show the list of benchmark-specific results in the history screen (one level deeper than currently)
2. Show only benchmark-specific results, which has `performance_run`
3. Sort the benchmark-specific results by throughput
