### ISSUE TITLE
Add filtering by date

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#546]
User should be able to select a range of dates and view results only from this range.

There is a firebase limitation that range selection and sorting must be on the same field, so filtering by date will only be possible when we sort by date.

Parent issue:
* https://github.com/mlcommons/mobile_app_open/issues/490

**Comment by anhappdev** [comment]
Closing this in favor of https://github.com/mlcommons/mobile_app_open/issues/641
