### ISSUE TITLE
Add filtering by hardware (SoC/CPU)

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#547]
We should add an ability to show all results from devices with a certain SoC/CPU.
It's a firebase limitation that you can't search for several values at once.

We can (and probably will) encounter issues with SoC naming consistency.

---

Depends on:
* https://github.com/mlcommons/mobile_app_open/issues/508

Parent issue:
* https://github.com/mlcommons/mobile_app_open/issues/490

**Comment by anhappdev** [comment]
Closing this in favor of https://github.com/mlcommons/mobile_app_open/issues/641
