### ISSUE TITLE
Potential problem with cached files from mobile_models repo

### ISSUE THREAD

**Issue by bellycat77** [mlcommons/mobile_app_open#55]
We have a potential problem with cached files from the https://github.com/mlcommons/mobile_models repo

We have 2 files with equivalent names but different links:
https://github.com/mlcommons/mobile_models/blob/main/v0_7/tflite/mobilenet_edgetpu_224_1.0_float.tflite
https://github.com/mlcommons/mobile_models/blob/main/v1_1/tflite/mobilenet_edgetpu_224_1.0_float.tflite
The application "looks" at the filename when it checks if was the file cached or not. So if we will not remove the old application version before installing the new one, then cached files will be kept. And if the new version of the application requires a new version of the file, then it will no be uploaded, because a file with the same name is already in cache.

**Comment by relja128** [comment]
That's annoying. Can you cache by url instead? It will conveniently evict the existing files.

**Comment by d-uzlov** [comment]
> Can you cache by url instead?

Yes, this would solve this issue.

>It will conveniently evict the existing files.

Using full URL in cache will not help evicting existing files. Our current cache system (both in android and in flutter) only downloads missing files. If we no longer use the old files, they just lie in the file system until the app is uninstalled, or user manually clears the cache.

Keeping the cache clean is a different, more complicated issue.

Except for the simplest solution of using full URL in path, which doesn't help with eviction of old files, there are several solutions, which can fix the eviction issue:
1. Use full URL for paths, automatically purge cache when app is updated.
**Pros**: simple.
**Cons**: we will download all data from scratch after each update.
2. Make a more sophisticated caching system, and try to keep track of the files, to delete files that were needed previously but no longer needed in the new version.
**Cons**: complicates code, possible overhead for tracking files.
3. Use some external library to help with caching.
**Pros**: less complicated code.
**Cons**: added dependency, possibly even more overhead compared to [solution 2].

Also, our apps can use custom tasks.pbtxt files, and it's not clear what we should do with the cache for these custom files, if we plan on evicting old files.

**Comment by relja128** [comment]
Let's go with cache by url. Evict when app is updated AND files are more
than 9 months old. (Both conditions have to be true). So after the app
version changes, delete files older than 9 months.

**Comment by anhappdev** [comment]
How about using a file checksum like MD5?
The config file should have a new field storing the checksum of the ML model in the URL. The app compares the checksum of the cached file with the checksum in the config file and download the new file if they are different. The filename can still be the same to evict the existing files.

**Comment by mcharleb** [comment]
A version if this repo needs to be made public. I suggest as part of doing that we clean it up, squash history and make only the files needed for MLPerf 1.1 present, then update the mobile_app_open config to use the new version of the repo.

**Comment by mcharleb** [comment]
I always delete the old app before installing a new one. This deletes the cache. I don't think we have robust app upgradeability and this is only one part of that. I would say that we create release notes that indicate that you must remove the old app before installing a new version. We can then create an issue to support upgrading the app with all required testing to validate that.

**Comment by relja128** [comment]
Caching policy:
* Cache by URL
Eviction policy:
* On app update, evict files more than 9 months old

**Comment by anhappdev** [comment]
@mcharleb Hi Mark, since I take over this issue from Ivan. Can you review the linked PR if is there anything else to change? As I see, Ivan answered all your questions.

**Comment by mcharleb** [comment]
I'm away on vacation this week and have no computer.

**Comment by anhappdev** [comment]
Ok. I didn't know that. Enjoy your vacation.

**Comment by anhappdev** [comment]
@mcharleb Hi Mark, can you please review the linked PR?

**Comment by relja128** [comment]
@anhappdev - can you please take a look?
