### ISSUE TITLE
Retire Jenkins for CI build and test iOS

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#565]
We are now using GitHub Actions for testing iOS build (https://github.com/mlcommons/mobile_app_open/pull/559) and Xcode Cloud for deployment to TestFlight (https://github.com/mlcommons/mobile_app_open/pull/367). So the Jenkins server can now be retired.

**Comment by anhappdev** [comment]
@d-uzlov Would you take this task, since you are already familiar with the Jenkins setup?

**Comment by d-uzlov** [comment]
I guess the only thing we need to do is shut down servers.
Do you have anything else in mind?

**Comment by anhappdev** [comment]
Maybe close the billing of the unused 3rd party service if necessary.

**Comment by d-uzlov** [comment]
Ok, I'll take it.

**Comment by d-uzlov** [comment]
We have the following resources that we no longer need:

* macincloud dedicated server. Status: requested delete
* jenkins VM in GCP. Status: stopped
* jenkins VM static IP. Status: working
* jenkins DNS entry. Status: working
* jenkins github webhooks. Status: working
* jenkins github account. Status: working

Billing for macincloud is managed by MLCommons.
Jenkins resources are either part of GCP or just free for us.

I think we should leave it as is for a few days, just in case we remember about something, and later delete everything.

**Comment by manasakankanala** [comment]
@morphine00 Adding you to the thread. 
Once this issue is closed , could you please also close the billing related to this CI. @d-uzlov  has added the item list in the above comment.
Thanks

**Comment by morphine00** [comment]
I've cancelled the MacInCloud subscription today. I believe the machine itself will stay up until the billing cycle is up (3rd of each month), so we can reactive it if we forget something.

**Comment by freedomtan** [comment]
Let's keep it running till the billing cycle is up. Then we can close this.

**Comment by anhappdev** [comment]
I think it would be ok to close this now.
