### ISSUE TITLE
Move `selected backend` field in results from benchmark data to top level

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#569]
Currently we have a separate `selected backend` field for each task because supposedly backends can delegate some tasks to other backends.
However, it's invisible for the application. Application selects only one backend binary at the launch.
The only thing application can see is metadata reported by backend: `backend_name`, `vendor_name`. This metadata will still be per task.

We need `selected backend` field at top level for filtering in online results.

**Comment by anhappdev** [comment]
The `BackendReportedInfo` is deeply nested in the app structure, so moving it to top level would require plenty of refactorings.
For this reason, I added a new `FilterInfo` so we can easily add custom data for filtering purpose to this class (https://github.com/mlcommons/mobile_app_open/pull/624). This approach is more flexible and require less effort, IMO.

**Comment by anhappdev** [comment]
Closing this in favor of https://github.com/mlcommons/mobile_app_open/issues/641
