### ISSUE TITLE
Update Flutter version from v2.10 to v3.3

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#570]
We are currently using Flutter `v2.10` which was released on Feb 3, 2022. The latest version is Flutter `v3.3`, released on Aug 31, 2022. 
(see https://docs.flutter.dev/whats-new and https://docs.flutter.dev/development/tools/sdk/release-notes)

I would update the Flutter version now and not wait too long to avoid too many changes at once.

**Comment by anhappdev** [comment]
Here are some new features which are most interesting for us, IMO:

> In Flutter 3, the macOS and Linux platforms have reached stable, in addition to Windows. You can now develop your app to run on any or all of these platforms. 

> [Dart 2.18: Objective-C & Swift interop](https://medium.com/dartlang/dart-2-18-f4b3101f146c)

**Comment by freedomtan** [comment]
Let's move to v3.
