### ISSUE TITLE
Update Android compiler version

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#586]
After we updated to Flutter v3.3.5 we started getting a warning that we should update Android compiler to v33.
Updating some of the Flutter lib dependencies transforms this warning into an error.

```
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to A:\work\git\mobile_app_open\flutter\android\app\build.gradle:
android {
  compileSdkVersion 33
  ...
}
```

**Comment by freedomtan** [comment]
Let's create test apk to see if this breaks something or as expected (breaking nothing).

**Comment by anhappdev** [comment]
Per this blog post [Picking your compileSdkVersion, minSdkVersion, and targetSdkVersion](https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd#.bpqsg4ili), maybe we should also update the `targetSdkVersion` to `33`
> minSdkVersion (lowest possible) <= 
    targetSdkVersion == compileSdkVersion (latest SDK)
