### ISSUE TITLE
State of score collection

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#587]
# What we want

* In the app
  * Result uploading
  * List of online results
    * With pagination
    * With changeable sorting
    * With filtering
* On server side
  * Validate result and put it into database

# What we currently have

We have a prototype which uses Firebase services:

* Uploading is working
* Online results are available
* Pagination is missing
* Sort is missing
* We have a filtering prototype: https://github.com/mlcommons/mobile_app_open/pull/494

We know that filtering in firebase will be severely limited (see #490) due to Firebase DB, so we decided to change DB.

If we are OK with limited filtering, then it should be easy to add both filtering and sorting with pagination.
I spent some time trying to overcome Firebase limitations. If we just use what already works, it should be fast to get filtering, sorting and pagination working in our app.

# Switching to a different database

In #490 we discussed database choice.
We can use SQL service in GCP.
We can probably still use the current Firebase Functions backend for result validation, and for interactions with database.

I'm not sure how difficult it would be to implement pagination with SQL.

**Comment by anhappdev** [comment]
Closing this in favor of https://github.com/mlcommons/mobile_app_open/issues/641
