### ISSUE TITLE
add a super resolution benchmark/task

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#595]
When the dataset part (https://github.com/mlcommons/mobile_app_open/issues/558)  of super resolution is done.
- [x] dataset part, see #558 and https://github.com/mlcommons/mobile_app_open/pull/574
- [x] add super resolution for the tflite backend as a reference for other backends, d23d16c 
- [x] add corresponding code for frontend
- [x] prepare coreml model for the Core ML backend, see #558 
- [ ] add some descriptions on how to add a new task: using this super-resolution as an example

**Comment by freedomtan** [comment]
# How to Add a New Task to MLPerf Mobile App (a draft)
Steps
1. add a dataset to `flutter/cpp/datasets`. For example, 
    * add `snu_sr.{cc,h}`  and corresponding building rule(s) in `flutter/cpp/datasets/BUILD`
    * what does "a dataset" mean? A dataset here is to implement [**LoadGen**](https://github.com/mlcommons/inference/tree/master/loadgen)'s  Query Sample Library (QSL). Actually, we can share some common methods and the **MLPerfDriver** uses interface defined in [`flutter/cpp/dataset.h`](https://github.com/mlcommons/mobile_app_open/blob/master/flutter/cpp/dataset.h), all the datasets in `flutter/cpp/datasets/` now inherit the **mlperf::mobile::Dataset**.
2. add corresponding code to `flutter/cpp/binary/main.cc` so the we can test the dataset with CLI.
3. new task specific settings to backends so that accelerators could be used. E.g add setting to TFLite backend by modifiying `mobile_back_tflite/cpp/backend_tflite/tflite_settings_android.h`
4. add front end code

**Comment by anhappdev** [comment]
# How to add a new task to the Flutter frontend:

1. Add a new task to the `tasks.pbtxt` file.
2. Add a new task to Flutter code part.
3. Add a new `benchmark_setting` to the backend's settings.
4. Add an integration test for the new task.

See the PR https://github.com/mlcommons/mobile_app_open/pull/608 for an example how to add the new super resolution task.
