### ISSUE TITLE
Set proper branch name and build number meta info on Android and Windows CI

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#600]
The application has meta info of the build environment.
On CI some of the info is not set properly:
- Branch name is always the default, `master`
  - CI has access to the branch name of the pull request, so we can write it in the app meta info
- Build number is always `1`
  - We can use number of commits in the current branch as a build number

**Comment by anhappdev** [comment]
With the new workflow, the metadata is now set correctly:
* https://github.com/mlcommons/mobile_app_open/pull/842
