### ISSUE TITLE
Make mobile repo public

### ISSUE THREAD

**Issue by mcharleb** [mlcommons/mobile_app_open#61]
This should likely have squashed history limited to current models

**Comment by mcharleb** [comment]
Do you want to:

1. Create a new mobile_open repo and deprecate mobile?
2. Replace master branch with squashed version and make mobile repo public?
3. Make mobile repo public as-is?

**Comment by relja128** [comment]
Do we need this for 1.1?

**Comment by mcharleb** [comment]
I thought we needed it immediately to enable other participants. Its not
tied to 1.1

**Comment by relja128** [comment]
Makes sense. Does this impact 1.1 in any way? E.g. if we create
mobile_open, and leave mobile as-is, that should be fine, right? I would
like to keep mobile intact for now for history reasons, and we can delete
it in a year if it's not needed, similar to mobile_app.

**Comment by mcharleb** [comment]
Doesn't impact 1.1. Agree with your plan

**Comment by relja128** [comment]
Created https://github.com/mlcommons/mobile_open
