### ISSUE TITLE
SR dataset present in mobile_models contain less images

### ISSUE THREAD

**Issue by mohitmundhragithub** [mlcommons/mobile_app_open#630]
Looks like we uploaded only 20 images instead of discussed 25 for the SR dataset. Is this expected? 

input_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/datasets/snusr_lr.zip"
groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/datasets/snusr_hr.zip"

**Comment by anhappdev** [comment]
Please see https://github.com/mlcommons/mobile_models/pull/51#issue-1441368068 for more detail.

**Comment by anhappdev** [comment]
Please reopen this issue if you still have other questions.

**Comment by Mostelk** [comment]
Can we have 2 zip files on github, one for the first 20 images, one for the remaining 5 images, and unzip both to same folder? for either LR or HR images?

**Comment by anhappdev** [comment]
The app does not support that use case yet, and adding support for it is not trivial.
If we need to host big dataset, I suggest just using a service like GitHub LFS or Google Cloud Storage.

**Comment by anhappdev** [comment]
I think we can also distribute the dataset as a release.

> Each file included in a release must be under 2 GB. There is no limit on the total size of a release, nor bandwidth usage.

https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas
