### ISSUE TITLE
Change Benchmark Ordering to run All Performance Runs Then All Accuracy Runs in Submission Mode

### ISSUE THREAD

**Issue by Mostelk** [mlcommons/mobile_app_open#634]
MPerf v2.1 Flutter app is running one performance (latency) run, followed by one accuracy run in Submission Mode (for example see the time stamps here https://github.com/mlcommons/mobile_results_v2.1/blob/master/closed/Samsung/results/results.json ) 
 This can make the latency results inconsistent with Performance mode, which only runs the performance latency measurements. Please change the order to run all Performance runs, followed by all Accuracy runs in Submission mode (as in MLPerf v2.0 app).

**Comment by freedomtan** [comment]
@anhappdev will help on this.
