### ISSUE TITLE
Decimal precision for accuracy not used in display of results

### ISSUE THREAD

**Issue by Mostelk** [mlcommons/mobile_app_open#635]
The accuracy numbers are usually in % of 100, say 74.6%, now all the numbers are rounded to the nearest whole percentage and shown as 0.75 which makes the decimal point useless (since all numbers less than 1 (100%) )., for example see https://github.com/mlcommons/mobile_results_v2.1/blob/master/closed/Samsung/results/Screenshot_20220831-194257.png 

Suggestion: multiply all the numbers by 100 and display them with one decimal point only, e.g. 74.6 instead of 0.75

**Comment by freedomtan** [comment]
I am sure if multiplying all the numbers by 100 is right, e.g., we'll have super resolution (SR) in 3.0 and the unit of the accuracy for the SR is dB. We don't want to multiply a dB value by 100.

**Comment by freedomtan** [comment]
1. Let's  just increase number of digits for accuracy numbers (to have at lease 4 effective numbers). (If there is not enough space, decrease the font size?) 
2. Let's stay as is. Because we already have detailed numbers logged and in details below on the screen.

@Mostelk what's your opinion.

**Comment by Mostelk** [comment]
sounds good. 4 effective number like xx.xx or .xxxx is good. We can do it differently per task, according to the metric, accuracy or PSNR

**Comment by anhappdev** [comment]
> The accuracy numbers are usually in % of 100, say 74.6%, now all the numbers are rounded to the nearest whole percentage and shown as 0.75 which makes the decimal point useless (since all numbers less than 1 (100%) )., for example see https://github.com/mlcommons/mobile_results_v2.1/blob/master/closed/Samsung/results/Screenshot_20220831-194257.png


Instead of taking the screenshot of the overview area, can we take the screenshot of the details area for submission?

![IMG_8424 Medium](https://user-images.githubusercontent.com/85728587/201184778-e5a501f1-5082-400b-a86a-706b91e36169.jpeg)

**Comment by Mostelk** [comment]
That option is good as well, but the frontend already showing 3 digits 0.27, we can make it 27.1 instead without changing any font ( if number is less than 1 multiply it by a 100)

**Comment by freedomtan** [comment]
convert xx.yy% to xx.y instead of 0.xx for numbers on the main screen.
be specific, image classification (both stream and offline), object detection, and segmentation.

**Comment by Mostelk** [comment]
This looks good! Thanks
