### ISSUE TITLE
Allow PSNR accuracy calculation of Super Resolution task for NCHW returned result

### ISSUE THREAD

**Issue by Mostelk** [mlcommons/mobile_app_open#638]
Currently the accuracy code, reads the ground truth image in in NHWC format, assumes the returned result from backend is also NHWC format. However, some backends are designed for NCHW format. Since is first task we have a 3 channel output result, we need to add this capability during accuracy calculation either in front end, or as a callback function to the backend to reorder its output. Currently preprocesssing allows the backend to order the input https://github.com/mlcommons/mobile_app_open/blob/3576a25ba6c3e4afb5133095ad9c5d24500603b0/flutter/cpp/datasets/snu_sr.cc#L117, so backend can convert NHWC to NCHW. We need accuracy calculation to support both NCHW and NHWC formats.

**Comment by freedomtan** [comment]
Good catch. adding 
```C++
backend_->ConvertInputs(output_size_byte, image_width_, image_height_, ground_truth_vector);
```
after reading a ground truth image should be enough.

However, I don't have the environment to verify it. Could any Samsung colleague help check it. And if it works, send a PR, please.

**Comment by sb-huh** [comment]
Currently there is no way to confirm the data layout of ground truth on vendor side.
In case of handling mass input buffers such as offline, it will occur many redundant conversion of data layout on vendor backend. So I recommend to define explicit definition of data layout on front-end layer and backend owner can refer those definition when it try to conversion its layout.

**Comment by freedomtan** [comment]
Because of the TFLite preprocessing code we use right now, by default, decoded/processed input tensors are in NHWC.

**Comment by freedomtan** [comment]
@freedomtan to check if the TFLite preprocessing code for read input tensors (and ground truth) can do the conversion. (Because we do it in each dataset code). And check if there is other ways to do it (seamlessly).

**Comment by freedomtan** [comment]
Generally, there is no option to turn NHWC raw rgb image to NCHW in tflite preprocessing code [1]. However, load raw RGB code is actually quite trivial [2-3], since we are not doing any real preprocessing for ground truth images, open file stream and then read as is enough.

Anyway, I was wrong about `ProcessOutput()` for each dataset. The `ProcessOutput()` is not called part of LoadGen interface. It's our internal interface. We can modify the interface if all of us agree on what to do.
LoadGen only calls `Name(), TotalSampleCount(), etc` [4]. When output processing completes, we call `QuerySamplesComplete()` [5] to tell LoadGen that outputs are ready.

Outputs are processed then forward

[1] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/evaluation/stages/image_preprocessing_stage.cc
[2] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/evaluation/stages/image_preprocessing_stage.cc#L266-L287
[3] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/evaluation/stages/image_preprocessing_stage.cc#L62-L73
[4] https://github.com/mlcommons/inference/blob/master/loadgen/query_sample_library.h
[5] https://github.com/mlcommons/inference/blob/master/loadgen/loadgen.h

**Comment by Mostelk** [comment]
Along the same lines, how about preparing two offline  versions of the rgb8 dataset (LR,HR) one written in CHW and the other written in HWC, and based on some flag toggled by backend, we load the requested version?. This will also eliminate need to change input format. Only code changes needed will be setting the NCHW or NHWC flag?

**Comment by anhappdev** [comment]
> Along the same lines, how about preparing two offline versions of the rgb8 dataset (LR,HR) one written in CHW and the other written in HWC, and based on some flag toggled by backend, we load the requested version?.

The current task file format only supports one `groundtruth_path` per dataset.
https://github.com/mlcommons/mobile_app_open/blob/85d380f7f1128712e87c0e6f5cb3e19e1ac06551/flutter/assets/tasks.pbtxt#L189-L193

But the app supports custom task file. So if we have 2 versions for the SNUSR groundtruth, another possible solution would be that if a vendor needs to use a different `groundtruth_path`, so he can use a custom task file with different `groundtruth_path`. That would require no code change.

**Comment by Mostelk** [comment]
Thanks Ahn for the suggestion. If we have the dataset (lr, hr) read in rgb8 NCHW format uploaded to Github as well. Can the app be configured to download this NCHW version instead of NHCW version, based on the backend under test?  or otherwise if it is easier, can we configure the app to download both to some other path like
input_path: "local:///mlperf_datasets/snusr/lr_nchw" 
 groundtruth_path: "local:////mlperf_datasets/snusr/hr_nchw" and use the custom task file you mentioned above?

**Comment by mohitmundhragithub** [comment]
Another possible solution could be to ask the backend to convert the output to the required format, only during the accuracy run

https://github.com/mlcommons/mobile_app_open/blob/master/flutter/cpp/datasets/snu_sr.cc#L139

We already have the check for accuracy run in the dataset's code. So, just like the function convertInput, we can have a convertOutput function, which the backend uses to convert to the desired format during accuracy computation.

**Comment by anhappdev** [comment]
> If we have the dataset (lr, hr) read in rgb8 NCHW format uploaded to Github as well,

The full dataset is over 100 MB and therefore hit the GitHub limit.

> can the app be configured to download this NCHW version instead of NHWC version, based on the backend under test?

With a custom task file, I mean manually choose it in the app when testing a certain backend, not automatically.

--- 

Anyway, I think adding a `backend_->ConvertOutputs()` into `ProcessOutput()` as others suggested would be a better solution if we must change the code.

**Comment by anhappdev** [comment]
Per discussion:
- We remove the groundtruth_path for lite dataset, which is used in performance run.
- If a backend needs to use channel first or last images for accuracy run, he can manually copy it to the dataset folder.

**Comment by freedomtan** [comment]
it's safe to close this now
