### ISSUE TITLE
Preparing for 3.0 submission code freeze

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#640]
- [x] make sure we everybody is happy with current super resolution implementation
  * at least, we still have #638
- [x] RNG seeds, https://github.com/mlcommons/mobile_app_open/pull/651
- [x] LoadGen update, https://github.com/mlcommons/mobile_app_open/pull/651
- [x] I assume we don't need new TensorFlow version this time
- [x] changing benchmark running orders, close #634
- [x] super resolution should be run before offline? #642
- [x] https://github.com/mlcommons/mobile_app_open/issues/626
- [x] A PR to merge samsung backend 2.x changes, https://github.com/mlcommons/mobile_app_open/pull/658

**Comment by anhappdev** [comment]
I think this one is helpful to have before the code freeze
https://github.com/mlcommons/mobile_app_open/issues/626

**Comment by mohitmundhragithub** [comment]
are we still looking to update loadgen? IMHO, it might be too late for loadgen update now

**Comment by freedomtan** [comment]
LoadGen, or say, the inference repo, didn't branch out v3.0 (yet), but the random number seeds are there.

https://github.com/mlcommons/inference/commit/b1c4cb972df6f51c5f08953dcb6f8ce5d163b41e

**Comment by freedomtan** [comment]
Let's try to have this done before the group meeting this week.

**Comment by anhappdev** [comment]
In case anyone needs it, here is the unified APK built from the `submission-v3.0` branch (commit https://github.com/mlcommons/mobile_app_open/commit/25fa990b8efe62ebb2abcedc6babbe38510185d9):
[2023-02-21-mlperfbench-25fa990-qsmgt.apk](https://drive.google.com/file/d/1r-SBC9YpUuBTpYGzG50dbfJ1vxoI9f0T/view?usp=sharing)
