### ISSUE TITLE
Provide the dataset as a release

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#644]
If we distribute the dataset (or model) as a release, we have a much bigger threshold for the file size (2 GB instead of 100 MB).

> Each file included in a release must be under 2 GB. There is no limit on the total size of a release, nor bandwidth usage.

https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas

**Comment by anhappdev** [comment]
The SNUSR dataset is released as a draft here:
https://github.com/mlcommons/mobile_models/releases/tag/untagged-adb45e94db8a258b27b7

After confirming that the files are ok I will make it public.

**Comment by anhappdev** [comment]
If I should put more information in the description, please advice.

**Comment by mohitmundhragithub** [comment]
these files looks good to me.

**Comment by AhmedTElthakeb** [comment]
looks good to me!

**Comment by freedomtan** [comment]
Let's make this zip file publicly available.

**Comment by anhappdev** [comment]
Published
