### ISSUE TITLE
Groundtruth changes cause app to become unresponsive

### ISSUE THREAD

**Issue by mcharleb** [mlcommons/mobile_app_open#65]
When running in submission mode (and even enabling submission mode) the UI becomes unresponsive and the message pops up with exactly that indication asking whether to wait or close the app.

**Comment by anhappdev** [comment]
I could not reproduce this bug. I tested with the commit `64796e5e920b623e83c071637e8b54a3f3df65a6`. Enable submission mode and running in submission mode caused no problem in my test. I could not download the whole ImageNet dataset (I have no corporate email) so I used the lite dataset in https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets.

@mcharleb Can you provide more details about the bug? Which commit did you used? How big is the dataset in submission mode? What was the user actions before the bug occurred? Thanks.

**Comment by bellycat77** [comment]
I can't reproduce the issue too. I have tried to run the Submission mode with full datasets (except for Image Segmentation cause I don't have annotations for it). It works on Samsung Note 20 Ultra. The benchmarks had been finished successfully. Could you provide steps for reproducing the issue?

**Comment by relja128** [comment]
Per @Mostelk - the app is likely trying to download tflite models. Being off wifi is probably causing problems. Either way we should diagnose and fix the UI.

@bellycat77 - can you repro with a clean install and off wifi?

**Comment by bellycat77** [comment]
@relja128 @mcharleb

All scenarios are with initial installations, without full datasets available
---
**Scenario 1:**
1. WiFi is enabled
2. Application installed
3. User runs the application
4. Application downloads models
5. User **disables** WiFi
6. User enables **Submission mode** and returns to the main activity
7. Application tries to download groundtruth files

**Result 1:** application shows error "Error: No network connected"

---
**Scenario 2:**
1. WiFi is enabled
2. Application installed
3. User runs the application
4. Application downloads models
5. User **doesn't disable** WiFi
6. User enables **Submission mode** and returns to the main activity
7. Application downloads groundtruth files
8. Application checks if full datasets are presented

**Result 2:** application shows error "Dataset is unavailable <...>"

**Comment by relja128** [comment]
No repro for now.
