### ISSUE TITLE
The log directory is not accessible on few Android 11 based phones

### ISSUE THREAD

**Issue by mohitmundhragithub** [mlcommons/mobile_app_open#66]
The log directory which loadgen creates is not accessible on few Android 11 based phones. So, probably we should generate the results in some accessible location instead of using /sdcard/Android/data path.

**Comment by relja128** [comment]
Is this needed in 1.1 for submission verification?

**Comment by relja128** [comment]
Per @mcharleb - we don't need this for verification. Only shows up on Pixel, x86 / ARM emulation.
