### ISSUE TITLE
Let's see  if we can move the iOS backend to Swift

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#671]
for sergij
1. build the app for iOS devices: flutter, bazel, and other. Please check if we have documentation good enough for you build the app. 
2. check how hard it could be to move to swift.
3. try to have better CoreML models

**Comment by RSMNYS** [comment]
Hi  guys! So the classes are migrated to the Swift. Now I'm working to use those classes in C++ code. To use them I need to use the Objc-C header. Currently have some issues with Undefined Symbols, but I believe that resolve this shortly and next week I will be able to test apple backend with the Swift Part.

**Comment by RSMNYS** [comment]
Hi guys! So the migration of the ObjectiveC to Swift was relatively an easy task in comparison how to make it work altogether. And things becoming a bit cumbersome. First to use Swift in C++ we still need to use ObjectiveC headers. It's fine as the Xcode generates the interface automatically, and we can include it. However when using bazel we need to use bazel's swift_library rule to build the package. And even with the "generates_header" attributes set to true, the  compiler can't find that generated file, me neither. As a workaround for now I've created a separated header and put the interface there. In the end the compiler is not able to find the CoreMLExecutor class, which is defined and implemented in Swift. Working to resolve this.

**Comment by RSMNYS** [comment]
Done in https://github.com/mlcommons/mobile_app_open/pull/716
