### ISSUE TITLE
Use .pbtxt instead of .h file for backend setting

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#694]
Currently, the backend settings are defined as `string` in a header file, which will be parsed later in code.
We should use the `.pbtxt` format to store those settings and get the benefit of using an IDE to maintain it (like auto-format, style check, syntax check, etc.)

Example of a `.h` file used to store backend setting: [tflite_settings_android.h](https://github.com/mlcommons/mobile_app_open/blob/1709aaf73ebecbe00ff03ae063f382d46fd6c764/mobile_back_tflite/cpp/backend_tflite/tflite_settings_android.h)

And we should convert it to a `.pbtxt` file similar to this one: [tasks.pbtxt](https://github.com/mlcommons/mobile_app_open/blob/1709aaf73ebecbe00ff03ae063f382d46fd6c764/flutter/assets/tasks.pbtxt)

**Comment by freedomtan** [comment]
@anhappdev to create a PR for TFLite backend with sample for how to choose between different `.pbtxt` settings.
