### ISSUE TITLE
Use PNG instead of raw images 

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#695]
Current, we use jpg and raw rgb images for ADE20K and SNUSR because we didn't have PNG support.
Since we merged https://github.com/mlcommons/mobile_app_open/pull/691, it should be possible to PNG for both.

**Comment by freedomtan** [comment]
ADE20K: original in PNG. Maybe we can try do segmentation PNG first. @freedomtan

**Comment by freedomtan** [comment]
To use `.png` to replace `.jpg` input images: adding `.png` to supported file formats is enough, see  e6379eb
To use `.png` for ground truth, couple lines of changes needed, see 2f815fd

On Pixel 7 Pro, with Pixel backend:
|.jpg|.png|
|---:|----:|
| 0.5889| 0.5897|
|<img src="https://user-images.githubusercontent.com/3395998/233523796-232b4fe8-3777-41de-930a-f3d65e0c1234.png" width="200"  />|<img src="https://user-images.githubusercontent.com/3395998/233523902-364185c7-3452-435a-8835-6f632ea9a6d2.png" width="200"  />|


- Use `.png` for input images: better quality.
- Use `.png` for groundtruth: reduced file size: 
  - `.raw`: 512x512x2000 = 524,288,000 bytes.
  - `.png`:  < 10 MiB

**Comment by freedomtan** [comment]
In the group meeting this week, @Mostelk mentioned if the NCHW vs NHWC issue. I read through the [PNG RFC](https://www.rfc-editor.org/rfc/rfc2083), it seems the PNG doesn't NCHW natively. So, for super resolution case, options I can think out right now:

1. use raw format (".rgb8")
2. add some output processing hook as we did for input tensors

**Comment by Mostelk** [comment]
One solution to try is; adopt PNG for input processing only, and leave rgb8 (NHWC and NCHW options) for accuracy calculation as current case.

**Comment by mohitmundhragithub** [comment]
I tried this change: https://github.com/mlcommons/mobile_app_open/compare/use_png_for_ade20k
with our backend, but got very poor accuracy. 

![image](https://user-images.githubusercontent.com/1549325/234016806-7cac7a33-a29e-4f88-acce-e60a05cfdb8d.png)

Will need to debug this further to find out the actual reason for this difference though.

**Comment by freedomtan** [comment]
> I tried this change: https://github.com/mlcommons/mobile_app_open/compare/use_png_for_ade20k with our backend, but got very poor accuracy.
> 
> ![image](https://user-images.githubusercontent.com/1549325/234016806-7cac7a33-a29e-4f88-acce-e60a05cfdb8d.png)
> 
> Will need to debug this further to find out the actual reason for this difference though.

Weird. I assume both the ground truth and the output tensor to are uint8, maybe that's a problem?

**Comment by freedomtan** [comment]
> One solution to try is; adopt PNG for input processing only, and leave rgb8 (NHWC and NCHW options) for accuracy calculation as current case.

Yes, that's the solution 1. I thought.

**Comment by freedomtan** [comment]
@AhmedTElthakeb and @Mostelk  to try it.
@mohitmundhragithub will try again.

**Comment by freedomtan** [comment]
To test the super-resolution task, replace ".rgb8" files with ".png" files is supposed to just work.

**Comment by mohitmundhragithub** [comment]
![image](https://user-images.githubusercontent.com/1549325/234193514-1a01e3dd-da49-464b-a46a-075c7b165602.png)

@freedomtan, Accuracy is fine with the dataset which you shared

**Comment by AhmedTElthakeb** [comment]
We are OK replacing annotations to PNG, but prefer to stick with original JPEG images as input.

**Comment by freedomtan** [comment]
@freedomtan to send the PR, but we can keep using the JPEG inputs for ADE20K.
