### ISSUE TITLE
Checksum validation failed.

### ISSUE THREAD

**Issue by priyanka994** [mlcommons/mobile_app_open#696]
Current, when i am trying to run MLPerf Mobile_app on MI13 i am getting checksum validation failed.
May I know what is the issue??

**Comment by anhappdev** [comment]
Please try to clear the app cache in the settings screen or delete and reinstall the app.

**Comment by priyanka994** [comment]
still its showing the same.

**Comment by anhappdev** [comment]
Which APK did you use? From the release page or did you self build the app? Can you post a screenshot here?

**Comment by priyanka994** [comment]
From the released page

**Comment by anhappdev** [comment]
@mohitmundhragithub Can you please take a look at this?

**Comment by mohitmundhragithub** [comment]
@anhappdev It looks like the monthly quota limit for mobile_models repo has got over now. Because of which, it's downloading some error html instead of actual file.

**Comment by anhappdev** [comment]
The issue should now be resolved in the latest release:
https://github.com/mlcommons/mobile_app_open/releases/tag/v3.0
