### ISSUE TITLE
Use GitHub release for publishing models and dataset

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#698]
Currently, we use Git LFS for storing `*.dlc` files in https://github.com/mlcommons/mobile_models because some `*.dlc` files are over 100 MB in size. Git LFS has a limited bandwidth quota. 

Maybe we can just use the GitHub release feature instead. It has no bandwidth limit and a file can be up to 2 GB in size (see https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases)

**Comment by freedomtan** [comment]
@anhappdev please help to put dlc files into the release page of  https://github.com/mlcommons/mobile_models

**Comment by anhappdev** [comment]
@mohitmundhragithub @freedomtan
The SNPE models are released at https://github.com/mlcommons/mobile_models/releases/tag/v3.0-snpe
