### ISSUE TITLE
offline image classification is slow for for CPU only cases

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#701]
As reported by @mohitmundhragithub: when CPU fallback is used for offline image classification, the speed is around 
10 queries per second, which means  it takes around 40 mins for classification offline model. 

Should we change this? Either reduce minimum images to test only for CPU offline model, or put maximum time limit (so that we can terminate earlier).

**Comment by mohitmundhragithub** [comment]
Its not just for calculate accuracy, but for performance mode for offline as well.

e.g. on some device if for the offline mode, the app gets 10QPS. This means for 24576 images, it will take 2457 secs to complete performance mode, which is 2457/60 ~= 40mins.

**Comment by mohitmundhragithub** [comment]
It was decided to explore loadgen, if we can have some max timeout... say 10mins.
@anhappdev can you please check if its possible?

**Comment by anhappdev** [comment]
> It was decided to explore loadgen, if we can have some max timeout... say 10mins.
> @anhappdev can you please check if its possible?

Ok. I will check that.

**Comment by anhappdev** [comment]
Yes, we can specify a `max_duration_ms` when running the test, currently we use the default value of 0.

https://github.com/mlcommons/inference/blob/b410a27269a1878a8d4e7b29e397e7b72f317257/loadgen/test_settings.h#LL191C1-L201C10

**Comment by anhappdev** [comment]
I added a static max duration of 10 minutes. If we want to configure this parameter, we can either do it:
1. In the app settings screen, similar to how the cooldown duration is set.
2. In the `tasks.pbtxt` file for each task separately.

I prefer the first option, in the settings screen, since the user can control it. Please share your thoughts?

**Comment by mohitmundhragithub** [comment]
IMHO, better to make it an app level policy for max time instead of providing the option to user.

**Comment by freedomtan** [comment]
10 minutes look to be fine. Let's do it. NOT configurable should be OK.

**Comment by freedomtan** [comment]
@freedomtan to check if we can get valid results on some lower tier TFLite CPU-only devices or use Firebase to test it.
