### ISSUE TITLE
Check if we can get rid of manage all file permission

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#702]
Currently, we have to manually enable the "Manage All Files Access Permission". That's not intuitive and could not be submit to Google Play Store.

https://github.com/mlcommons/mobile_app_open/pull/621

**Comment by anhappdev** [comment]
I spent more time to resolve the issue but could not success.

Without the permission `MANAGE_EXTERNAL_STORAGE` the app can only read media files (`*.jpg`) but not other file types like `*.pbtxt` or `*.tfrecord`. Still don't know why.

For user convenience, we can use this package https://pub.dev/packages/permission_handler to request `MANAGE_EXTERNAL_STORAGE` permission and it will show the UI for that. But it still doesn't resolve the issue that we still need the `MANAGE_EXTERNAL_STORAGE` permission.

**Comment by freedomtan** [comment]
@freedomtan to test if this package [https://pub.dev/packages/permission_handle](https://pub.dev/packages/permission_handler) work for devices having all file access permission in different places

**Comment by anhappdev** [comment]
I am moving the discussion from https://github.com/mlcommons/mobile_app_open/issues/727#issuecomment-1608830898 to this issue for better tracking.

> With the `all file permission` we used currently, it cannot be published to the Play Store.
> 
> Can we ignore this `all file permission` for Play Store publishing.
> 
> what if we make all the filenames with file extension like .png or .jpg (.txt -> .png). If this gonna work? @anhappdev to check it.

Renaming the file extension to a media file extension like .jpg or .png as @freedomtan suggested does work.
I renamed `coco_val_full.pbtxt` to `coco_val_full.jpg` and the app can now read the file without the read all file permission.

The question now is if and how we use this work-around. Using a not correct file extension is ... well... "not correct".

**Comment by freedomtan** [comment]
Let's do something like `coco_val_full.pbtxt.pseudo.png` for `coco_val_full.pbtxt` so that we can remove the scary "all file permission".

**Comment by anhappdev** [comment]
Noted that if the local path in `tasks.pbtxt` is a directory. All files in that directory must be renamed to have a media file type extension.
For example, in the SNUSR dataset, if a vendor still uses `.rgb8` files instead of `.png`, all `.rgb8` files should add the `pseudo.png` extension.

**Comment by freedomtan** [comment]
We have to remove this permission and either
1. have all the datasets in /sdcard/Android/app_name/ (not /data/app/, @freedomtan to update this to the correct name), or
2. we have to rename all of those .png or .jpg files (and change corresponding dataset cpp files)


Let's do 1. first (for submitting 4.0 to the Play Store). Let's discuss if we want to implement 2. later.

copying data from `cp -r /sdcard/mlperf_data/mlperf_datasets to /sdcard/Android/.....`
