### ISSUE TITLE
Update v3.0 release notes

### ISSUE THREAD

**Issue by Mostelk** [mlcommons/mobile_app_open#717]
Need to provide release notes with the v3.0 and also update the Release Notes included with the app, with updated vendor backend descriptions https://docs.google.com/document/d/1xQT7KuDUA871GdguxXzTq2MDDdq1DYIRDXqpdnq1iz0/edit#heading=h.nz45hizhp445.
 We need to build a new app with updated release notes included.

**Comment by TheKanter** [comment]
What exactly am I supposed to do here? I already wrote most of the text in the google doc. Could you give me a bit more guidance?

**Comment by mohitmundhragithub** [comment]
I have updated the writeup from Qualcomm.

**Comment by freedomtan** [comment]
We are still waiting from confirmation from Google folks. @TheKanter

**Comment by freedomtan** [comment]
@anhappdev please take descriptions from the doc @Mostelk shared and update the 3.0 app. If updating 3.0 apk release is not possible, we can have 3.0.1 release

**Comment by anhappdev** [comment]
I think this change in https://github.com/mlcommons/mobile_app_open/pull/721 should be included in the new 3.0 release build.

**Comment by Mostelk** [comment]
@anhappdev The working group reviewed and signed off on this, please include page 1 in the release notes in the release page, and the rest to update the corresponding description in the app, and release v3.0x version.

**Comment by Mostelk** [comment]
> I think this change in #721 should be included in the new 3.0 release build.

@mohitmundhragithub please confirm

**Comment by anhappdev** [comment]
There is a part called `MLPerf Mobile App Descriptions` which should be included in the app. Should we create a new screen to display the text, and where should it be? A new sub menu in the settings screen or a new `About` menu?

**Comment by Mostelk** [comment]
> There is a part called `MLPerf Mobile App Descriptions` which should be included in the app. Should we create a new screen to display the text, and where should it be? A new sub menu in the settings screen or a new `About` menu?

I thought there is already such description in the app, if not looks we can add an About or sub menu in the configuration screen where we pick and check the tasks to run.

**Comment by anhappdev** [comment]
> if not looks we can add an About or sub menu in the configuration screen 

I would create a new menu like in this screenshot (replace the Help with About)
<img src="https://github.com/mlcommons/mobile_app_open/assets/85728587/409e5dc1-4003-41e4-a97d-48960d2ac94e" width="300">

> Also I found in the results section, when you click the task, the description pops up, we need to update this with the newer description.

Ok

**Comment by mohitmundhragithub** [comment]
> dd an About or sub menu in the configuration screen where we pick and check the tasks to run. Also I found in the results section, when you click the task, the descr

good to have it.

**Comment by Mostelk** [comment]
LGTM, @anhappdev  please share apk for test

**Comment by anhappdev** [comment]
Adding a drawer like in the screenshot requires much more code changes than I expected, so to meet the deadline, I went with a submenu in the config screen.

APK for testing can be downloaded from https://github.com/mlcommons/mobile_app_open/pull/723#issue-1737395660

**Comment by Mostelk** [comment]
@anhappdev I think the prelease looks good. The only thing is the Description and Installation instructions should come on top of page, Followed by MLPerf Mobile App V3.0, title, which is directly followed by the Release Notes

**Comment by anhappdev** [comment]
> The only thing is the Description and Installation instructions should come on top of page, Followed by MLPerf Mobile App V3.0, title, which is directly followed by the Release Notes

What should be the title of the release?

<img width="1187" alt="Screenshot 2023-06-07 at 11 38 11" src="https://github.com/mlcommons/mobile_app_open/assets/85728587/937f3803-2453-414a-9a18-7bcd16e4e5dc">

**Comment by Mostelk** [comment]
I think the release title looks good

**Comment by anhappdev** [comment]
> I think the release title looks good

So only one `MLPerf Mobile App v3.0` title in the top is good? Or should I add the `MLPerf Mobile App v3.0` title again right above `Release Notes`?

**Comment by anhappdev** [comment]
There is a Windows build at: 
https://github.com/mlcommons/submissions_mobile_3.0/issues/15

Should it be released on the same page of this release?
https://github.com/mlcommons/mobile_app_open/releases/tag/v3.0

BTW, there is an installation instruction for Android, but not for Windows.

**Comment by anhappdev** [comment]
I created a draft for Windows build as a separated release here:
https://github.com/mlcommons/mobile_app_open/releases/tag/untagged-32b6452c904e9826b3da

**Comment by freedomtan** [comment]
Let's remove the "Pre-" make the 3.0 release as a formal one.

**Comment by anhappdev** [comment]
Closed as v3.0 is released.
