### ISSUE TITLE
add single stream and offlline task for MNEdgeTPU-V2-L

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#719]
We want replace MobileNet EdgeTPU with [MobileNet EdgeTPU-V2-L](https://github.com/tensorflow/models/tree/master/official/projects/edgetpu/vision#edgetpu-optimized-vision-models). Let's try have two more tasks at the main screen.  Let's create a new branch to see if 8 tasks are too crowded.

We need both fp and qint8 tflite files (@Mostelk to add the links to tflite files)
fp: from the tf-model site
quint: from tf-hub

**Comment by Mostelk** [comment]
Official saved model and INT8 TFLite License: [Apache-2.0] (https://opensource.org/licenses/Apache-2.0)  https://tfhub.dev/google/lite-model/edgetpu/vision/mobilenet-edgetpu-v2/l/1 
https://tfhub.dev/google/edgetpu/vision/mobilenet-edgetpu-v2/l/1 
Frozen Graph and FP32 TFLite (exported from above)  https://drive.google.com/file/d/1--A9EI8Ntr_Q5CH0WblFvUctVI_6VkcR/view?usp=sharing

**Comment by anhappdev** [comment]
> Frozen Graph and FP32 TFLite (exported from above) https://drive.google.com/file/d/1--A9EI8Ntr_Q5CH0WblFvUctVI_6VkcR/view?usp=sharing

It looks like the fp32 model did not work with dynamic batch size > 1. I got this error:
```
ERROR: external/org_tensorflow/tensorflow/lite/kernels/reshape.cc:85 num_input_elements != num_output_elements (2002 != 1001)
ERROR: Node number 80 (RESHAPE) failed to prepare.
```

**Comment by anhappdev** [comment]
Script to convert the TensorFlow model to TFLite FP32 model. This one works with dynamic batch size > 1.

```python
# TF2 version
import tensorflow as tf
import tensorflow_hub as hub

# Get the model
keras_layer = hub.KerasLayer('https://tfhub.dev/google/edgetpu/vision/mobilenet-edgetpu-v2/l/1')
model = tf.keras.Sequential([keras_layer])
model.build([None, 224, 224, 3])
input_tensor = tf.ones((4, 224, 224, 3))
output_tensor = model(input_tensor)

# Convert the model
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float32]
tflite_model = converter.convert()

# Save the model.
save_path = "./mobilenet-edgetpu-v2-L_fp32.tflite"
with open(save_path, 'wb') as f:
  f.write(tflite_model)

print(f"Model saved to {save_path}")
```

**Comment by freedomtan** [comment]
we don't need this anymore
