### ISSUE TITLE
Define what needs to be done for launching App to playstore 

### ISSUE THREAD

**Issue by peladodigital** [mlcommons/mobile_app_open#727]
What requirements exist to launch an app in the playstore? What are we missing?

**Comment by RSMNYS** [comment]
Hi guys! 

First of all we need to add description and assets, such as:

Main store listing section

1. Listing
- App name;
- Short app description;
- Full app description;
2. Graphics
- App icon ( PNG or JPEG, 512 px by 512 px);
- Feature graphic (PNG or JPEG, 1,024 px by 500, https://support.google.com/googleplay/android-developer/answer/9866151?hl=en);
- Phone screenshots;
- Tablet screenshots;

App Content section
Fill in policies (privacy, ads, app access and so on, there are some questionaries to do this).

After this is done, we can create our release. First we can create the release in the internal testing channel, and add user's groups by emails, who can test, or open this for everyone who wants to join the beta testing. Next, if all good, we can promote the build to the production. 

The build should be signed with the keystore (which you should save in some safe place). This is needed to upload the updates.

**Comment by anhappdev** [comment]
This issue will need to be resolved: https://github.com/mlcommons/mobile_app_open/issues/702.

**Comment by freedomtan** [comment]
@peladodigital we should start discussing this in the mobile working group meeting

**Comment by freedomtan** [comment]
> This issue will need to be resolved: #702.

With the `all file permission` we used currently, it cannot be published to the Play Store.

Can we ignore this `all file permission` for Play Store publishing.

what if we make all the filenames with file extension like .png or .jpg  (.txt -> .png). If this gonna work?  @anhappdev to check it.

**Comment by freedomtan** [comment]
Supposedly, we are targeting to have the app submitted to Play Store after we have an app which merge all the  3.1 submissions. Roughly, around mid-Oct.

**Comment by anhappdev** [comment]
- Closed in favor of https://github.com/mlcommons/mobile_app_open/issues/840
