### ISSUE TITLE
Error, when building android libs on the MacBook M1

### ISSUE THREAD

**Issue by RSMNYS** [mlcommons/mobile_app_open#738]
When execute the command **make flutter/android** this error occurs: ~/local_config_cc/BUILD:44:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'

**Comment by freedomtan** [comment]
did you have environment variable `ANDROID_NDK_HOME` set?

**Comment by RSMNYS** [comment]
That was the reason! Closing this issue. Thanks for the help.
