### ISSUE TITLE
App is not installed on certain android devices. 

### ISSUE THREAD

**Issue by RSMNYS** [mlcommons/mobile_app_open#739]
We have Pixel 5 and 4XL with latest android. When trying to install  mlperfbench-v3.0-qsmgt.apk we have the device is not yet supported error.
![image](https://github.com/mlcommons/mobile_app_open/assets/17128789/3a085758-584f-4414-86b7-8862e1b921d9)

**Comment by freedomtan** [comment]
That's why we added "default fallback"

**Comment by RSMNYS** [comment]
Where the user can get the apk with the default fallback implemented?

**Comment by anhappdev** [comment]
> Where the user can get the apk with the default fallback implemented?

The released version with all backends already has a fallback (the TFLite backend), but it may not work with certain phones if the vendor chooses not to support it. Please see https://github.com/mlcommons/mobile_app_open/pull/700 for more detail.

**Comment by RSMNYS** [comment]
I was able to prepare the dedicated build with the TF and Pixel backends. Now the user can install the apk on his pixel device.

**Comment by anhappdev** [comment]
Close as resolved.
