### ISSUE TITLE
Migrate all benchmark_setting to new schema with delegate_choice

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#748]
In https://github.com/mlcommons/mobile_app_open/pull/674 we introduced the option to define multiple delegate choices in a benchmark setting. For compatibly we still have glue code to support the old schema, but it should be removed to keep the code clean and maintainable.

https://github.com/mlcommons/mobile_app_open/blob/1466e102562e274f9e663e5cab18f60119c4ae1d/flutter/cpp/proto/backend_setting.proto#L52-L63

Let use this issue to track the migration of each backend and remove the deprecated field when all backends have been migrated.

- [x] TFLite
- [x] Apple
- [x] Pixel
- [x] MediaTek
- [x] QTI
- [x] Samsung

**Comment by freedomtan** [comment]
@freedomtan to do the MediaTek. Try to fix the Pixel one.
@RSMNYS  to check the apple one
@AhmedTElthakeb please help on the Samsung one

**Comment by RSMNYS** [comment]
1. Why do we hardcode the delegates, and not getting them during the runtime to show to the user?
2. Currently Apple backend doesn’t have an option to set the configuration with the delegate, so the task is about to make it possible, right? So in the mlperf_backend_configuration_t the selected_delegate will be passed, and using it we need to setup the model to use this delegate?

I found the apple supports four options for the delegates: CPU, GPU, Neural Engine, and Metal Performance Shaders. The idea is to use those for the each benchmark we have?

**Comment by freedomtan** [comment]
For Apple:

- TFLite backend: delegate (CoreML, GPU (metal)).
- Core ML backend: (CPU + Neural Engine) for newer iPhone models, not sure which one is best for (CPU+GPU)?

**Comment by anhappdev** [comment]
@RSMNYS  
1. The `delegate_choice` hard-coded in the `*.pbtxt` file is actually the configuration for that delegate. If there are multiple `delegate_choice` available, it will be shown as a list for user selection in the benchmark configuration screen.
 
2. For `mobile_back_apple` each `benchmark_setting` should have multiple `delegate_choice` based on [MLComputeUnits](https://developer.apple.com/documentation/coreml/mlcomputeunits). We don't want to show CPU only, so I think [`all`, `cpuAndGPU`, `cpuAndNeuralEngine`] should be enough.
When setting the `MLComputeUnits`, the Apple backend should catch the error if that `MLComputeUnits` is not available, then fallbacks to the next one and reports the actually used accelerator in the API call `mlperf_backend_accelerator_name()`.
For example, if the user chooses `cpuAndNeuralEngine` on an iPhone 8 (but Apple Neural Engine is first available on iPhones XS and later) so the backend should fall back to `cpuAndGPU`, and report back the GPU as the accelerator used.

**Comment by freedomtan** [comment]
- Pixel backend: #753 
- MTK backend: #754

**Comment by anhappdev** [comment]
Apple: 

- https://github.com/mlcommons/mobile_app_open/pull/758
