### ISSUE TITLE
Create a submission branch for v3.1

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#759]
- [x] to have updated Samsung backend, https://github.com/mlcommons/mobile_app_open/pull/762
- [x] random number seeds (get them from the main inference group), https://github.com/mlcommons/inference/commit/f7df3acb6880b6b3a92cd5a444d173137aa5d8ca
- [x] update loadgen version to 3.1? it seems there is nothing new, https://github.com/mlcommons/inference/commit/2da0c52666e21e4b296b09e1dbd287bf3a814e96

**Comment by anhappdev** [comment]
I think these issues should be resolved (PRs merged) before creating the v3.1 branch:

- https://github.com/mlcommons/mobile_app_open/issues/748
- https://github.com/mlcommons/mobile_app_open/pull/761
- https://github.com/mlcommons/mobile_app_open/pull/758

**Comment by freedomtan** [comment]
please test https://github.com/mlcommons/mobile_app_open/pull/761 and  #764, mostly they are supposed to just work. Let's test them anyway.

**Comment by freedomtan** [comment]
After report for the #764 (by @AhmedTElthakeb) and #761 (by all the vendors), we should be able to merge #765 and create the 3.1 submission branch.

**Comment by anhappdev** [comment]
As discussed, we all should test the APK from the [master branch](https://github.com/mlcommons/mobile_app_open/commits/master).

The APK can be downloaded by clicking on the green check mark > App Build Details > Summary: 

<img width="1555" alt="Screenshot 2023-08-08 at 16 27 33" src="https://github.com/mlcommons/mobile_app_open/assets/85728587/9e42b1b0-c9aa-4eff-b5d5-5ddf2382e8a1">

**Comment by freedomtan** [comment]
The `2023-08-08_mlperfbench-39d5152-qsmgt.apk`

- [ ] mtk: reported by @freedomtan "yes, it works as expected on some mediatek inside devices I test"
- [ ] qti:
- [ ] samsung:

**Comment by AhmedTElthakeb** [comment]
Starting commit https://github.com/mlcommons/mobile_app_open/commit/b086d99d1786ca2599ea19f69fa4456d3500c5ed upnormal behavior is observed on Samsung devices. With starting the app, a white screen shows up, after a while the screen shows an error message that "some resources failed to load ...", if I clear the cache, I could run okay.  

Please note that I tested https://github.com/mlcommons/mobile_app_open/pull/764 independently, it works fine.

**Comment by anhappdev** [comment]
@AhmedTElthakeb Is the error message shown every time the app starts? Can you reproduce the issue? Sometimes, when downloading resources (images, models) from the internet, a file may be corrupted, it will show that message. With clearing the cache, the files will be redownloaded.

**Comment by anhappdev** [comment]
@AhmedTElthakeb Regarding the white or black screen is shown at app start, this PR https://github.com/mlcommons/mobile_app_open/pull/770 will fix it. Thanks for the bug hint.

**Comment by freedomtan** [comment]
@mohitmundhragithub We're trying to have the 3.1 branch created this week. Please check if we can do it after #770.

**Comment by anhappdev** [comment]
https://github.com/mlcommons/mobile_app_open/commits/submission-v3.1

**Comment by mohitmundhragithub** [comment]
> @mohitmundhragithub We're trying to have the 3.1 branch created this week. Please check if we can do it after #770.
> 
> If we didn't get the response before the group meeting on Wed, we'll just go ahead creating the branch.

this seems to be working fine.

**Comment by mohitmundhragithub** [comment]
The branch seems to be ok, but i found few issues with the qti settings file, which is good to merge as well. not mandatory though, as these changes will come as part of our submission as well. 

https://github.com/mlcommons/mobile_app_open/pull/773

**Comment by freedomtan** [comment]
it's done
