### ISSUE TITLE
Apple backend should check if ANE available

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#768]
Currently, if an Apple device has no Apple Neural Engine, it falls back to use CPU but still reports ANE as accelerator used.
The Apple backend should check if an ANE is available and report correctly the accelerator used.

**Comment by RSMNYS** [comment]
@anhappdev can you please attach the screenshot

**Comment by anhappdev** [comment]
> @anhappdev can you please attach the screenshot

Please see https://github.com/mlcommons/mobile_app_open/pull/758#discussion_r1281482124
