### ISSUE TITLE
Add crash reporting to Flutter app

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#772]
We can add [Firebase Crashlytics](https://firebase.google.com/docs/crashlytics) to the Flutter app. 

> Firebase Crashlytics is a lightweight, realtime crash reporter that helps you track, prioritize, and fix stability issues that erode your app quality. Crashlytics saves you troubleshooting time by intelligently grouping crashes and highlighting the circumstances that lead up to them.

**Comment by anhappdev** [comment]
Make this crash reporting optional (a toggle in the settings screen).

**Comment by RSMNYS** [comment]
@anhappdev  will you work on that, or me?

**Comment by anhappdev** [comment]
I will do that because I have some other Firebase related issues open.

**Comment by anhappdev** [comment]
Firebase Crashlytics needs to upload symbol files in the build step:
https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=flutter 

I could not find a way to make this optional, which means that Firebase is always required to build the app.
