### ISSUE TITLE
How should I use 'dart run' instead?

### ISSUE THREAD

**Issue by andyyeh75** [mlcommons/mobile_app_open#776]
Hi team,

I tried to make this package under wsl, and it shows the error of dart below.  How should I use 'dart run' instead? Any code/script change?

> Deprecated. Use `dart run` instead.
Building package executable...
Failed to build build_runner:build_runner:
../../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {
                                                        ^
make: *** [flutter/flutter.mk:121: flutter/result/json] Error 1
root@yehandy-mobl2:~/mlperf/mobile_app_open# ../../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {^C

full log
> mlperf/mobile_app_open# make
WITH_TFLITE=1
[ -z "" ] || rm -rf output/flutter/pub
make \
        output/flutter/pub/flutter.stamp \
        output/flutter/pub/flutter_common.stamp
make[1]: Entering directory '/root/mlperf/mobile_app_open'
WITH_TFLITE=1
cd flutter &&  flutter --no-version-check pub get
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Resolving dependencies...
  collection 1.17.2 (1.18.0 available)
  device_info_plus 8.2.2 (9.0.3 available)
  file 6.1.4 (7.0.0 available)
  file_picker 5.2.10 (5.5.0 available)
  http 0.13.6 (1.1.0 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  package_info_plus 3.1.2 (4.1.0 available)
  pedantic 1.11.1 (discontinued replaced by lints)
  petitparser 5.4.0 (6.0.1 available)
  platform 3.1.0 (3.1.2 available)
  process 4.2.4 (5.0.0 available)
  share 2.0.4 (discontinued)
  share_plus 6.3.4 (7.1.0 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test_api 0.6.0 (0.6.1 available)
  uuid 3.0.7 (4.0.0 available)
  vm_service 11.7.1 (11.10.0 available)
  win32 3.1.4 (5.0.7 available)
  xml 6.3.0 (6.4.2 available)
Got dependencies!
mkdir -p output/flutter/pub
touch output/flutter/pub/flutter.stamp
cd flutter_common &&  flutter --no-version-check pub get
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Resolving dependencies...
  _fe_analyzer_shared 61.0.0 (64.0.0 available)
  analyzer 5.13.0 (6.2.0 available)
  build 2.3.1 (2.4.1 available)
  build_daemon 3.1.1 (4.0.0 available)
  build_resolvers 2.2.1 (2.3.1 available)
  build_runner 2.3.3 (2.4.6 available)
  build_runner_core 7.2.7+1 (7.2.10 available)
  built_value 8.6.1 (8.6.2 available)
  code_builder 4.5.0 (4.6.0 available)
  collection 1.17.2 (1.18.0 available)
  ffi 2.0.2 (2.1.0 available)
  file 6.1.4 (7.0.0 available)
  flutter_lints 2.0.2 (2.0.3 available)
  http 0.13.6 (1.1.0 available)
  js 0.6.5 (0.6.7 available)
  json_serializable 6.6.2 (6.7.1 available)
  lints 2.0.1 (2.1.1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  path_provider 2.0.15 (2.1.1 available)
  path_provider_android 2.0.27 (2.2.0 available)
  path_provider_foundation 2.2.4 (2.3.1 available)
  path_provider_linux 2.1.11 (2.2.1 available)
  path_provider_platform_interface 2.1.0 (2.1.1 available)
  path_provider_windows 2.1.7 (2.2.1 available)
  platform 3.1.0 (3.1.2 available)
  plugin_platform_interface 2.1.5 (2.1.6 available)
  source_gen 1.3.2 (1.4.0 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test_api 0.6.0 (0.6.1 available)
  uuid 3.0.7 (4.0.0 available)
  watcher 1.0.2 (1.1.0 available)
  win32 4.1.4 (5.0.7 available)
  xdg_directories 1.0.1 (1.0.3 available)
Got dependencies!
mkdir -p output/flutter/pub
touch output/flutter/pub/flutter_common.stamp
make[1]: Leaving directory '/root/mlperf/mobile_app_open'
[ -z "" ] || rm -rf output/flutter/pub
cd flutter_common &&  flutter --no-version-check pub run \
        build_runner build --delete-conflicting-outputs
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Deprecated. Use `dart run` instead.
Building package executable...
Failed to build build_runner:build_runner:
../../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {
                                                        ^
make: *** [flutter/flutter.mk:121: flutter/result/json] Error 1
root@yehandy-mobl2:~/mlperf/mobile_app_open# ../../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {^C

**Comment by freedomtan** [comment]
I didn't try WSL/WSL2, I guess it should just work if you got right Flutter SDK version (please check https://github.com/mlcommons/mobile_app_open/blob/master/flutter/pubspec.yaml). 

@anhappdev might have better answer.

**Comment by anhappdev** [comment]
@andyyeh75 Unfortunately, I am not familiar with Windows so I cannot help much in this case.
But as @freedomtan suggested, please ensure you use the correct Flutter version (requires `>=3.7.1 <3.8.0`, tested with `3.7.6`)

**Comment by andyyeh75** [comment]
Thanks for the response. My flutter is new enough though.
# flutter --version

Flutter 3.13.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ff5b5b5fa6 (10 days ago) • 2023-08-24 08:12:28 -0500
Engine • revision b20183e040
Tools • Dart 3.1.0 • DevTools 2.25.0

**Comment by anhappdev** [comment]
> Thanks for the response. My flutter is new enough though.
> 
> # flutter --version
> Flutter 3.13.2 • channel stable • https://github.com/flutter/flutter.git Framework • revision ff5b5b5fa6 (10 days ago) • 2023-08-24 08:12:28 -0500 Engine • revision b20183e040 Tools • Dart 3.1.0 • DevTools 2.25.0

You need to use a compatible Flutter version, not the latest one. Please test with Flutter `v3.7.6`.

> please ensure you use the correct Flutter version (requires >=3.7.1 <3.8.0, tested with 3.7.6)
