### ISSUE TITLE
Change settings (whether to use accelerator, number of threads)

### ISSUE THREAD

**Issue by K-R-U-T-I** [mlcommons/mobile_app_open#78]
# EVALUATION_APP_PATH=//java/org/mlperf/inference
# bazel build -c opt --cxxopt='--std=c++14' --fat_apk_cpu=x86_64,arm64-v8a ${EVALUATION_APP_PATH}:mlperf_app
# adb install -r bazel-bin/${EVALUATION_APP_PATH}/mlperf_app.apk

After building & installing the app using these commands, Change settings (whether to use accelerator, number of threads) options not visible. [MLPerf App](https://github.com/mlcommons/mobile_app_open/tree/master/android/java/org/mlperf/inference)

**Comment by relja128** [comment]
Is this a UI issue? Could you please attach a screenshot of what you're referring to?

**Comment by K-R-U-T-I** [comment]
This is the screen after clicking on the hamburger menu icon to go to settings.

<img src="https://user-images.githubusercontent.com/38699938/135032743-e6934506-00db-429f-9966-495d03ce7577.jpeg" width="350" height="550">

& here I'm not able to change any settings (whether to use accelerator, number of threads)

<img src="https://user-images.githubusercontent.com/38699938/135032783-58f1d33f-aa27-45d3-9218-cb200211f017.jpeg" width="350" height="550">

**Comment by relja128** [comment]
We currently don't have any settings that can be changed in the menu. Depending on application version and hardware detected, some menu items may have changeable parameters, but in general the menu is static for now. We will clean this up before a public launch.
