### ISSUE TITLE
Suspicious SoC names in iPhone results.

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#783]
@anhappdev  and @RSMNYS 
I was browsing results we sent to firebase so far and find this

```json
"environment_info": {
    "platform": "ios",
    "value": {
      "android": null,
      "ios": {
        "os_version": "Version 16.2 (Build 20C52)",
        "model_code": "iPhone14,3",
        "model_name": "iPhone 13 Pro Max",
        "soc_name": "Intel Xeon Gold 5218"
      },
      "windows": null
    }
  },
```
The `"soc_name": "Intel Xeon Gold 5218"`  definitely is wrong.

the json file is inside the `2SX6QevwLSaBQY8pBKfQCFpQgZs1` directory

**Comment by anhappdev** [comment]
@freedomtan Maybe the app is run on an iPhone simulator?

**Comment by freedomtan** [comment]
> @freedomtan Maybe the app is run on an iPhone simulator?

OK. `"Intel Xeon Gold 5218"` still looks suspicious
