### ISSUE TITLE
[iOS] the app doesn't build with Xcode15

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#785]
To preparing for upcoming iPhone 15 Pro, I updated all the devices to macOS Sonoma and iOS 17.0 Release Candidate, as we as Xcode 15. When I run
```
$ flutter build ios 
```
I got 
```
$ flutter build ios
Changing current working directory to:
/Users/freedom/work/mobile_app_open/flutter
Building com.mlcommons.inference for device (ios-release)...
Automatically signing iOS for device deployment using specified development team
in Xcode project: .........
Running Xcode build...                                                  
Xcode build done.                                            5.0s
Failed to build iOS app
Error (Xcode): DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS,
use TOOLCHAIN_DIR instead


Encountered error while building for device.
```
It turns out that, we need to update `DT_TOOLCHAIN_DIR` to `TOOLCHAIN_DIR` as instructed by the message in 
`flutter/ios/Pods/Target\ Support\ Files/Firebase/Firebase.release.xcconfig`  and `flutter/ios/Pods/Target\ Support\ Files/Firebase/Firebase.debug.xcconfig`. I did it manually and got a working App. 

I think it's should be possible to do it in the `Podfile`. However, I totally forget how to write `ruby`. 

@anhappdev and @RSMNYS please help making the app work with Xcode 15.

PS. Xcode 15 works on latest macOS Ventura 13.5.x, if you are unwilling to upgrade to Sonoma 14.0 RC yet.

**Comment by RSMNYS** [comment]
Here is the fix: https://github.com/mlcommons/mobile_app_open/pull/786
