### ISSUE TITLE
merge Qualcomm's 3.1 submission

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#789]
merge related patches and put .dlc files to mobile_models

**Comment by mohitmundhragithub** [comment]
@anhappdev,

I can't upload the DLC files that were generated. 
Can you please uplaod the files to github.com/mlcommons/mlperf_models please?

**Comment by anhappdev** [comment]
@mohitmundhragithub Please check 
https://github.com/mlcommons/mobile_models/releases/tag/v3.1-snpe
