### ISSUE TITLE
Merge submission-v3.1 branch into master

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#794]
To do:

- [x] Remove `patchelf` (https://github.com/mlcommons/mobile_app_open/pull/787)
- [x] Merge QTI backend (https://github.com/mlcommons/mobile_app_open/pull/799)
- [x] Merge Samsung backend (#811)

Open issues:

- [x] QTI backend caused crash in non-supported devices. (https://github.com/mlcommons/mobile_app_open/pull/805)

**Comment by mohitmundhragithub** [comment]
https://github.com/mlcommons/mobile_app_open/pull/805

I have created this PR to push the latest fixes from submission-v3.1 to master branch.

**Comment by freedomtan** [comment]
since both #805 and #811 are merged, we can close this for now
