### ISSUE TITLE
create an integrated 3.1 submission based release

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#800]
Since we had #791 and #796 merged. Let's check if the integrated app works as expected. If yes, we can release it on github.

**Comment by anhappdev** [comment]
We can use the CI to build the release APK: 
* https://github.com/mlcommons/mobile_app_open/pull/801

**Comment by anhappdev** [comment]
Please test the APK from here:
https://github.com/mlcommons/mobile_app_open/actions/runs/6465004288

**Comment by AhmedTElthakeb** [comment]
I tested on couple devices, in both cases this apk crashes while checking for qti backend.
`Abort message: 'cpp/backend_qti/qti_backend_helper.cc:123 runtime 0 is not available on this platform'`

**Comment by mohitmundhragithub** [comment]
> I tested on couple devices, in both cases this apk crashes while checking for qti backend. `Abort message: 'cpp/backend_qti/qti_backend_helper.cc:123 runtime 0 is not available on this platform'`

can you please share the logcat logs?

**Comment by anhappdev** [comment]
@mohitmundhragithub The app also crashed on Android simulator.

**Comment by freedomtan** [comment]
FYR. It works on some MediaTek devices and Google Pixel 7/8 Pro.

**Comment by mohitmundhragithub** [comment]
https://github.com/mlcommons/mobile_app_open/pull/804

This PR should fix the issue i think.

**Comment by mohitmundhragithub** [comment]
@AhmedTElthakeb, can you please try this apk out? 
https://github.com/mlcommons/mobile_app_open/pull/804#issuecomment-1764270801

**Comment by freedomtan** [comment]
FYR. #804 works as expected on some MediaTek devices and Pixel devices.

**Comment by freedomtan** [comment]
Let's have a release from #804 -based 3.1 branch. @anhappdev: please prepare a release (with supported platforms updated).

**Comment by anhappdev** [comment]
Please check the pre-release here:
https://github.com/mlcommons/mobile_app_open/releases/tag/v3.1

**Comment by freedomtan** [comment]
@mohitmundhragithub and @AhmedTElthakeb: please help confirm if this pre-release apk works as expected.

**Comment by mohitmundhragithub** [comment]
> Please check the pre-release here: https://github.com/mlcommons/mobile_app_open/releases/tag/v3.1

This apk seems to be working fine for Qualcomm.

**Comment by AhmedTElthakeb** [comment]
> @mohitmundhragithub and @AhmedTElthakeb: please help confirm if this pre-release apk works as expected.

Seems to work fine for Samsung

**Comment by freedomtan** [comment]
@Mostelk: with that, we are ready to have a formal 3.1 release.

**Comment by anhappdev** [comment]
@mohitmundhragithub @AhmedTElthakeb @Mostelk @freedomtan 
Please also check the description text whether the supported devices are correct.

**Comment by mohitmundhragithub** [comment]
> @mohitmundhragithub @AhmedTElthakeb @Mostelk @freedomtan Please also check the description text whether the supported devices are correct.

qti backend will support default backend as well. May be we can include that as well?

**Comment by freedomtan** [comment]
> > @mohitmundhragithub @AhmedTElthakeb @Mostelk @freedomtan Please also check the description text whether the supported devices are correct.
> 
> qti backend will support default backend as well. May be we can include that as well?

Sounds good to me.

@anhappdev please add this to to what's new and QTI-backend

**Comment by anhappdev** [comment]
> @anhappdev please add this to to what's new and QTI-backend

Text updated.

**Comment by freedomtan** [comment]
@mohitmundhragithub and @AhmedTElthakeb do we have other concerns? if NO, let's make this a public release.

CC: @Mostelk

**Comment by mohitmundhragithub** [comment]
its ok for us.

**Comment by AhmedTElthakeb** [comment]
looks good

**Comment by freedomtan** [comment]
@anhappdev please make it a formal release.

**Comment by anhappdev** [comment]
> @anhappdev please make it a formal release.

Done.
https://github.com/mlcommons/mobile_app_open/releases/tag/v3.1
