### ISSUE TITLE
To update the UI of app

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#806]
1. Let's get figma 

- [ ] design from Hanjo @RSMNYS: please help.

2. Let's check feasibility of implementing Hanjo's design: e.g., is there any clear obstacles. 

- [ ] give feedbacks if something is hard to implement
- [ ] and try to finalize the design
- [ ] scope out the work

3.
4. ....

**Comment by RSMNYS** [comment]
Hi guys! Here is the figma file: https://www.figma.com/file/og9GrHGzMQ9PSp8CFCPVdb/Design-Audit?type=design&node-id=69%3A535&mode=design&t=rWeSndRRQQXSMCK8-1

**Comment by anhappdev** [comment]
Please find the effort estimation here:
https://docs.google.com/spreadsheets/d/13hmH3EpnSo7MLOzukxfqiMmJ37GhRXFZUbBQRMPAhuE/edit?usp=sharing

**Comment by anhappdev** [comment]
- [ ] S1 - Resource loading screen
- [ ] S2 - Start screen
- [ ] S3 - Run progress screen
- [ ] S4 - Result screen
- [ ] S5 - History screen
- [ ] S6 - Settings screen
- [ ] S7 - Menu screen https://github.com/mlcommons/mobile_app_open/pull/815

**Comment by banjo247** [comment]
@freedomtan hi there! I still need to handle the sharing/reporting side of the application. The previous files sent through was either a JSON file which I think was a bit confusing as it covers all parameters even if not used, and then David T sent through some excel file that wasn't entirely clear. Is there some kind of output file I can use to start creating some ideas about reports and report sharing of results?

**Comment by anhappdev** [comment]
@banjo247 The app will upload and share the result via a JSON file. Here is an example: [results.json](https://github.com/mlcommons/mobile_app_open/files/13496265/results.json)
We also have a description of the file here: https://github.com/mlcommons/mobile_app_open/blob/master/docs/result-spec.md

**Comment by freedomtan** [comment]
@banjo247: we used brown and blue to represent unofficial and official releases. Do you have any suggestion for colors other than current brown for "unofficial" builds.

**Comment by anhappdev** [comment]
@banjo247 @RSMNYS  We need
- [ ] a design / color for unofficial build (see https://github.com/mlcommons/mobile_app_open/pull/845)
- [ ] a new design for the history screen (see https://github.com/mlcommons/mobile_app_open/pull/832)

**Comment by anhappdev** [comment]
We should be good with the new UI in current state. If we need a new design on some screens, we can do it later by opening a new issue.
