### ISSUE TITLE
MobileNetEdgeTPU-V2 final model to be used

### ISSUE THREAD

**Issue by mohitmundhragithub** [mlcommons/mobile_app_open#810]
The links that were [shared earlier](https://docs.google.com/presentation/d/15NgyI0ez17rsQywAuGfeHE42kvOB3DrPsetjryAdeys/edit#slide=id.g240b4652761_0_13) has different files:

Link1: https://tfhub.dev/google/edgetpu/vision/mobilenet-edgetpu-v2/l/1
Link2: https://drive.google.com/file/d/1--A9EI8Ntr_Q5CH0WblFvUctVI_6VkcR/view?usp=sharing 

The TF model shared in Link2 has the dimensions fixed to 1x224x224x3.
The TF model shared in Link1 has the dimensions fixed to ?x224x224x3.

As per the description in [the slide ](https://docs.google.com/presentation/d/15NgyI0ez17rsQywAuGfeHE42kvOB3DrPsetjryAdeys/edit#slide=id.g240b4652761_0_13) Link 2 must have been extracted from Link1. But need confirmation on the final model. I think the one with dynamic batch would be be better.

**Comment by freedomtan** [comment]
Agree that we should support dynamic batch size for offline.

**Comment by mohitmundhragithub** [comment]
> Agree that we should support dynamic batch size for offline.
> 
> Actually, I think the official one is from https://github.com/tensorflow/models/tree/master/official/projects/edgetpu/vision#edgetpu-optimized-vision-models

Hi,

I checked this link. The TF version of the [MobileNetEdgeTPUv2-L](https://storage.cloud.google.com/tf_model_garden/models/edgetpu/checkpoint_and_tflite/vision/mobilenet-edgetpu-v2/l/mobilenet-edgetpu-v2-l.tar.gz) shared here is the checkpoint. And the tflite version shared in [link](https://storage.cloud.google.com/tf_model_garden/models/edgetpu/checkpoint_and_tflite/vision/mobilenet-edgetpu-v2/l/mobilenet_edgetpu_v2_l.tflite) is a fixed 1 batch model only.

I think the tfhub model shared in the slide (link 1 in my comment in this issue) should be good to use.

**Comment by freedomtan** [comment]
> > Agree that we should support dynamic batch size for offline.
> > Actually, I think the official one is from https://github.com/tensorflow/models/tree/master/official/projects/edgetpu/vision#edgetpu-optimized-vision-models
> 
> Hi,
> 
> I checked this link. The TF version of the [MobileNetEdgeTPUv2-L](https://storage.cloud.google.com/tf_model_garden/models/edgetpu/checkpoint_and_tflite/vision/mobilenet-edgetpu-v2/l/mobilenet-edgetpu-v2-l.tar.gz) shared here is the checkpoint. And the tflite version shared in [link](https://storage.cloud.google.com/tf_model_garden/models/edgetpu/checkpoint_and_tflite/vision/mobilenet-edgetpu-v2/l/mobilenet_edgetpu_v2_l.tflite) is a fixed 1 batch model only.
> 
> I think the tfhub model shared in the slide (link 1 in my comment in this issue) should be good to use.

Yes. the TF version is the checkpoint. But I thinks it's the original source. To get frozen pb or saved_model, you have to clone the repo and export the model to use the checkpoints / weights.

Nope, the TFLite model does support dynamic batch size. When I run it with `benchmark_model --graph=...  --use_nnapi=1 --input_layer=input --input_layer_shape=n,224,224,3`, where n > 1, I can get expected results on Pixel and MTK devices.

**Comment by mohitmundhragithub** [comment]
> > > Agree that we should support dynamic batch size for offline.
> > > Actually, I think the official one is from https://github.com/tensorflow/models/tree/master/official/projects/edgetpu/vision#edgetpu-optimized-vision-models
> > 
> > 
> > Hi,
> > I checked this link. The TF version of the [MobileNetEdgeTPUv2-L](https://storage.cloud.google.com/tf_model_garden/models/edgetpu/checkpoint_and_tflite/vision/mobilenet-edgetpu-v2/l/mobilenet-edgetpu-v2-l.tar.gz) shared here is the checkpoint. And the tflite version shared in [link](https://storage.cloud.google.com/tf_model_garden/models/edgetpu/checkpoint_and_tflite/vision/mobilenet-edgetpu-v2/l/mobilenet_edgetpu_v2_l.tflite) is a fixed 1 batch model only.
> > I think the tfhub model shared in the slide (link 1 in my comment in this issue) should be good to use.
> 
> Yes. the TF version is the checkpoint. But I thinks it's the original source. To get frozen pb or saved_model, you have to clone the repo and export the model to use the checkpoints / weights.
> 
> Nope, the TFLite model does support dynamic batch size. When I run it with `benchmark_model --graph=... --use_nnapi=1 --input_layer=input --input_layer_shape=n,224,224,3`, where n > 1, I can get expected results on Pixel and MTK devices.

when i use this tflite model, somehow it doesn't work for us. 

Is it ok to use the saved model from link 1?

**Comment by mohitmundhragithub** [comment]
It was discussed in the meeting today that it's ok to use Link 1 as well.
We may need to save a copy of this model in github.com/mlcommons/mobile_open as well.

**Comment by freedomtan** [comment]
> It was discussed in the meeting today that it's ok to use Link 1 as well. We may need to save a copy of this model in github.com/mlcommons/mobile_open as well.

Agree. Let's send PR to mobile_open or mobile_models

**Comment by mohitmundhragithub** [comment]
The tfhub link now redirects to kaggle... but the downloadable model is the same.

**Comment by mohitmundhragithub** [comment]
I can't create a PR for the model.
@anhappdev can you please help for it?

**Comment by anhappdev** [comment]
> I can't create a PR for the model. @anhappdev can you please help for it?

Can you show a screenshot of the error?

**Comment by mohitmundhragithub** [comment]
No technical issues as such... Its more of a licensing issue. 
For me to download the model and then upload to mlcommons repo will require more approvals.

**Comment by freedomtan** [comment]
We chose another model. Close this for now.
