### ISSUE TITLE
simple web UI for submitted data

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#817]
Yes, most of us know how to read json files, but that's not convenient. 
We used to have some prototype web site, should we start from previous prototype or start a new one.

**Comment by anhappdev** [comment]
Do we need a website? 
Currently, the app can upload, download and display the results from the same account stored as JSON files in Firebase. We can modify it to download any results stored in Firebase.

**Comment by freedomtan** [comment]
Firebase Web hosting + React should be good enough. @RSMNYS please help have a prototype for this task.

**Comment by RSMNYS** [comment]
Hi guys! Did more adjustments. Please check, creds and url are the same. 
Also pushed the code to the branch. The project is linked to the test firebase account. Also added the README how to link to another firebase project and deploy.

**Comment by freedomtan** [comment]
> Hi guys! Did more adjustments. Please check, creds and url are the same. Also pushed the code to the branch. The project is linked to the test firebase account. Also added the README how to link to another firebase project and deploy. Working to add the filtering.

Please add some device/machine information to the results

**Comment by freedomtan** [comment]
@nathanw-mlc: please add @RSMNYS to the access list of the firebase project for the mobile app

**Comment by nathanw-mlc** [comment]
> @nathanw-mlc: please add @RSMNYS to the access list of the firebase project for the mobile app 

@RSMNYS should already have access to the mobile app firebase project through his MLCommons Google Workspace account. Is he needing elevated permissions?

**Comment by RSMNYS** [comment]
![Screenshot 2024-01-01 at 17 43 22](https://github.com/mlcommons/mobile_app_open/assets/17128789/cf14b006-5660-41b8-931d-b270c24af4f9)


> > @nathanw-mlc: please add @RSMNYS to the access list of the firebase project for the mobile app
> 
> @RSMNYS should already have access to the mobile app firebase project through his MLCommons Google Workspace account. Is he needing elevated permissions?

yes, I need the elevated permissions to manage the hosting.

**Comment by freedomtan** [comment]
- [ ] If we create an account when submitting (instead of anonymous one), we should be able to use that account.

**Comment by anhappdev** [comment]
@RSMNYS Please try a way to not expose the API key
https://github.com/mlcommons/mobile_app_open/security/secret-scanning/1

**Comment by anhappdev** [comment]
Just found out that we can set up a GitHub Action to deploy the website to Firebase automatically on new PR.
I will do the setup for it.

**Comment by nathanw-mlc** [comment]
> Just found out that we can set up a GitHub Action to deploy the website to Firebase automatically on new PR. I will do the setup for it.

Will @RSMNYS still need elevated permissions if we use this solution?

**Comment by RSMNYS** [comment]
In this case we need to expose the project's API key and other settings from Firebase. Generally that info is not secure, but let me know if we are ok to reveal this: @freedomtan, @anhappdev.

**Comment by anhappdev** [comment]
> In this case we need to expose the project's API key and other settings from Firebase. Generally that info is not secure, but let me know if we are ok to reveal this: @freedomtan, @anhappdev.

We should not expose the API key, at least not storing it in the code.
Please update file [firebase-config.ts](https://github.com/mlcommons/mobile_app_open/blob/610125e4a2ad2edf78d6ec4a169555d5f5596550/benchmarks_web_viewer/src/firebase-config.ts) so it can read the values from the environment variable like this: 
``` ts
const firebaseConfig = {
  apiKey: process.env.REACT_APP_FIREBASE_WEB_API_KEY,
  authDomain: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
  // ... 
};
```

Then we can store the key and other values in env:
```shell
export REACT_APP_FIREBASE_WEB_API_KEY=abcd
export REACT_APP_FIREBASE_AUTH_DOMAIN=acbd
```

**Comment by RSMNYS** [comment]
@anhappdev  it's clear, but how the GitHub will know this to build the app?

**Comment by anhappdev** [comment]
> @anhappdev it's clear, but how the GitHub will know this to build the app?

I will store it as a GitHub secret (https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions)

**Comment by RSMNYS** [comment]
Understood! Thanks.

**Comment by RSMNYS** [comment]
@nathanw-mlc  here are the env variables for the web app: 

REACT_APP_FIREBASE_WEB_API_KEY
REACT_APP_FIREBASE_AUTH_DOMAIN
REACT_APP_FIREBASE_DATABASE_URL
REACT_APP_FIREBASE_PROJECT_ID
REACT_APP_FIREBASE_STORAGE_BUCKET
REACT_APP_FIREBASE_MESSAGING_SENDER_ID
REACT_APP_FIREBASE_APP_ID
REACT_APP_FIREBASE_MEASUREMENT_ID

**Comment by anhappdev** [comment]
> @nathanw-mlc here are the env variables for the web app:
> 
> REACT_APP_FIREBASE_WEB_API_KEY REACT_APP_FIREBASE_AUTH_DOMAIN REACT_APP_FIREBASE_DATABASE_URL ...

I already added these as GitHub secrets for this repo.

**Comment by anhappdev** [comment]
This is the URL for the web UI.
https://mobile-app-build-290400.web.app

We can also use a custom domain / URL if @nathanw-mlc provides us one.

**Comment by nathanw-mlc** [comment]
> This is the URL for the web UI. https://mobile-app-build-290400.web.app
> 
> We can also use a custom domain / URL if @nathanw-mlc provides us one.

Hey Anh, where would I set that up?

**Comment by anhappdev** [comment]
> > This is the URL for the web UI. https://mobile-app-build-290400.web.app
> > We can also use a custom domain / URL if @nathanw-mlc provides us one.
> 
> Hey Anh, where would I set that up?

You can follow this guide:
https://firebase.google.com/docs/hosting/custom-domain

**Comment by nathanw-mlc** [comment]
https://mlperf-mobile.mlcommons.org/
