### ISSUE TITLE
Delete result uploaded to Firebase

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#830]
Should the user be able to delete the results which he already uploaded to Firebase?

**Comment by freedomtan** [comment]
It sounds reasonable to have `delete` / `remove` from a user's history. Overwrite a record might be an alternative.
If `delete` is hard to do, at least we have something dirty-bit (mark it as invalid /  deleted).

do we have the function to `delete` a user account? YES, we need kinda need this for privacy policy. Should remove the data associated with a particular account when the user deletes his/her account? It seems to be easy to do, so Let's do it.
