### ISSUE TITLE
For V4.0

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#836]
- [x]  new model: the model should be public before code freeze? Check with @colbybanbury this week. #722, #853, #821
- [x]  loadgen: https://github.com/mlcommons/mobile_app_open/pull/798
- [x]  UI update: https://github.com/mlcommons/mobile_app_open/issues/806
- [x] random number seed from the mail inference group once they are available. it's in https://github.com/mlcommons/inference/pull/1560/files#diff-4aea9ab8b222eed4a7096c6707e8e37682594dcb485d9b7450ad1b2e7155a853. We need to change the setting in the app. https://github.com/mlcommons/mobile_app_open/pull/863
- [x] Change the order of the test cases. in #722

**Comment by freedomtan** [comment]
Let's branch out v4_0, and try to add the three things above.

**Comment by anhappdev** [comment]
https://github.com/mlcommons/mobile_app_open/tree/submission-v.40

**Comment by mohitmundhragithub** [comment]
I think We need to reorder the test cases. Based on the past, the outgoing test cases should be put toward the end of the list i think.

the order should be
1) IC V2
2) OD
3) IS V2
4) LU
5) SR
6) IC V2 offline
7) IC
8) IC offline

**Comment by freedomtan** [comment]
Thanks for @anhappdev for merge all the necessary patches in the submission-v4.0 branch.

@mohitmundhragithub and @AhmedTElthakeb  Please help check if it is OK https://github.com/mlcommons/mobile_app_open/tree/submission-v4.0

**Comment by mohitmundhragithub** [comment]
> Thanks @anhappdev for merging all the necessary patches into the submission-v4.0 branch.
> 
> @mohitmundhragithub and @AhmedTElthakeb Please help check if it is OK https://github.com/mlcommons/mobile_app_open/tree/submission-v4.0

we tried it out. Everything looks ok to me.

**Comment by freedomtan** [comment]
- [ ] mediatek
- [ ] qualcomm
- [ ] samsung: it should be fine. need check again

**Comment by AhmedTElthakeb** [comment]
Looks ok to me
