### ISSUE TITLE
Preparing for submit the Android app (after 4.0) to the Play Store

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#840]
Let's try to list all the things we need to see if we still to something more:

- []
- []

**Comment by anhappdev** [comment]
- [ ] Set up a CI workflow to build and deploy APK to Play Store (@anhappdev)

**Comment by RSMNYS** [comment]
Here are the basic steps we need to follow up to submit the app:

1. Create a Developer Account 
2. Sign the App with a Release Key:
- [ ] Use the keytool command to generate a release key and a keystore file.
- [ ] Update app's build.gradle file with the signing configuration.
3. Create an App Listing on Google Play Store:
- [ ]  Log in to the Google Play Developer account and navigate to the Google Play Console.
- [ ] Click on "Create App" and provide necessary information like app's title, default language, and type (app or game).
4. Complete the App Listing Details:
- [ ]  Provide app title, 
- [ ]  Short and full description
- [ ]  App category 
- [ ]  Content rating, 
- [ ]  Contact details, 
- [ ]  And links to privacy policy and terms of service.
- [ ] Upload graphical assets like the app icon, screenshots, and feature graphic.
5. Set Pricing and Distribution:
6. Upload Android App Bundle or APK:
- [ ]  Build the app in release mode to generate an Android App Bundle (.aab) or an APK file.
- [ ]  In the Google Play Console, navigate to the "Releases" section and upload your app bundle or APK.
7. Publish the App

**Comment by anhappdev** [comment]
Related: 
* https://github.com/mlcommons/mobile_app_open/issues/727

**Comment by anhappdev** [comment]
- The app is rejected on Play Store with the following reason:
    > All Files Access Permission policy: Not a core feature
- We need to resolve the issue https://github.com/mlcommons/mobile_app_open/issues/702

**Comment by freedomtan** [comment]
@RSMNYS Please update screenshots with new UI for both Google Play and Apple App Store,

**Comment by anhappdev** [comment]
The app is now available for open testing at:
https://play.google.com/store/apps/details?id=org.mlcommons.android.mlperfbench
