### ISSUE TITLE
Add description for MobileNet V4 

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#885]
We need a description for the new MobileNet V4 model.

Here is the description for MobileNetEdgeTPU:

>  "benchInfoImageClassificationDesc": "Image classification picks the best label to describe an input image and is commonly used for photo search and text extraction. The MobileNetEdgeTPU reference model is evaluated on the ImageNet 2012 validation dataset and requires a minimum accuracy of 74.66% (98% of FP32 accuracy of 76.19%) Top-1 accuracy (For Performance measurements, App uses a different dataset).\n\nThe MobileNetEdgeTPU network is a descendent of the MobileNet-v2 family that is optimized for low-latency and mobile accelerators. The MobileNetEdgeTPU model architecture is based on convolutional layers with inverted residuals and linear bottlenecks, similar to MobileNet v2, but is optimized by introducing fused inverted bottleneck convolutions to improve hardware utilization, and removing hard-swish and squeeze-and-excite blocks.\n\nThe offline variant of image classification has no latency constraints and typically uses batched inference and has higher throughput.",

https://github.com/mlcommons/mobile_app_open/blob/9309f2867e39bbed2bf6947b6cd1ade37671c249/flutter/lib/l10n/app_en.arb#L122C3-L122C4

**Comment by freedomtan** [comment]
https://mlcommons.org/2024/05/mlperf-mobile-v4-0-release/
