### ISSUE TITLE
log_accuracy/mlperf_log_accuracy.json data attribute

### ISSUE THREAD

**Issue by fatihcakirs** [mlcommons/mobile_app_open#90]
Hello, 

In experiments, I've noticed that the ``data`` attribute in ``log_accuracy/mlperf_log_accuracy.json`` files differ across different backend choices. This is the case for all benchmarks except for image segmentation where the data attribute value is empty.

What is this attribute, and is it expected to differ across multiple vendor backends?

**Comment by relja128** [comment]
@mcharleb - I assume you know more about this?

**Comment by mcharleb** [comment]
That is all populated by the loadgen code AFAIK. I have no idea why it would be different.

**Comment by relja128** [comment]
As an example, DATA1 and DATA2 are entirely different between submitters for the same test (in this case, mobileBERT).

{ "seq_id" : 0, "qsl_idx" : 80, "data" : "DATA1" },
{ "seq_id" : 1, "qsl_idx" : 36, "data" : "DATA2" },

**Comment by freedomtan** [comment]
"data" field is for hexadecimal strings of "qsl_idx". So, they could same data expressed in different data types.
https://github.com/mlcommons/inference/blob/master/loadgen/loadgen.cc#L95-L129

**Comment by relja128** [comment]
log_accuracy/mlperf_log_accuracy.json contains processed input data (post quantization, normalization, swizzling, etc.). It is a mid-stage artifact of the process. The data will be consistent on the same backend over time, but not between backends.
