### ISSUE TITLE
make early-stopped appear as valid for Stable Diffusion

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#900]
We marked benchmark stopped by the early-stopping (> 64 images, > 10 mins) with different color. For Stable Diffusion, which runs quite long, we want to mark as valid (no different color).

**Comment by Mostelk** [comment]
> If Valid with Early Stopping ( 10 min and at least 64 samples), then visualize the output to be Valid if it is the Stable Diffusion Benchmark only the UI @anhappdev

**Comment by anhappdev** [comment]
* Implemented in the PR https://github.com/mlcommons/mobile_app_open/pull/903

https://github.com/mlcommons/mobile_app_open/blob/e0efbd3c29c41684cb626d142d2568f599f10575/flutter/lib/benchmark/performance_result_validity.dart#L51-L73
