### ISSUE TITLE
change random number seeds for 4.1

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#909]
we can get them from the main inference group: https://github.com/mlcommons/inference/

**Comment by freedomtan** [comment]
4.1 seeds are in https://github.com/mlcommons/inference/pull/1736

**Comment by anhappdev** [comment]
Implemented in https://github.com/mlcommons/mobile_app_open/pull/903/commits/600a04e37573b0d51830ddc55705682da6b96d21

**Comment by mohitmundhragithub** [comment]
Hi Anh,

We need find a way to pass the SD seeds as well.

"--seed", "-s", type=int, default=633994880, help="Dataset download location"

line 19 in text_to_image/tools/sample_ids.py in the same review.

**Comment by anhappdev** [comment]
@mohitmundhragithub should we use a hard-coded SD seed (easier to implement)?

**Comment by anhappdev** [comment]
With this PR https://github.com/mlcommons/mobile_app_open/pull/922 all backends can read the same `stable_diffusion_seed` and `stable_diffusion_num_steps` from the app.
