### ISSUE TITLE
Code freeze for 4.1 submission

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#911]
Let's try to freeze the code for v4.1 submission and create a 4.1 submission branch by this Friday (Sep 6th, 2024).

**Comment by anhappdev** [comment]
https://github.com/mlcommons/mobile_app_open/tree/submission-v4.1

**Comment by anhappdev** [comment]
@freedomtan Should I rebase `submission-v4.1` on master now?

**Comment by freedomtan** [comment]
I am for merging it to the `submission-v4.1` if @mohitmundhragithub and @AhmedTElthakeb (or @Mostelk) are not against it

**Comment by mohitmundhragithub** [comment]
should be okay to rebase.

**Comment by freedomtan** [comment]
> I am for merging it to the `submission-v4.1` if @mohitmundhragithub and @AhmedTElthakeb (or @Mostelk) are not against it

@anhappdev please do it then.

**Comment by anhappdev** [comment]
Done
