### ISSUE TITLE
changes needed for 4.1 repo

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#915]
1. mini query count and mini time should be the same as others: 1024 and 60 seconds
**maximum time (for early stopping): 300 seconds**

https://github.com/mlcommons/mobile_app_open/blob/master/flutter/assets/tasks.pbtxt#L296-L298

2. remove the mobilenet edgetpu, which is supposed to be retiredly for this round.

**Comment by anhappdev** [comment]
> 2. remove the mobilenet edgetpu, which is supposed to be retiredly for this round.

@freedomtan Only the image_classification V1 should be removed, and the V2 stays, correct?
