### ISSUE TITLE
Central place for documentation

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#99]
I think we need to have a central place for documentation or some solution to maintain documentation better.
The instructions are for example kind of copy & paste all over different repos and make it difficult to update.
There are many broken links and outdated instructions.
If someone has experience regarding this, please suggest a solution.

**Comment by mcharleb** [comment]
@anhappdev What audience? Submitters? End users? People building the app?

**Comment by anhappdev** [comment]
A solution is that we can create several entry points (README files) for different user group. In each of the file, we point the users to the right docs, kind of overview or table of contents. 
Those files can be placed here in `mobile_app_open`.

**Comment by anhappdev** [comment]
The structure of this repo `mobile_app_open` is currently in refactoring and evolving a lot. Wait until we have stable structure.

**Comment by relja128** [comment]
Top level README should include a table of contents including links to other repos as needed. Other than that we are sticking with READMEs per app / per repo.
